makejdk.sh
sbin/build.sh

Fixed a abs/relative path issue, also replaced hard-coded references to openjdk repo folder name with a variable

Minor fixes while building openjdk in native env (without docker)

---

README.md
sbin/jtreg.sh

Right now the plan seems to be:
- Make the xml results (from the jtreg run) visible.
- Get Jenkins to parse it.
- Make sure Jenkins lists the job as "failed" when the tests fail.

Make Changes to Allow Jenkins to Parse Jtreg Test Results

---

sbin/build.sh

- Replaced single quotes with double quotes, this enables parsing of variables within quotes strings

Fix broken OpenJDK build on s390x

---

makejdk.sh
sbin/build.sh
sbin/jtreg.sh

- replaced legacy ways of running a command using backticks with the `$()`
- `jtreg.sh`: extracted blocks of code into functions of its own (also includes work from @Bluevisitor)
- Added the missing JVM_VARIANT variable to debug message
- Refactored jtreg.sh, each code block is a bash function - easier to s...
- Fixed the url to jtreg binary - now corrected to the one on ci.adopto...
- Refactored blocks of bash code into functions of its own, replaced old...
- Moved setting of environment variables from the function to the main...
- Merged changes from another change to fix bug with s390x builds
- Put a check around jtreg binary download to see if it exists otherwise do not download (is this desirable, let me know otherwise - im now doubtful of it)
- Changed the way jtreg is downloaded, …

Refactoring + some enhancements to build scripts

---

makejdk.sh
sbin/jtreg.sh

Currently we allow the user to say "run the default jtreg tests after the build is complete", but we don't allow the user to specify a subset.
If we want to run less tests than the default, or more, or if we want to run focused testing (in the event that a specific module has been changed recently), we'll need this option or something like it.

Allow user to specify tests we want jtreg to run

---

makejdk.sh

Fix to change made in the same area as changed by PR https://github.com/Bluevisitor/openjdk-build/commit/be63d41343d235dcb7a2c82472643157e82a85f8
Strangely this line was causing the issue:
```if [[ ! -z $JTREG ]]; then```
`If` block was executed irrespective of passing `--jtreg` or not
We couldn't have spotted this via pull requests, maybe we should discourage such constructs (as the above) reducing the chances of bugs slipping thru - @karianna @gdams any thoughts?

Do not run tests if not specified

---

sbin/build.sh
sbin/jtreg.sh
sbin/jtreg_prep.sh

This new script allows us to specify an existing Java and run jtreg against it, rather than building a new Java from scratch.

Run jtreg without building java

---

sbin/jtreg.sh

Injected the environment variable NUM_PROCESSORS into the jtreg script to allow parameterising the number of cores to use when running jtreg tests.
Fixes issues #30

Parameterise number of cores for test runs (jtreg)

---

.travis.yml
README.md
git-hg/git-hg.sh
makejdk.sh
sbin/build.sh
sbin/jtreg.sh
sbin/jtreg_prep.sh
sbin/signalhandler.sh

This fixes a number of warnings and errors from running the shell lint checker.
There are some real bugs (e.g. use of undefined vars), but most are safety features; notably 
1. using quotes around var expansion to avoid word splitting and globbing by the shell,
1. fail safe when `cd`'ing to a directory, especially where we `cd` then `rf -f`
Special bonus addition is the image in our README.md to show the testing status.

Fix shell script lint check errors

---

.travis.yml

This will run shellcheck on all files ending with '.sh' and report any static issues found.

Travis file for lint checking script files

---

makejdk-any-platform.sh

Change config for the ARM such that JVM_VARIANT can be overriden via makejdk-any-platform

Make JVM_VARIANT overrideable

---

sbin/build.sh

Noticed in the Jenkins jobs - build logs, colour codes weren't being picked up due to this

Fixes the failing issue on Jenkins - cannot find file ../colour-codes.sh

---

makejdk-any-platform.sh

Replaced hard-coded number of processors flag passed to --with-jobs, to environment variable NUM_PROCESSORS. Fixes issue #76.

Remove hard-coding of cores and using NUM_PROCESSORS instead

---

makejdk.sh
sbin/jtreg_prep.sh

Calling shift causes the next argument to be ignored

Stop calling shift when an argument has no parameters

---

sbin/build.sh

Adding the -q flag to the zip command to run the command in silent mode - this prevents unnecessary log messages in the log file and other text are visible and not become hidden when viewing the bottom of the log file in the browser or local machine editor

Adding the -q flag to the zip command to run the command in silent mode

---

makejdk.1
makejdk.sh
sbin/build.sh
sbin/common-functions.sh

- Corrected spelling of a variable name
- Accept a new command-line param to specify the location of the pre-built FreeType Font directory, instead of building one each time, for e.g,
```
./makejdk-any-platform.sh [other params] --freetype-dir=/path/to/new/installfreetype/
```
Look for the below message on the console or build.log:
```
---> Skipping the process of checking and downloading the FreeType Font dependency, a pre-built version provided at /path/to/new/installfreetype/ <---
```
Note: The way this is written, if an environment variable by the name 
`FREETYPE_DIRECTORY` is created with the correct location, the build scripts will pick it up and use it.
Also added some performance checks around the dependency downloads for future references, metrics will be written to both console …

Specify freetype dir for the FreeType Font library to build script

---

installer/docker/ubuntu/jdk/Dockerfile

Proposed Dockerfile to create image based on ubuntu 16:10 with a named adoptopenjdk binary jdk
This file uses AdoptOpenJDK API to download named release of a binary which is then installed in a /opt/java/openjdk-$RELEASE directory.
Samples, demos and doc are removed as part of the install.
The file can support different architectures in theory by using --build-arg ARCH=foo on build command.  
To use this file run (as examples)
`docker build --build-arg RELEASE=jdk8u162-b00 -t adoptopenjdk:jdk8u162 . `
or 
`docker build  -t adoptopenjdk:latest .`
Contents can be validated by using  `docker run -it adoptopenjdk /bin/bash`

Initial version of Dockerfile for ubuntu with jdk

---

makejdk.sh

we need to clean up any newly create files when the source already exists

add git clean -fdx to cleanup stage

---

installer/docker/README.md
installer/docker/ubuntu/jdk/Dockerfile
installer/docker/ubuntu/jdk/build.sh

Changed the process for creating a docker image from a standalone approach to one suitable to be driven from Jenkins. Relies on docker push capabilities provided by Jenkins Docker plugins.
Prototype process is working on jenkins
using my repo See https://ci.adoptopenjdk.net/view/all/job/openjdk_docker_jdk8_ubuntu_x86_64_image/
Images are being pushed to Dockerhub - https://hub.docker.com/r/adoptopenjdk/openjdk8/

Update to docker runtime image creation to enable pushing to docker hub

---

makejdk-any-platform.sh
makejdk.sh
sbin/build.sh

At the moment we are checking if we are running in AIX and then choosing to run `gmake` to build OpenJDK source, this can already been predetermined and set in the `makejdk-any-platform.sh` script like we do for the other platforms checks.
There is still some more such checks in the different scripts but that's for subsequent PRs.

Move aix related checks to main script

---

sbin/build.sh

Added shellcheck disable notation to not warn about `SC2086` - the variable will contain values with spaces and its okay

Resolve one of the Shellcheck warnings reported by TravisCI for PR #145

---

sbin/build.sh

Adding some echoes to the build.sh and common-functions.sh script files. Also changing to the image folder to be able to remove the AWT/GUI components from the demo folder in the newly created JDK image.
PR fixes issue #167.

Fixing issue with demo files not getting removed from with tarbal

---

makejdk-any-platform.sh

Typo in my last commit. $(OPENJDK_FOREST_NAME) will not extract the value of the variable OPENJDK_FOREST_NAME. ${OPENJDK_FOREST_NAME} will.

Replace curly braces with parenthesis because typo

---

makejdk-any-platform.sh

cloning of jdk8u failed when running with bash on macos

fixed stripping of \u\ char for jdk8

---

makejdk.sh

docker file path incorrectly generated when specifying jdk8u

fix docker building of jdk8u

---

makejdk.sh

when looking for containers to clean up the name was truncated in the docker ps command.  using --no-trunc avoids truncations and allows the name to be found.

fix finding existing containers

---

makejdk-any-platform.sh

This is actually a fix for https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/23
The logic in the parameter parsing is to cycle over each parameter and use a variable `counter` to indicate the current parameter. In the case wher ewe are parsing a parameter such as `--version jdk8` the value of `counter` is incremented to give us access to the next parameter. This brings it out of sync with `i` for any subsequent iterations of the loop.
What this means is that if something like `--version jdk8u --variant openj9` is used, then the value of the `variant` parameter will not be picked up properly. This can be fixed in two ways:
1. Use a different variable for the "temporarily incremented" `counter`
2. Reset the value of `counter` by decrementing it after it has been used to read the …

Fix parameter parsing error in makejdk-any-platform.sh

---

makejdk.sh

OpenJ9 builds don't work on gcc4.8 or later. We currently have to use separate build machines in order to handle this but we can use environment variables to manage this.

force openj9 builds to use gcc4.8

---

docker/jdk10/x86_64/ubuntu/Dockerfile

libfontconfig1-dev is a build dependency for jdk10 builds

add libfontconfig1-dev to jdk10 dockerfile

---

makejdk.sh

This reverts commit 4f9e3014ed3d72f9669d819d9d66a90412df6258.

Revert "force openj9 builds to use gcc4.8 (#228)"

---

sbin/build.sh

This causes the loss of the --with-milestone parameter. This fix stops it being overridden

Don't override CONFIGURE_ARGS when setting boot JDK

---

makejdk.sh
sbin/build.sh

This improvement allows the build script to take arguments in any
order, and also prevents conflicts between user-specified configure
args and configure args we add as part of the script.

Improve build script argument handling

---

git-hg/update-without-modules.sh

Enable synchronizing OpenJFX repository in GitHub.
This PR adds the possibility to use the git-hg scripts for synchronising the OpenJFX mercurial repository at http://hg.openjdk.java.net/openjfx/jfx-dev/rt with a git repository hosted on github.com.
The setup and update-without-modules scripts can then be called as follows:
$ ./setup.sh jfx open-jfx/jfx-dev/rt
$ ./update-without-modules.sh openjfx/jfx-dev/rt
The changes in the PR will only replace the first slash of the cli argument instead of all slashes.

Enable synchronizing openjfx repository into github

---

sbin/build.sh

If some parameters are empty, we don't want to use the configure
options that set those parameters. So is $hat is empty, we don't
want to use "--with-hat=$hat" .

Add isEmpty checks to some configure parameters

---

sbin/build.sh

Argument 1 will never be empty because we always pass hard-coded
strings. It is argument 2 we should be worried about, as that's the
one containing potentially-empty variables.

Undo build.sh typo

---

makejdk-any-platform.sh
sbin/build.sh

This changes the version string from:
`* Version string: 9-internal+0-adhoc.jenkins.openjdk (9-internal)`
to:
`* Version string: 9-adoptopenjdk+181 (9-adoptopenjdk)`

update version tags for jdk9 and later

---

sbin/common-functions.sh

Should fix https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/326

Replace 'file' use with '-r' check for CaCerts

---

docker/jdk10/x86_64/ubuntu/Dockerfile-openj9
docker/jdk8/x86_64/ubuntu/Dockerfile-openj9
docker/jdk9/x86_64/ubuntu/Dockerfile-openj9
makejdk.sh

Pass the right OPENJDK_CORE_VERSION to the docker build and update the Dockerfile-openj9 to add additional dependencies.

Fix broken docker build for OpenJ9

---

README.md
makejdk-any-platform.1

Updated man page for makejdk-any-platform.sh with latest options.
Updated REAME.md section for makejdk-any-platform.sh options and usage example. The --keep is replaced with -c (--keep is currently broken #198).

Makejdk man update

---

makejdk.sh

Resolve the problem from #198. The issue exist only for first build. The function buildDockerContainer has been triggered without args. Args have been removed and handled inside buildDockerContainer to simplify execution. 
I would assume that the disucussion of usfulness of -k should be considered as separte issue (refere to last comment from #198). 

fixed --keep option #198

---

docker/jdk10/x86_64/ubuntu/Dockerfile-openj9
docker/jdk8/x86_64/ubuntu/Dockerfile
docker/jdk8/x86_64/ubuntu/Dockerfile-openj9
docker/jdk9/x86_64/ubuntu/Dockerfile
docker/jdk9/x86_64/ubuntu/Dockerfile-openj9

Resolved issue #188. All docker MAINTAINER replaced with 
AdoptOpenJDK <adoption-discuss@openjdk.java.net>

update MAINTAINER in Dockerfile #188

---

pipelines/openjdk10_nightly_pipeline.groovy
pipelines/openjdk10_openj9_nightly_pipeline.groovy
pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_openj9_nightly_pipeline.groovy
pipelines/openjdk8_openj9_release_pipeline.groovy
pipelines/openjdk8_release_pipeline.groovy
pipelines/openjdk9_nightly_pipeline.groovy
pipelines/openjdk9_openj9_nightly_pipeline.groovy
pipelines/openjdk_amber_nightly_pipeline.groovy

Set nightly builds deployment per platform, keep release as before. This will need co-operation with configuration updates of build openjdk_{JVMVERSION}_build_checksum and openjdk_release_tool

Set nightly builds deployment per platform

---

pipelines/openjdk10_openj9_nightly_pipeline.groovy

Adding windows builds to the pipeline created in https://github.com/AdoptOpenJDK/openjdk-build/issues/272 now that https://github.com/AdoptOpenJDK/openjdk-build/issues/281 has been resolved

Add Windows to openjdk10_openj9 pipeline

---

pipelines/openjdk10_openj9_nightly_pipeline.groovy

Automate triggering of openjdk10-openj9 systemtest in x64x & ppc64le linux platforms once the sdk build job of these platforms succeeds. 
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

Automate trigger of openjdk10-openj9 systemtest in x64x & ppc64le linux

---

pipelines/openjdk10_openj9_nightly_pipeline.groovy

Add option to automatically trigger Openjdk10-Openj9 systemtest on zLinux

Automatically trigger Openjdk10-Openj9 systemtest on zLinux

---

sbin/build.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/302
Logic to obtain the exit code was incorrect

Handle and check exit code from make properly

---

pipelines/openjdk9_openj9_nightly_pipeline.groovy

Build job appears to be succeeding, so no reason not to have it in the pipeline

Add Windows to the openjdk9/openj9 nightly pipline

---

pipelines/openjdk8_openj9_nightly_pipeline.groovy

Adding Win32 and x64_linux_largeHeap to the openjdk8_openj9 nightly build pipelines
(for now keep as separate buildPlatforms, to be able to keep test lists separate/different from the win64, x64_linux builds)
Signed-off-by: smlambert <slambert@gmail.com>

Add Win32 & x64_linux_largeHeap

---

sbin/build.sh

Gah ... This is kinda why I don't use functions in my own shell scripts - can be hard to trace the flow, but not to worry.
This change ensures is changes into the source repo before trying to determine the tag (otherwise it picks up the tag from the `openjdk-build` repo apparently! Hopefully this won't result in any issues further down the line.
I've accidentally created this branch in the AdoptOpenJDK repo instead of my own so when merged please feel free to delete the branch.

Ensure tag from the source repo instead of openjdk-build is used

---

pipelines/openjdk10_nightly_pipeline.groovy
pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_openj9_nightly_pipeline.groovy
pipelines/openjdk8_release_pipeline.groovy
pipelines/openjdk9_nightly_pipeline.groovy

This change needs to be co-ordinated with updating Jenkins job names, and fixes the problem of no aarch64/arm64 builds showing up in the nightlies on the website.

WIP: Update arm64 name to be aarch64

---

pipelines/openjdk10_nightly_pipeline.groovy
pipelines/openjdk10_openj9_nightly_pipeline.groovy
pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_openj9_nightly_pipeline.groovy
pipelines/openjdk8_openj9_release_pipeline.groovy
pipelines/openjdk8_release_pipeline.groovy
pipelines/openjdk9_nightly_pipeline.groovy
pipelines/openjdk9_openj9_nightly_pipeline.groovy
pipelines/openjdk_amber_nightly_pipeline.groovy

At the moment we can't pass in an alternate parameter to the pipelines for the openj9 release build process. Previously we've done temporary modifications to the build jobs. Now that we have the branch able to be passed as a parameter to the build jobs, it makes sense to allow this to be passed in from the pipelines.
I've done this across all pipelines (not just the openj9 ones) for consistency, although we're only likely to use it for the openj9 builds. I've modified the pipelines to take an optional `ALT_BRANCH` parameter

Pipelines allow alternate branch

---

pipelines/openjdk10_nightly_pipeline.groovy
pipelines/openjdk10_openj9_nightly_pipeline.groovy
pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_openj9_nightly_pipeline.groovy
pipelines/openjdk8_openj9_release_pipeline.groovy
pipelines/openjdk8_release_pipeline.groovy
pipelines/openjdk9_nightly_pipeline.groovy
pipelines/openjdk9_openj9_nightly_pipeline.groovy
pipelines/openjdk_amber_nightly_pipeline.groovy

This is to pass PIPELINE_TIMESTAMP to build jobs (so they can be same across platforms, which will ensure they will be part of the same 'release' set on the website).
Signed-off-by: smlambert <slambert@gmail.com>

Add timestamps to top-level pipelines

---

pipelines/openjdk10_release_pipeline.groovy

We should really look at squashing all of these pipelines into 1 or 2 universal pipelines but here is the jdk10 release pipeline for now.

add jdk10 release pipeline

---

pipelines/openjdk8_nightly_pipeline.groovy

Recent openjdk8 build timestamp is either empty or use the build timestamp itself. It should use the timestamp generated by upstream pipeline job, which is passed in the jdk build job.

Fix empty string PIPELINE_TIMESTAMP issue

---

pipelines/openjdk10_nightly_pipeline.groovy
pipelines/openjdk10_release_pipeline.groovy

Should be ok now that https://github.com/AdoptOpenJDK/openjdk-build/issues/332 is resolved.
Note to reviewers: I'm currently running a release build of openjdk10/hotspot that won't have this change in, so Linux/arm32 isn't going to get released

Add Linux/arm32 (e.g. raspberry pi) back into openjdk10 pipeline

---

sbin/build.sh

Partially fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/262 (This will create the artefacts but they won't get as far as being published). Creating this PR mostly to review the names in parallel with me testing that it works.
I've chosen to create the tarball named OpenJRE.tar.gz as opposed to OpenJDK.tar.gz.
The directory name will be taken from the same name as the jdk (usually the tag from the repo) but with `jdk` substituted for `jre`. If `jdk` wasn't present in the original name then the `jdk` tar will get suffixed with `.jre`. If anyone has an issue with this naming scheme, please let me know before this is integrated.
I am currently trialling this on the [AO8/J9 jenkins job](https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/) which I have modified to …

Add support for creating JREs

---

pipelines/openjdk10_nightly_pipeline.groovy
pipelines/openjdk10_release_pipeline.groovy

ao10 builds are now down to the 2 hour mark (as a result of things done in https://github.com/AdoptOpenJDK/openjdk-build/issues/406) which makes it feasible to put them back into the nightly flows.

Add Linux/arm32 (e.g. raspberry pi) back into openjdk10 pipeline (#395)

---

sbin/build.sh

Speeds up the native arm32 builds significantly if pigz is available. Won't make such a difference to other platforms but shouldn't cause any negative effects, and will fall back to gzip if pigz is unavailable

Use pigz to compress instead of gzip if available

---

makejdk.sh
sbin/jtreg.sh

Pass in jdk version to jtreg as jdk test structure is different with
different jdk version

Pass in jdk version to jtreg

---

sbin/build.sh

JDK11 falls over in a heap if you try to use the parameters we've been using for previous versions.
This will also  need to be done in the new build scripts

Use --with-freetype=bundled for JDK11

---

pipelines/openjdk_amber_nightly_pipeline.groovy

All other pipelines use `yyyyMMddHHmm`.

Fix timestamp pattern for consistency

---

pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_openj9_nightly_pipeline.groovy

Default pipelines for some releases still have the version number hardcoded - we should fix this so it's a parameter in all flows, but for now I'll just change the defaults.
If no-one's reviewed this by the time I need to kick off the build tomorrow morning I'm going to make an executive decision to merge regardless

Update JDK8 build pipelines with version jdk8u181-b13

---

makejdk.sh

When `-dsgc` (or its expanded version) is given to `makejdk.sh` it results in a blank parameter being given to the git command (without `-dsgc` it's set to `--depth=1`) which confuses git and gives this error (note the double space between `clone` and `-b` wher the "empty" parameter is sitting:
```
Git repo cloning mode: deep (preserves commit history)
git clone  -b dev https://github.com/adoptopenjdk/openjdk-jdk11.git /space/pi3/workspace/openjdk11_build_arm32_linux/openjdk
Too many arguments.
usage: git clone [options] [--] <repo> [<dir>]
-v, --verbose         be more verbose
-q, --quiet           be more quiet
```

Stop -dsgc passing invalid empty parameter to git

---

pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_release_pipeline.groovy

This PR adds `Windows32` entry to `openjdk8` pipeline build map in order to have win32 artifacts to be generated and released.
Related to #384.

Add windows x86-32 target to openjdk8 build pipelines

---

pipelines/openjdk8_nightly_pipeline.groovy
pipelines/openjdk8_release_pipeline.groovy

This PR adds the missing pieces for #462 in order for the scheduled build pipelines to trigger builds for `Windows32` platform.

Add Windows32 to buildPlatforms list

---

makejdk.sh

- Git clean -fxd will not remove directories
that contain a Git repository (.git folder).
- Adding a second force will remove these folders
- Ref https://git-scm.com/docs/git-clean#git-clean---force

Force git clean to remove dirs with .git repos

---

pipelines/build/openjdk11_pipeline.groovy

This reverts commit e1499e919e2135d460e560f055f48810e61dcae5.
OpenJ9 builds already get the buildj9 tag added so this is not needed

Revert "Lock JDK11 to our VS2017 machine (tagged openj9 for now)"

---

pipelines/build/openjdk11_pipeline.groovy

Enable jdk11 systemtest build on aarch64 linux
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

Enable jdk11 systemtest build on aarch64 linux

---

README.md
docker-build.sh
docker/jdk10/x86_64/ubuntu/Dockerfile
docker/jdk8/x86_64/ubuntu/Dockerfile
docker/jdk9/x86_64/ubuntu/Dockerfile

Resolved issue #273. The ~/.ssh is exposed to docker with -v. In case of passphrase docker will reuse user ssh-agent. 
Extras description has been added to README. 
ssh packge has been added to Dockerfile for jdk8, jdk9 and jdk10

Docker builds do not honour the --ssh flag being passed through #273

---

sbin/common/config_init.sh

Add check to prevent `--help` arg throwing unbound variable error (example below) when no java version is provided.
```bash
./makejdk-any-platform.sh --help
Starting ./makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
Parsing opt: --help
/myworkspace/sbin/common/config_init.sh: line 158: $1: unbound variable
```
Signed-off-by: Parker Mauney <parkermauney@gmail.com>

Fix unbound variable error for --help arg

---

pipelines/build/openjdk11_pipeline.groovy

Add perftest category to all enabled platforms for jdk11. So when the test build is created it will be triggered automatically. No need to update those build script.

Add perftest category  to all enabled platforms for jdk11

---

configureBuild.sh
sbin/build.sh

THIS IS A BREAKING CHANGE
This will change the directory layout of the binaries to be the apple layout which is built at the same time as the main `JDK` and `JRE` images

build: change extracted image for macOS

---

configureBuild.sh
docker-build.sh
sbin/common/common.sh
sbin/common/config_init.sh

Resolved issue #583.
Added jdk version suffix to docker volumes
Clean up dockers containers using '-f volume=...'

docker builds leave volumes behind even when cleaning #583

---

pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy

Hopefully finally fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256
I'll remove the `build` tag from the two Ubuntu build machines when this is in.
Note for reviewers ref the removal of the boot JDK comment - `-2` has a JDK9 available now:
```
[root@build-osuosl-centos74-ppc64le-2 ~]# /usr/lib/jvm/jdk-9.0.4+11/bin/java -version
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+11)
OpenJDK 64-Bit Server VM (build 9.0.4-adoptopenjdk+11, mixed mode)
[root@build-osuosl-centos74-ppc64le-2 ~]# ^C
```

Switch ppc64le builds from Ubuntu to CentOS7

---

sbin/prepareWorkspace.sh

Equivalent of https://github.com/AdoptOpenJDK/openjdk-build/pull/626 but for freetype instead of cacerts
Fixes https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-windows-x64-openj9/

win/openj9 - download freetype with wget instead of curl

---

build-farm/platform-specific-configurations/windows.sh

Fix compilation failures by adding `--disable-warnings-as-errors` configure option and setting toolset version to 2013 for windows x86-32 builds.

Start building JDK11 for windows x86

---

build-farm/platform-specific-configurations/windows.sh

Logic error meant that the openssl options were only activated for win32 not win64. Reported by `latif` on Slack

Missing SSL options for JDK8/J9/Win64

---

sbin/common/common.sh

Fix tarball creation to get rid of the leading dots. A build of jdk8u on my workstation shows resulting tarball now match other JDKs layout:
```bash
$ ./makejdk-any-platform.sh  --docker -p 4  -J /usr/lib/jvm/zulu-7-amd64/ jdk8u
[...]
$  tar tvf  workspace/target/OpenJDK.tar.gz | head
drwxr-xr-x build/build       0 2018-10-18 20:59 jdk8u181-b13/
drwxr-xr-x build/build       0 2018-10-18 20:59 jdk8u181-b13/lib/
-rw-r--r-- build/build 2282796 2018-10-18 20:59 jdk8u181-b13/lib/sa-jdi.jar
-rw-r--r-- build/build  407738 2018-10-18 20:59 jdk8u181-b13/lib/jconsole.jar
-rw-r--r-- build/build  163049 2018-10-18 20:59 jdk8u181-b13/lib/dt.jar
-rw-r--r-- build/build 17793678 2018-10-18 20:59 jdk8u181-b13/lib/ct.sym
drwxr-xr-x build/build        0 2018-10-18 20:59 jdk8u181-b13/lib/amd64/
-rwxr-xr-x …
```

[WIP] Avoid leading dot from tarball paths (#660)

---

build-farm/platform-specific-configurations/linux.sh

Fixes this failure - I feel this could perhaps use a proper upstream fix though ...
```
Compiling 394 files for BUILD_jdk.compiler.interim
../../src/hotspot/cpu/arm/c1_LIRGenerator_arm.cpp: In member function ‘void LIRGenerator::do_ArithmeticOp_Int(ArithmeticOp*)’:
../../src/hotspot/cpu/arm/c1_LIRGenerator_arm.cpp:831:43: error: ‘out_reg’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
../../src/hotspot/cpu/arm/c1_LIRGenerator_arm.cpp:823:15: note: ‘out_reg’ was declared here
LIR_Opr out_reg;
^
../../src/hotspot/cpu/arm/c1_LIRGenerator_arm.cpp: In member function ‘void LIRGenerator::do_ArithmeticOp_Long(ArithmeticOp*)’:
../../src/hotspot/cpu/arm/c1_LIRGenerator_arm.cpp:761:74: error: ‘entry’ may be used uninitialized in this function [-Werror=maybe-uninitialized] …
```

Add --disable-warnings-as-errors to arm32

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh

Linux/ppc64le is trying to download a bootstrap JVM which requires a version of GLIBC that isn't in the path (probably because it was built on Ubuntu 16.04 ...)
At the moment any existing JDK10_BOOT_DIR defined on the jenkins machine configuration is ignored and JDK10_BOOT_DIR is set to $WORKSPACE/jdk-10 which is downloaded if it wasn't already cached from a previous run. This change will allow it to use a version of JDK10 from JDK10_BOOT_DIR which already exists on the box.
Will fix ppc64le/JDK11 build failures

Do not override JDK10_BOOT_DIR if already defined

---

build-farm/platform-specific-configurations/mac.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/561 (Once gcc49 is removed)
Must not be merged until the current JDK8/JDK11 with OpenJ9 release rebuilds are completed.

Updates to macos compiler as per OpenJ9 request

---

build-farm/platform-specific-configurations/windows.sh

In addition to https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/514 this resolves https://github.com/eclipse/openj9/pull/2979
Do not merge until OpenJ9 have commited their change to enable this
NOTE: This will block any ability to rebuild with OpenJ9 0.11.0 which requires MinGW

Replace MinGW with LLVM for Windows/OpenJ9

---

security/README.md

In JDK 9 or above, cacert is in 'jdk/lib/security ' folder.

Add jdk/lib/security as location of cacert

---

build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/windows.sh

This will prevent us rebuilding JDK9 and JDK10 with OpenJ9 which don't have the right options, but we shouldn't really need them again going forward anyway ...
It's currently enabled for JDK8 only, but the support is now in the 11 codebase.
Related: https://github.com/eclipse/openj9/pull/3992

Enable OpenSSL support in openjdk11 with OpenJ9

---

pipelines/build/openjdk11_pipeline.groovy

The changes to enable openssl on JDK11 seem to have caused problems when CCACHE is enabled.
This doesn't appear to occur outside jenkins so at least for now I'm going to disable it

Disable ccache on JDK11+OpenJ9 on x/p-Linux

---

sbin/common/common.sh

Unnecessarily and we already bypass this for AIX - no disadvantage to doing it the same way elsewhere (Plus this makes the gzip on AIX use `-9` which the previous syntax didn't ...)

Stop using GNU-tar specific option to create final archive

---

build-farm/platform-specific-configurations/windows.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/813

Ensure LLVM/clang 7 dir is in PATH before cygwin

---

sbin/build.sh

From @andrew-m-leonard : 
This appears to be happening unless `--topo-order` is specified on the git describe command line. This PR will add it. Not quite sure why openj9 is having this issue but the main hotspot mirror is not, but I will leave it to the openj9 team to justify if required. Have not 
```
[sxa@sxat470p openj9-openjdk-jdk11]$ git rev-list --tags --max-count=10 --topo-order | xargs git describe --tags
jdk-11.0.2+7
jdk-11.0.2+6
jdk-11.0.2+5-2-g743cc6ccf0
jdk-11.0.2+5-1-g6970e5c340
jdk-11.0.2+5
jdk-11.0.2+4-4-gf761c6949f
jdk-11.0.2+4-3-g3f60c236d4
jdk-11.0.2+4-2-ga31b99b526
jdk-11.0.2+4-1-gd81782b9b8
jdk-11.0.2+4
[sxa@sxat470p openj9-openjdk-jdk11]$ git rev-list --tags --max-count=10 | xargs git describe --tags
jdk-11.0.2+6 …
```

Use --topo-order when retrieving git tags

---

pipelines/build/openjdk_build_pipeline.groovy

Config map is [..., parameters[... ,ADDITIONAL_FILE_NAME_TAG:***, ...],...]

Fix test jobName with largeHeap Tag

---

pipelines/build/openjdk_build_pipeline.groovy

- Adds a 'queue' stage to the pipelines.
- This will indicate how long the build
waits for a node.
Fixes #863

Add queue stage to Jenkins pipelines

---

configureBuild.sh

I am not sure why `CONF` and the debug option is needed on `s390x` specifically, but this should resolve the lack of JRE in the release builds.
Running test at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-s390x-jre/5/console but if reviewers are happy with the change, feel free to approve/merge ;-)
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/885
NOTE FOR REVIEWERS: This is using `JDK11_CORE_VERSION` instead of `JDK11_VERSION` which is used in `setMakeArgs()` ... I'm a touch nervious that `setMakeArgs` isn't working since `OPENJDK_CORE_VERSION` is set to `jdk11u` in the JDK11 case, but `JDK11_VERSION` is `jdk11` without the `u` suffix (as defined in `sbin/common/constangs.sh`) hence I've used …

Ensure JRE target is called for Linux/s390x

---

build-farm/platform-specific-configurations/linux.sh

Should be enabling openssl bundling on all releases except jdk12, not the other away round

Fix jdk12 openssl setting

---

build-farm/platform-specific-configurations/windows.sh
pipelines/build/openjdk12_pipeline.groovy

JDK12u is supposed to be built with VS2017 toolchain. The PR changes a couple of things across build scripts;
1. It adds `vs2017` label to jdk12u windows build definitions.
2. Fixes a typo that resulted in picking `VS2013` as the toolchain in `windows.sh` file.
3. Re-organize `windows.sh` file to be more explicit on VS toolchains for jdk12u and jdk11u.

Update node labels, fix typo in script and be more explicit on versions

---

build-farm/platform-specific-configurations/aix.sh

Removed code is
```
if architecture = 'x64'
.....
```
which is not valid for aix and so will not be executed.
--with-freemarker-jar which the code sets is also set in sbin/build.sh

Remove redundant code

---

build-farm/platform-specific-configurations/mac.sh

mac: Only strip 3 dirs on boot JDK11, not JDK10

---

sbin/build.sh

Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>
The current build.sh doesnt get the correct tag when there are multiple tags with the same date on the same SHA. This change is to correctly get the latest tag from the SHA.

Correctly find latest tag from repo when there are multiple for same SHA

---

sbin/build.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/977
Also will throw a message to stderr if the tag detection fails - I could do an `exit 1` in that case but wanted to keep this critical fix simple for now in case that causes other side effects with some builds

Stop tag detection failing when there's a subdir with name of tag

---

sbin/prepareWorkspace.sh

In case of cross compilation on x86-64 systems for i686 targets, Freetype is not compiled for 32 bit.
See also: https://github.com/AdoptOpenJDK/TSC/issues/71#issuecomment-475451019

enforce compilation of freetype with 32 bit on i686 systems

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy

Don't believe there's any reason for this to be locked to marist-2 any more as the machine setup is the same.

Stop locking JDK11/12 on Linux/s390x to one build box

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/library/src/ParseVersion.groovy
pipelines/library/src/common/VersionInfo.groovy
sbin/build.sh
sbin/common/common.sh

- Stop generating hash json. 
- Use openjdk version for dir name. 
- Fix using readlink on solaris

Stop generating hash json, Use openjdk version for dir name, Fix using readlink on solaris

---

pipelines/library/src/common/VersionInfo.groovy

This will take the format of the path inside the archive from
- `jdk-8.0.212+1`
- `jdk-8.0.212+1-jre`
to:
- `jdk-8.0.212`
- `jdk-8.0.212-jre`
To fix any windows issues around `+` in a file name

Remove build number from path inside the build archive

---

build-farm/platform-specific-configurations/windows.sh
sbin/build.sh

Freetype dependency on windows requires building for 32-bit / 64-bit targets with the corresponding MSVC version that is used to build the jdk binaries. 
Given that;
1. we're already downloading freetype source code on the fly during build phase,
2. both hotspot and openj9 configure processes support `--with-freetype-src` argument to build the freetype binaries from given source tree with the detected MSVC compiler toolset, 
it seems no longer a requirement for us to handle freetype as a static dependency to configure on each build agent.
This PR removes several freetype configuration flags from windows configuration script, sets freetype version to be downloaded and adds the corresponding `--with-freetype-src` flags to the configure arguments.

Use downloaded freetype instead of relying on a pre-built version

---

build-farm/platform-specific-configurations/linux.sh

This should supercede https://github.com/AdoptOpenJDK/openjdk-build/pull/1018 but I've had reports that it may cause some build failures so I want to verify it more before integrating.

OpenJ9: Build against system openssl on Linux and don't reship it

---

build-farm/platform-specific-configurations/windows.sh

This PR contains a couple of improvements;
1. Use `--with-freetype-src` everywhere since it's now automatically compiled as part of the configure phase.
2. Cleanup of `PATH` entries as they're handled by the configure phase.
3. Do not exclude `TOOLCHAIN_VERSION` for JDK8U tag builds since it results in a different toolchain usage than the nightly builds.
4. Enable VS2017 for JDK11 and onwards for both x86 and x64 builds (x86 will fail, will need to get https://github.com/AdoptOpenJDK/openjdk-jdk11u/pull/7 merged first).

Use VS2017 for JDK11u and onwards

---

build-farm/platform-specific-configurations/linux.sh

Currently (after https://github.com/AdoptOpenJDK/openjdk-build/pull/1035 was merged) the number of parallel processes on arm32 builds is always being set to 1. With this, it will honour the `NUM_PROCESSORS` definition if we have one in the jenkins definition.

Fix core usage on ARM32 systems if NUM_PROCESSORS set

---

pipelines/jobs/configurations/jdk11u.groovy

Add support for aarch64 openj9 builds on JDK11

---

pipelines/jobs/pipeline_job_template.groovy

This reverts commit ad79f8fba437ee0d5f782dddb9f78e9b00970cf2.
Re-enables the nightly builds now that we have done the quarterly releases

Revert " Pre release build inhibitor (#1037)"

---

sbin/build.sh

Previously `--jvm-variant` args passed to our build scripts were not processed when building on `cygwin` or `msys`, i.e. on windows.
This PR extracts the configuration of `--with-jvm-variants` configure args to the shared code path so that it'll be processed in all build environments.
Part of changes related to #871.

Set --with-jvm-variants if provided by user

---

configureBuild.sh

Closes #1070
DCO 1.1 Signed-off-by: John Neffenger <john@status6.com>

Add Client VM to builds for Linux arm32 platform

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy

This PR makes 32-bit hotspot builds (for windows) to include `client` and `server` vm's.
Fixes #871.

Add client variant to 32-bit hotspot builds 

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy

This was merged for 32 bit builds in PR #1104, can this be added to 64-bit builds too?

Add jvm variant build arguments for 8, 11, 12 64-bit hotspot builds

---

build-farm/platform-specific-configurations/windows.sh

- Change location of OpenSSL 64 bit `/cygdrive/c/progra~1/OpenSSL` to `/cygdrive/c/openjdk/OpenSSL-1.1.1-x86_64`
- Change location of OpenSSL 32 bit `/cygdrive/c/progra~2/OpenSSL` to `/cygdrive/c/openjdk/OpenSSL-1.1.1-x86_32`
- This PR is to be done in conjunction with https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/750
@sxa555 
Signed-off-by: HusainYusufali <husainyusufali7@gmail.com>

Change location of OpenSSL in Windows - DO NOT MERGE

---

pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/build/openjdk_pipeline.groovy

With new test jobs are generated (test job name change), we need to
update the way tests are launched
Issue: #1116
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

Update the logic for launching tests

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk_pipeline.groovy

Additional test targets to launch via build pipelines (did not update jdk9/jdk10 as they are no longer run).

Add extended.system/special.functional to the set of launched test targets

---

sbin/prepareWorkspace.sh

We could get a non-default version of gpg on the box, but I prefer this to be able to keep the standard tools with the distribution in place.
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/834

Fix error with gpg when ~/.gnupg does not exist

---

build-farm/platform-specific-configurations/aix.sh

Taking an executive decision to push this through for now since it will only affect one platform and I need to test that this will fix a problem on the new machine. `wget` is failing to find it's dependent libraries properly without this on the newly set up AIX system (Same problem I had with git, but that was resolved by reverting to an older version).
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/146#issuecomment-516544918 

Ensure /opt/freeware/lib is at start of LIBPATH on AIX

---

entitlements.plist
entitlements_jdk8.plist
pipelines/build/common/openjdk_build_pipeline.groovy
sign.sh

This allows users to bundle AdoptOpenJDK binaries into notarized macOS applications. 
This is confirmed to be fixed on JDK11+
On JDK8 we still hit the same issue that the Corretto folks do which is this error:
```
The binary uses an SDK older than the 10.9 SDK
```
My suggestion would be that we investigate shipping a JDK8 build that is optimized for bundling (i.e built on a later toolchain) This [repo](https://github.com/stooke/jdk8u-xcode10) may be usefil as it contains some patches required to get JDK8 to compile on xcode10.

enable hardened runtime support for macos

---

pipelines/build/openjdk8_pipeline.groovy

ran a test openj9 build on the new digital ocean centos6 machines and it passed

remove pinning to joyent x64 linux machine

---

pipelines/build/common/openjdk_build_pipeline.groovy

This change forces the pipelines to sign the binaries before running tests

sign builds before running tests

---

build-farm/platform-specific-configurations/aix.sh
pipelines/build/openjdk13_pipeline.groovy

xlc16 is required for JDK13 - see also https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/773 which is the corresponding infrastructure issue. I have installed this on one of the AIX build machines for now and am using the `xlc16` tag to target the AIX JDK13 build to it.

Add XLC16 PATH entries for JDK13/AIX

---

build-farm/platform-specific-configurations/aix.sh

Had an extra line in there for the last commit which meant it set xlc16 for all builds

xlc16 build fix

---

pipelines/build/common/openjdk_build_pipeline.groovy

This should fix the recent build failures with the linux installers. The Jenkins job `create_installer_linux` expects a parameter `RELEASE_TYPE`. The value should be `Release` if it's a release and `Nightly` otherwise.
It's my first change to the build pipeline, so please double check.

Update parameters for create_installer_linux

---

pipelines/jobs/configurations/jdk13u.groovy

Ref: https://github.com/eclipse/openj9/pull/6584
xlc16 is available on one of the build machines which has allowed HotSpot builds of JDK13 to succeed but not OpenJ9

Disable AIX JDK13 until upstream OpenJ9 stable on xlc16

---

sbin/common/config_init.sh

Like Solaris and AIX, *BSD also has GNU make installed as gmake.  Switch to using a case statement so it's easier to incorporate additional OSes here and also so we can use *bsd rather than separately listing FreeBSD, NetBSD, and OpenBSD.

Use gmake on *BSD

---

docker/jdk11/x86_64/ubuntu/Dockerfile
docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk11/x86_64/ubuntu/dockerConfiguration.sh
docker/jdk12/x86_64/ubuntu/Dockerfile
docker/jdk12/x86_64/ubuntu/Dockerfile-openj9
docker/jdk12/x86_64/ubuntu/dockerConfiguration.sh
docker/jdk13/x86_64/ubuntu/Dockerfile
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/dockerConfiguration.sh

These were based heavily on the JDK10 Dockerfile, the only difference between them being the different JDK versions they install to build the JDK on the docker container.

Added JDK 11-13 Dockerfiles

---

makejdk-any-platform.1
sbin/build.sh
sbin/common/config_init.sh

Add the command line --make-args, similar to --config-args but for `make`
Fix for #1283

Add custom  commands accessible from makejdk-any-platform

---

docker-build.sh
docker/jdk10/x86_64/ubuntu/Dockerfile
docker/jdk11/x86_64/ubuntu/Dockerfile
docker/jdk12/x86_64/ubuntu/Dockerfile
docker/jdk13/x86_64/ubuntu/Dockerfile
docker/jdk8/x86_64/ubuntu/Dockerfile
docker/jdk9/x86_64/ubuntu/Dockerfile
sbin/build.sh

Fixes: #1216  
Ref: #1073 
These changes should allow for the Docker Builds to work, and subsequently the `buildDocker.sh` script.
The unbounded variables problem has been fixed by the `if` statements in `docker-build.sh`. It's not a very clean way of fixing it, but it works if the variables haven't been used in the case of not using `--debug-docker` or `--ssh` with `make-any-platform.sh`.
The problem of the `./gradlew` script no being found has been fixed by adding that into the Docker container, in `docker-build.sh` by the addition of `-v "${hostDir}/pipelines":/openjdk/pipelines \ `.
With the current version of Gradle that is put onto the containers, it can only be executed with Java-8. Therefore, all Dockerfiles have `zulu-8`, along with the JDK version needed for the `JDK_BOOT_DIR` …

Changed scripts to fix broken Docker builds

---

docker/jdk8/x86_64/ubuntu/Dockerfile

Forgotten from the last PR;
Error message from last JDK8 DockerfileCheck run say it's required.
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-DockerfileCheck/label=build-scaleway-x64-ubuntu-16-04-2,version=jdk8u/lastBuild/console

Add JDK8 dependency to Dockerfile

---

docker/jdk8/x86_64/ubuntu/Dockerfile

I mistakenly put an incorrect package name into the jdk8 Dockerfile. Changed to the correct package :-)

Changed 'libconfig' to 'libfontconfig' in jdk8 dockerfile

---

docker/buildDocker.sh

Requested by @sxa555 
Upon use of the `--eclipse` option, the script will retrieve the correct dockerfile from the `ibmruntimes/openjdk-openj9-jdkXX` repository, build a container using it and build the JDK on it.

Modified buildDocker for option to use Eclipse OpenJ9 dockerfiles

---

git-hg/freebsdRepoSync.sh

* Add a script that will allow the AdoptOpenJDK bot to automatically merge
changes from the AdoptOpenJDK repos into the FreeBSD child repos.
* The script itself doesn't contain the automation, but it gives an
automated facility (e.g. cron, an event queue) a single command to
execute to do the update.
* This could be used to perform a sync (manually or automatic) for any
child repository with a few tweaks.  In particular see CHILD_REPO_PATH
and SYNC_BRANCH.

Script to merge from AdoptOpenJDK into FreeBSD child repos

---

.dockerignore
docker-build.sh
docker/jdk8/x86_64/ubuntu/Dockerfile
docker/jdk8/x86_64/ubuntu/Dockerfile-openj9
sbin/common/common.sh
sbin/prepareWorkspace.sh

* some shell script changes to avoid errors from `set -u`
* separate the openj9 Dockerfile from the base dockerfile
* remove --no-options from gpg command lines, it caused errors
These changes may be made partially or fully irrelevant by what happens with https://github.com/AdoptOpenJDK/openjdk-build/pull/913 and https://github.com/AdoptOpenJDK/openjdk-build/issues/689, but opening a PR anyways in case they're useful in the interim.

fixes for building OpenJ9 using docker

---

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk12/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
docker/jdk8/x86_64/ubuntu/Dockerfile-openj9

Based mostly off the JDK8 fixed openj9 dockerfile from #1171
- Added an additional dependency (on top of the JDK8 additions) that 11-13 needed.
- Set JAVA_HOME in jdk8,11 and 12 dockerfiles.
- 13 needed `JDK8_BOOT_DIR` to be set instead of `JAVA_HOME`. Not entirely sure why, but it couldn't find java 8 for Gradle to use without it.
- All of them use Ubuntu 16 in the containers, as opposed to Ubuntu 18, as this stopped a freemarker checksum issue that has occurred since updating to Freemarker 2.3.29
- Ensured `MAINTAINER` is `LABEL maintainer=...`
Tested and working on MacOS :)

Fixed Openj9 Dockerfiles (8,11-13)

---

git-hg/freebsdRepoSync.sh

* Issuing 'git push --tags' will only push the tags, so also do a regular
'git push' as well to push the changes.
Interestingly, 'git fetch --tags' fetches both the changes and the tags

FreeBSD sync: Push changes as well as tags

---

sbin/common/config_init.sh
sbin/prepareWorkspace.sh

allows a user to parse a git repository link containing patches to be applied at build time to the openjdk source code.

Allow patches to be applied at build time

---

git-hg/freebsdRepoSync.sh

* In the situation where the repository already exists, pull changes
before attempting to reset ourselves to origin/branch to ensure that
all of the origin changes are present.  Otherwise there may be
additional changes on the origin that will cause push to fail.

Pull changes when working with an existing repository

---

docker/buildDocker.sh

Sets `$WORKSPACE` to `$HOME` if it's undefined or unbounded. Helpful when fixing the dockerfiles locally.

Add check for WORKSPACE var in buildDocker.sh

---

sbin/common/common.sh

`readlink` fails if `$(which javac)` is not a symlink.

Use `/usr/libexec/java_home` on macOS.

---

docker-build.sh
docker/jdk11/x86_64/ubuntu/Dockerfile
docker/jdk13/x86_64/ubuntu/Dockerfile
docker/jdk8/x86_64/ubuntu/Dockerfile

An issue found whilst I was attempting to setup the `SXA-DockerfileCheck` job onto `infra-vagrant-1`. Every job failed due to an inability to find a file that was there, whenever running from the `buildDocker` script as the Jenkins user, however worked for the main user.
Some digging showed that inside the container, the files that were shared between the host system and the container were owned by UID 1001, which was not owned by any user in the container, but did correspond to the Jenkins UID of the host machine.
As such, I've changed it so the user made within the docker container ("build") will have the same UID from the person that started the `buildDocker.sh` script.

Dockerfiles: Made container user UID and host UID the same

---

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
docker/jdk8/x86_64/ubuntu/Dockerfile-openj9

*Correctly* changing the openj9 Dockerfiles so the container user has the same UID as the user who started the Dockerfiles (or the `buildDocker` script)

Dockerfiles: Changed container UID to host UID for j9 files

---

docker-build.sh

Initially looked at due to the `build-scaleway-x64-ubuntu-16-04-2` machine constantly filling up. 
- The `if` statement at the end always returned false, as `-z` checks if the variable is `null`, however it was `false`.
- The script now looks for the name of the container instead of the image's name `openjdk_container`. 
- When building the container, the name is specified to be whatever version of openjdk the container will be building.
This was done to allow multiple instances of `buildDocker.sh` to run on the same computer, in the case of the Jenkins job `SXA-DockerfileCheck`. Before, the container was removed based off the image name `openjdk_container`. However, when running multiple docker builds, only the latest container would have that image's name, the other container's images …

docker-build.sh: Fixed removal of containers; Works when running in parallel

---

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
docker/jdk8/x86_64/ubuntu/Dockerfile-openj9

Required to build JDK with OpenJ9.

DockerfilesJ9: Install GCC7 and use to build JDK

---

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9

JDK 11+ need GCC 7.3 specifically to build correctly- Pulling from `ppa:ubuntu-toolchain-r/test` will give it 7.4.
If not, the following error message is given:
```
VMAccess.cpp: In function 'void acquireExclusiveVMAccess(J9VMThread*)':
VMAccess.cpp:154:132: error: self-comparison always evaluates to true [-Werror=tautological-compare]
J9_LINEAR_LINKED_LIST_ADD(exclusiveVMAccessQueueNext,exclusiveVMAccessQueuePrevious,vm->exclusiveVMAccessQueueHead,vmThread);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^                                  
VMAccess.cpp:154:287: error: self-comparison always evaluates to true [-Werror=tautological-compare]
J9_LINEAR_LINKED_LIST_ADD(exclusiveVMAccessQueueNext,exclusiveVMAccessQueuePrevious,vm->exclusiveVMAccessQueueHead,vmThread);
^ …
```

Dockerfiles-J9: Use GCC7.3, not 7.4

---

docker-build.sh
sbin/common/common.sh

This change will more appropriately name the volume sources for the docker containers, and the containers themselves. This change will make it so when running `./makejdk-any-platform.sh --docker` and `./buildDocker.sh` , there will be unique volumes for the J9 and Hotspot variants. Without this, Jenkins jobs that run 2 instances of `./buildDocker.sh` on the same OS but different build variants at the same time, result in one of the two containers outputting: 
```
Incorrect Source Code for <jdk_version>.  This is an error, please check what is in /openjdk/build and manually remove, exiting...
```
as it's detecting the other build variant's source code.

DockerBuild: Made sure variables are named appropriately

---

sbin/common/common.sh

This has been raised by a user in the slack channel and I think it's probably a good idea for security purposes to have a consistent user used on the files inside the tarballs we produce.
Am testing this out at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-xlinux-build and https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-aix-build to verify that it works before getting a full review/merge.

Set UID/GID to root/root (0/0) in the tarball contents when using gnu tar

---

git-hg/mercurialToGit.sh

JDK11 and JDK mirror scripts are failing.
Unbound variable `$releaseTagExcludeList` is the cause.
Fix for #1391
CC: @johnoliver

Give optional variable releaseTagExcludeList a default value.

---

git-hg/freebsdRepoSync.sh

* Reset to the upstream state before doing a pull instead of after.  If
there were conflicts during the previous merge then the pull will fail
otherwise.  Since we've done a reset prior to the pull, there is no need
to do so after, since local changes were wiped out by the initial reset.
Sponsored by:	The FreeBSD Foundation

Reset before pull

---

pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/build/openjdk_pipeline.groovy
pipelines/jobs/configurations/jdk10u.groovy
pipelines/jobs/configurations/jdk11u.groovy
pipelines/jobs/configurations/jdk12u.groovy
pipelines/jobs/configurations/jdk13u.groovy
pipelines/jobs/configurations/jdk8u.groovy

Shelley - asking you to check over this in case you want a different set of tests configured for the new builds
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1400 and the aarch64/J9 failing builds (support for JITted builds is only in  them for large heap variants just now)

Enable large heap OpenJ9 builds for s390xLinux and ppc64leLinux

---

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk12/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/build/openjdk_pipeline.groovy
pipelines/jobs/configurations/jdk10u.groovy
pipelines/jobs/configurations/jdk11u.groovy
pipelines/jobs/configurations/jdk12u.groovy
pipelines/jobs/configurations/jdk13u.groovy
pipelines/jobs/configurations/jdk8u.groovy

Without this fix the build detects and uses `/usr/bin/ccache` (3.2.4) instead of `/usr/local/gcc/bin/ccache` (3.4.2) and comes up with this error:
````
VMAccess.cpp: In function 'void acquireExclusiveVMAccess(J9VMThread*)':
VMAccess.cpp:154:132: error: self-comparison always evaluates to true [-Werror=tautological-compare]
J9_LINEAR_LINKED_LIST_ADD(exclusiveVMAccessQueueNext,exclusiveVMAccessQueuePrevious,vm->exclusiveVMAccessQueueHead,vmThread);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^                                  
VMAccess.cpp:154:287: error: self-comparison always evaluates to true [-Werror=tautological-compare]
J9_LINEAR_LINKED_LIST_ADD(exclusiveVMAccessQueueNext,exclusiveVMAccessQueuePrevious,vm->exclusiveVMAccessQueueHead,vmThread);
^                                  
cc1plus: all …
```

Don't use Ubuntu-supplied ccache in Docker when building OpenJ9 JDK11+

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk_pipeline.groovy

Introduced yesterday and locked the build pipelines as none of them could find a matching machine. Introduced by me cut & pasting from x64.

Adjust labels on new J9 XL builds to not target CentOS6

---

sbin/build.sh
sbin/prepareWorkspace.sh

Causing a build break now. Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1086 (assuming it works and hasn't got any other side effects ...)
Reviews welcome but please do not merge until I've had a chance to test it [EDIT: I'm comfortable that this is putting an identical `cacerts` in the same place as before, so this is good to go]

Stop pulling cacerts from jdk11u for jdk8u builds

---

build-farm/make-adopt-build-farm.sh

If the issue described in https://github.com/AdoptOpenJDK/openjdk-build/issues/1409 continues we can integrate this is a (hopefully) temporary workaround. At the moment this will change it (unnecessarily) for OpenJ9 builds as well as HotSpot, but it is the smallest change that will have the desired effect and be easy to roll back.
Leaving it to anyone with an interest to decide whether to merge this or not. I suspect if it's not resolved upstream in a few days we make the change to avoid us going too long without being able to test (FYI @smlambert as you've expressed concerns in this area.)

Temporarily use JDK11 to boot JDK11 builds

---

docker/buildDocker.sh

fixes: #1406 
Git wasn't pulling changes due to the if statement equalling `true`, then failing to git clone a repo that was already there. Change to absolute paths and it works :-)

buildDocker: Changed git function to use absolute paths

---

build-farm/make-adopt-build-farm.sh
build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

This prevented https://github.com/AdoptOpenJDK/openjdk-build/pull/1411 from activating as `JDK_BOOT_DIR` is being overridden before the section modified in that PR.
I believe this change will be ok, but it will fail if a suitable `JDK10_BOOT_DIR` is not defined as it will attempt to download one. This will at least expose any of our machines that are not configured with a suitable JDK10 boot JDK, so I'm willing to take  that hit ... I may look at stripping out that logic from the platform files universally later ...
Again this is part of mitigating https://github.com/AdoptOpenJDK/openjdk-build/issues/1409

Don't override JDK11 boot JDK in platform files

---

pipelines/build/openjdk8_pipeline.groovy

Currently special.openjdk target only exists in jdk8 and correspondingly only jdk8 Test_openjdk_special builds were created. https://ci.adoptopenjdk.net/view/Test_openjdk_special/ 
Will expand to other versions when needed.

Add special.openjdk to the set of jdk8's launched test targets

---

docker/buildDocker.sh

ref: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1575304389184900
Ensures the name of the docker containers reflect if the dockerfiles are from Eclipse. Should stop any conflicts of docker container names, as seen here:
https://ci.adoptopenjdk.net/job/DockerfileCheck/75/console

buildDocker: Specify Eclipse in container names

---

sign.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1235 (or at least makes mitigation more likely)
Hit three instances of this last night:
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-windows-x86-32-hotspot/109/console
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/517/console
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9-windowsXL/124/console

If signing of a file fails, back off for 10 seconds and retry

---

build-farm/make-adopt-build-farm.sh

This reverts commit 572d554169a10c1b02a5f1440acd1657cbcb7648.
May cause issues if some of our build machines don't have a JDK10 boot JDK on them as such issues will no longer be masked after https://github.com/AdoptOpenJDK/openjdk-build/pull/1416/files was merged ... I'd prefer to sit and watch this after integrating tomorrow but I'll leave it to any reviewer as to whether to just approve or approve & merge before the automated runs tonight ;-)
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1409

Revert "Temporarily use JDK11 to boot JDK11 builds (#1411)"

---

docker-build.sh
sbin/common/config_init.sh

This PR is a solution to issue #1293 
The JRE_PATH and JDK_PATH variables are configured according to the OS of the docker container, not the native host.

Configure path variables accordingly when choosing to build in Docker containers

---

docker/buildDocker.sh

This will stop the`the input device is not a TTY` error message found in https://ci.adoptopenjdk.net/job/DockerfileCheck/78/ in the `eclipsej9` section.
Further to #1423 , I've also made sure the docker containers specified have the correct name.

buildDocker: Use only option -i for docker exec commands

---

build-farm/make-adopt-build-farm.sh
sbin/build.sh

As per slack discussion and agreed at the TSC call this week, we will use a separate repository for external user support questions (many of which will likely be routed upstream to another project if they are underlying openjdk bugs.
This will stop us from clogging up the openjdk-build repository with these issues. I will start moving the existing such issues across to the new repository, and this issue will prevent people using future releases from raising them here.

Bug report url

---

docker/buildDocker.sh

@sxa555 noticed in https://ci.adoptopenjdk.net/job/DockerfileCheck/label=infra-vagrant-T541,variant=eclipsej9,version=jdk8u/85/ that some builds would complete in a few minutes.  
This was because the container was not being removed once the build had finished, so this PR will stop and destroy the containers once building.

buildDocker: Remove Eclipse container once running build

---

build-farm/make-adopt-build-farm.sh

This is usually later on in the log as per the example below but will aid early diagnosis within the scripts if required:
```
checking Boot JDK version... openjdk version "12.0.2" 2019-07-16 OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing) 
```

Show BOOT JDK version string in build log for debug purposes

---

build-farm/platform-specific-configurations/linux.sh

With https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1021 , I changed the OpenSSL102 role to include Debian8 - therefore the build script needs to be updated to change the build configuration when building on Debian 8.
I checked this wouldn't break CentOS6 too.

Ensure Debian is built with openssl-1.0.2

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy

Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1049
(To be fair it shouldn't be broken on the later AIX box, but I want to keep it on the older ones for now for compatibility...)

Ensure JDK8 and 11 are built on AIX xlc13-tagged machines

---

sbin/common/common.sh

This is frequently seen in the build log and has a tendancy to confuse people, when it's just checking if pigz is in place to see if it can be used in preference to gzip, which it will fall back to.
`which: no pigz in (/usr/local/gcc/bin:/usr/local/bin:/usr/bin)`
It's not an error, so suppress the output to avoid confusing people :-)

suppress 'which pigz' output as it looks like an error

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/openjdk_build_pipeline.groovy

Somewhat belated since it's the last day of 2019, but this fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1456
Ref https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html for the datestamp formats

Fix datestamps on last week of the year

---

build-farm/platform-specific-configurations/linux.sh

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1101
OpenSUSE requires OpenSSL 1.0.2 to be installed via the playbook, therefore this needs to be specified when building on it.

Add OpenSUSE to OSs that require OpenSSL102

---

sbin/prepareWorkspace.sh

Not entirely sure why but on OpenSUSE freetype appears to put intself in a `lib64` directory under the install location instead of `lib`. Perhaps this should be fixed at source, but for now this is a workaround that will symlink `lib` to `lib64` if it's put it in the "wrong" place.

build: Allow freetype to be detected on OpenSUSE

---

build-farm/make-adopt-build-farm.sh
sbin/build.sh
sbin/common/common.sh

- Bump latest JDK feature version to 15
See:
https://github.com/AdoptOpenJDK/openjdk-jdk/blob/dev/make/autoconf/version-numbers#L29
- Fix tag lookup scheme so as to detect the
appropriate major version originally specified.

Update support for building JDK head

---

build-farm/make-adopt-build-farm.sh
build-farm/platform-specific-configurations/mac.sh
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
sbin/build.sh
sbin/common/config_init.sh

uses the built in codesign args defined in https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/b3250adefed0c1778f38a7e221109ae12e7c421e

enable correct codesigning on jdk11

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

Currently there is logic where when there is no directory
present pointed to by JDKxx_BOOT_DIR a fallback is in
place to download the JDK N-1 boot JDK version via the
API. If this fails for some reason, no diagnostics are
available.
This patch tries to simplify the logic a bit and adds an
additional 'java -version' output for the - potentially -
changed boot JDK the build will be using.

Switch to API v3 and provide better diagnostics

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

With later JDK versions 'java -version' output
goes to the error stream (fd 2). Account for that
in diagnostics so that "BOOT JDK: " is properly
pre-fixed.

Fix java -version diagnostic output

---

pipelines/build/openjdk8_pipeline.groovy

Caused by b8ffae5cf892a7efb35714783def2fb65796079b.
ff2f113a1ee68a2fd4b3b5b70d0c7a73ea68da00 seems to have happened in
between and the revert was not clean?

Fix compilation of pipelines

---

pipelines/build/openjdk14_pipeline.groovy
pipelines/jobs/configurations/jdk14.groovy

Configurations for jdk14 openj9 build pipeline on most supported platforms. Disabled tests

Add pipeline for JDK14 with OpenJ9

---

sbin/build.sh

When invoking the build via './makejdk-any-platform.sh [...] jdk' the
BUILD_CONFIG[OPENJDK_CORE_VERSION] ends up being set to the same value
as JDK_PREFIX, namely 'jdk'. This results in
${BUILD_CONFIG[OPENJDK_CORE_VERSION]#$JDK_PREFIX} evaluating to the empty
string. Thus, the if statement:
if [ "$JDK_VERSION_NUMBER" -gt 8 ] ...
ends up being evaluated as 'if [ "" -gt 8 ] ... resulting in:
bash: [...] integer expression expected
Use BUILD_CONFIG[OPENJDK_FEATURE_NUMBER] instead which should always
be a numeric value.

Fix bash syntax error for builds on jdk/jdk

---

pipelines/jobs/configurations/jdk13u.groovy

JDK13 now out of support, and the OpenJ9 repositories no longer can no longer build it.

Disable JDK13 nightly builds

---

pipelines/jobs/configurations/jdk10u.groovy

This would be a step towards auto-detecting new pipelines and
generating them.
JDK 10u is deprecated anyway.

Disable JDK 10u pipeline job

---

pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy

We have a bit more AIX capacity and while the machines aren't fully verified as working, we should now be able to run at least the sanity testing nightly

Add sanity.openjdk testing to AIX JDK8/11 pipelines

---

build-farm/platform-specific-configurations/mac.sh

On MacOSX, jdk versions 11 and higher support code-signing and the OpenJ9 variant also supports jdk 8.

Expand use of '--with-macosx-codesign-identity'

---

build-farm/platform-specific-configurations/aix.sh
sbin/build.sh

Apparently we haven't been building JDK8 OpenJ9 builds with the OpenSSL support enabled. This PR resolves that.
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-aix8j9ssl/2/console

aix: enable openssl support on JDK8/J9

---

pipelines/build/common/create_job_from_template.groovy
pipelines/jobs/pipeline_job_template.groovy

concurrentBuild is deprecated since DSL 1.76. Replace with new disableConcurrentBuilds() property. 

concurrentBuild is deprecated

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

This would be a (temporary) fix to actually get the JDK HEAD
pipelines building. Currently they fail with:
```
Downloading GA release of boot JDK version 14...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
That is, 'set -e', prevents for the fallback download
using the EA version of JDK 14 to actually happen.

Work-around 'set -e' for the JDK N-1 fallback download

---

pipelines/build/common/openjdk_build_pipeline.groovy

Needed because configuration of groovy scripts don't allow `matches.find()`
Just copied the method from build_base_file.groovy and accounted for `buildConfig.JAVA_TO_BUILD`
FYI @jerboaa

Updated JavaVersionNumber method to use matches()

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy

@sxa555 this will now move all jdk14 and 15 builds to our Mojave build machine too. I suggest that we consider deprecating the macos10.12 machine and spin up an additional 10.14 machine.
We should be able to take the 10.12 machine offline as soon as we stop building jdk13 (if we haven't already)

move jdk14 and 15 to macos machine that can support notarization

---

pipelines/build/prTester/pr_test_pipeline.groovy

JDK13 pipeline still runs this might be why

Remove jdk13 reference

---

build-farm/platform-specific-configurations/aix.sh

* --disable-warnings-as-errors is not valid for JDK8

Remove disableWarningsAsErrors

---

build-farm/platform-specific-configurations/linux.sh

Fixes #1508 once updates have been deployed onto the machines. New provisional tarballs are in https://ci.adoptopenjdk.net/userContent/gcc/

env: tolerate gcc 7.5 in /usr/local/gcc bin

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh

Was preventing these statements from returning 1 if the command failed, therefore not fetching correct bootjdk on jdk next

Removed erroneous tags

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh

Breaks the builds when a boot JDK is downloaded as it doesn't include the `-` parameter to `tar` 
This reverts commit 0cba20148cb3e02f2a830f2f912be1b4febaf386.

Revert "Removed erroneous tags (#1530)"

---

pipelines/build/common/openjdk_build_pipeline.groovy

Disable hotspot-jfr build trigger sanity.external test job. Those test jobs are already triggered by hotspot build.
Close #1468 

Disable hotspot-jfr build trigger sanity.external test job

---

docker/jdk14/x86_64/ubuntu/Dockerfile
docker/jdk14/x86_64/ubuntu/Dockerfile-openj9
docker/jdk14/x86_64/ubuntu/dockerConfiguration.sh

Based entirely off the JDK13 ones, having ran `sed 's/jdk13/jdk14/g'` on a copy of them. 
I'll replace JDK13 with JDK14 in the `DockerfileCheck` Job once merged :-)

docker: Add Dockerfiles for JDK14

---

build-farm/platform-specific-configurations/aix.sh

The current HotSpot JDK13 was built on a later version of AIX than the current build machines and is causing a crash when we try to use it as the boot JDK for JDK14:
```
Downloading GA release of boot JDK version 13...
BOOT JDK: #
BOOT JDK: # A fatal error has been detected by the Java Runtime Environment:
BOOT JDK: #
BOOT JDK: #  Internal Error (threadCritical_aix.cpp:45), pid=7405590, tid=258
BOOT JDK: #  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
BOOT JDK: #
BOOT JDK: # JRE version:  (13.0+33) (build )
BOOT JDK: # Java VM: OpenJDK 64-Bit Server VM (13+33, mixed mode, tiered, compressed oops, g1 gc, aix-ppc64)
BOOT JDK: # Core dump will be written. Default location: /ramdisk0/build/workspace/build-scripts/jobs/jdk14/jdk14-aix-ppc64-openj9/core or core.7405590
BOOT …
```

aix: Use OpenJ9 VM as boot JDK to avoid crashes

---

build-farm/platform-specific-configurations/mac.sh

On macos the error code from wget | tar does not get correctly detected
This will do it in a way that will correctly cause a failure code if
they wget does not work.
FYI @adam-thorpe

env: Fix detection of failed macos boot jdk download

---

build-farm/platform-specific-configurations/linux.sh

linux: Remove old GCC locations to force to 7.5 or system installed

---

pipelines/jobs/configurations/jdk11u.groovy

I believe the standard heap OpenJ9 builds should now work again
This reverts commit 1b2f804b733c9f97c417e81d04bb9b0106ff044f.

Revert "Temporarily disable aarch64 openj9 builds (#1452)"

---

sign.sh

Follow on from https://github.com/AdoptOpenJDK/openjdk-build/commit/8860634d93597f9a423c7d38b581ddb08d34bbfd

sign.sh: Allow retries on EXE signing as well as DLLs

---

docker/buildDocker.sh
docker/jdk15/x86_64/ubuntu/Dockerfile
docker/jdk15/x86_64/ubuntu/Dockerfile-openj9
docker/jdk15/x86_64/ubuntu/dockerConfiguration.sh

fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1150
Although the script won't currently work for JDK15, this future proofs it for when it does come out. For now, the changes to `buildDocker.sh` will at least allow the `DockerfileCheck` job to run/test JDK14. 
JDK15 Dockerfiles were made by cp'ing the JDK13 repo and `sed -i -e 's/jdk13/jdk15/g' * && sed -i -e 's/JDK13/JDK15/g' *` in it.

Docker: Add JDK15 Dockerfiles & buildDocker.sh support them

---

build-farm/platform-specific-configurations/aix.sh

Reducing this value appears to make it a bit more reliable. Going forward we should probably use `--with-jobs` but in the absence of extra testing for now, this should suffice
I'm vaguely optimistic that this fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1151

Reduce AIX memory usage due to fork failures

---

docker/buildDocker.sh

Was causing the `DockerfileCheck` jenkins job to fail on JDK14, as it was attempting to find the jdk14u repository which isn't there (yet). Also thought I'd remove this for JDK15 so it doesn't trip up the job when it comes to running it.

docker: Change jdkVersion to jdk14, not jdk14u

---

pipelines/jobs/configurations/jdk15.groovy
pipelines/jobs/configurations/jdk8u.groovy

This to manage overnight test execution for JDK8 HotSpot vs openj9
Signed-off-by: Archana Nogriya <archana.nogriya@uk.ibm.com>

Reschedule pipelines to run JDK8 bit earlier and replacing with JDK15

---

sbin/build.sh

Previous syntax was causing build failures. Since `auto` was the default in earlier versions, and I've verified that using this option in JDK15 still causes auto-detection (so it won't fail where dtrace, or an equivalent, does not exist) this should be safe. Error message that this shoudl resolve is:
```
configure: error: Invalid value for --enable-jvm-feature-dtrace: 'auto'
configure exiting with result code 1
```

Fix enable dtrace option to be compatible with JDK15 and later

---

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk14/x86_64/ubuntu/Dockerfile-openj9

For the `-dtrace` option.
Stops this error:
```
checking if dtrace should be built... no, missing dependencies
configure: error: Cannot enable dtrace with missing dependencies. See above. You might be able to fix this by running 'sudo apt-get install systemtap-sdt-dev'.
```

Add systemtap-sdt-dev to J9 Dockerfiles

---

pipelines/build/common/create_job_from_template.groovy
pipelines/jobs/pipeline_job_template.groovy

We've had some issues on AIX where the builds have become slower at times but by the time it's been noticed the older builds have "fallen off the end" of the 10 builds that we keep. Increasing this number to about a month worth of builds, and two months worth of pipelines should use a fairly small amount of space (since we're only keeping artifacts  for one or two of them) but should allow us to gain more ability to analyse when issues are occurring and have an improved ability to diagnose them.

Store more (artifact-free) build trend history

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/mac.sh

I want to clean up the ["Failing Builds" tab]() - for this I need to run another successful build for the JDK13 ones that are failing. At the moment this is not possibly because it tries to force the codesigning option in which is not supported on JDK13.
Ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-mac-x64-openj9/176/console
```
Using autoconf at /usr/local/bin/autoconf [autoconf (GNU Autoconf) 2.69]
configure: error: unrecognized options: --with-macosx-codesign-identity
configure exiting with result code 1
```

Codesign not jdk13

---

pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
sbin/build.sh

* Dtrace is set to auto on all active pipeline configurations save JDK15+ (which is required)
* Removes --enable-dtrace from the global build script
Closes: #1586

Set dtrace only on JDK15+ builds

---

sbin/prepareWorkspace.sh

fixes: #1580 
Ensures that the `public_key.gpg` is specific to each build.
Testing at : https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/392/

Move GPG key to be generated/stored in `WORKSPACE_DIR/WORKING_DIR`

---

README.md

Modifying the instructions is a appropriate action, so that users will use only relative paths, as there are multiple places where the script needs to be updated.
Signed-off-by: Surya Narkedimilli <narkedi@gmail.com>

Fixing Issue: 1417 -s and -d parameters assumed relative

---

build-farm/platform-specific-configurations/windows.sh

ref: #https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1193 #1556 
fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1159
This change allows machines to use the built-with-VS2017 OpenSSL 64bit, if it's on the machine, with JDK11+ OpenJ9 builds

Enable use of OpenSSL-1.1.1d-64 VS2017 for Windows JDK11+ OpenJ9

---

build-farm/platform-specific-configurations/windows.sh

This is needed to convert x86-32 to x32 which is what the API uses

add support for windows x86-32 boot jdk download

---

build-farm/platform-specific-configurations/windows.sh

Ref: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1209 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1205
Update to the build scripts to allow them to pick up the new version of OpenSSL.

build: Enable OpenSSL1.1.1e on Windows

---

sbin/build.sh

Keep any such files in debug-image and test-image.
Fixes #1636.

Only remove debuginfo files from jdk

---

build-farm/platform-specific-configurations/windows.sh

Correct the path it's detecting from, as it currently doesn't line up with what the playbook says ( https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1209/ ) or what I've put on the machines as part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1205

Windows: Correct OpenSSL path

---

pipelines/jobs/configurations/jdk11_pipeline_config.groovy
pipelines/jobs/configurations/jdk14_pipeline_config.groovy
pipelines/jobs/configurations/jdk15_pipeline_config.groovy
pipelines/jobs/configurations/jdk8_pipeline_config.groovy

Note to reviewers: DO NOT MERGE THIS YET (I'll do so over the weekend)
As per standard process, this will keep the nightlies running but will not run testing against them, thus preventing executor tie-up for release builds.

Inhibit nightly testing during April 2020 release cycle

---

build-farm/platform-specific-configurations/windows.sh

Tested and seems to resolve the issue where JAVA_HOME becomes set to a java 7 which prevents gradle from running properly in the siutation where neither JDK8_BOOT_DIR or JDK11_BOOT_DIR are defined which can happen when building java 8. As per https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1263#issuecomment-615090885 in

windows: Don't set JAVA_HOME to JDK_BOOT_DIR

---

pipelines/build/common/openjdk_build_pipeline.groovy
sign.sh

This broke all windows releases from the last cycle (https://github.com/AdoptOpenJDK/openjdk-build/issues/1694)
None of the exe/dll files were signed because the path was incorrect on the azure machines. Added Propagate: true to prevent this happening again

fix signtool.exe path on windows

---

sbin/build.sh

https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1263

Allow building the --with-add-source-root to work with full paths

---

sbin/prepareWorkspace.sh

Should fix: #1680 
ref: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/83/console
The addition of a space means that the when checking a src repo's remote to make sure the source is correct, there's no chance of mistaking the source of `openjdk-jdkXXu` for `openjdk-jdk`
i.e.
`grep "${BUILD_CONFIG[REPOSITORY]}" ` returns 0 when the remote is `openjdk-jdk11`, despite `$BUILD_CONFIG[REPOSITORY]` being `openjdk-jdk`

prepareWorkspace: Add space after BUILD_CONFIG[REPOSITORY] variable

---

docker/jdk/x86_64/ubuntu/Dockerfile
docker/jdk/x86_64/ubuntu/Dockerfile-openj9
docker/jdk10/x86_64/ubuntu/Dockerfile
docker/jdk11/x86_64/ubuntu/Dockerfile
docker/jdk11/x86_64/ubuntu/Dockerfile-openj9
docker/jdk12/x86_64/ubuntu/Dockerfile
docker/jdk12/x86_64/ubuntu/Dockerfile-openj9
docker/jdk13/x86_64/ubuntu/Dockerfile
docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
docker/jdk14/x86_64/ubuntu/Dockerfile
docker/jdk14/x86_64/ubuntu/Dockerfile-openj9
docker/jdk8/x86_64/ubuntu/Dockerfile
docker/jdk9/x86_64/ubuntu/Dockerfile

ping @sxa 
Update to the more stable APIv3 as to stop 404 errors.
(ref: https://ci.adoptopenjdk.net/job/DockerfileCheck/label=docker-aws-ubuntu1604-x64-1,variant=hotspot,version=jdk14u/116/ )

Docker: Update Dockerfiles to use APIv3

---

sbin/build.sh

Looking closely at the build logs on AIX, you'll notice two instances of this as it's trying to remove `.debuginfo` and `.diz` files:
```
find: 0652-017 -delete is not a valid option.
```
This removes use of the `-delete` option in favour of using `xargs`.

Fix deletion of .debuginfo and .diz files

---

pipelines/build/common/openjdk_build_pipeline.groovy

fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1284
ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/554/console
A build issue introduced with #1647 and #1639 . The softlayer Windows build machines (unlike the azure ones), don't have a `CYGWIN_WORKSPACE` variable setup for them. This causes them to default to `C:/cygwin64/tmp/openjdk-build/` currently, however that causes an issue when the build is trying to find the path: 
```
c1xx: fatal error C1083: Cannot open source file: '../../../../..c:/cygwin64/tmp/openjdk-build/workspace/build/src/build/windows-x86_64-normal-clientANDserver-release/hotspot/variant-server/libjvm/gtest/objs/BUILD_GTEST_LIBJVM_pch.cpp': No such file or directory
```
FYI @karianna @gdams @sxa

pipelines: Correct workspace path for Windows build

---

pipelines/build/common/openjdk_build_pipeline.groovy

* https://github.com/AdoptOpenJDK/openjdk-build/pull/1723 is no longer needed. It was not the test job's that were at fault.

Revert: "Ensure testType isn't false"

---

build-farm/make-adopt-build-farm.sh

The display of the boot JDK version output in the log is incorrect - it's currnetly displaying whichever is first in the path. This will fix that, and also display the `java -version` output of whatever is in the path to assist any other debug operations.

Boot jdk display fix

---

sbin/build.sh

Refactor the code that adds configure options relating to debug information from
`buildingTheRestOfTheConfigParameters()` to `configureDebugParameters()` so it
can be applied to all platforms (including Windows).
Fixes: #1735

Apply debug configuration options consistently

---

pipelines/jobs/configurations/jdk11_pipeline_config.groovy

OpenJ9 are looking to migrate to using cmake for their builds. We've had cmake in the playbooks for a while, and the initial platform they want to switch over us JDK11 on macos. this PR makes that change and should verify that our build machines are capable of doing this.
Their official cutover will be on the 19th but I want to put this through now to get a good amount of confidence that it will work on the adoptopenjdk systems.
Cc @dnakamura

openj9: Enable building with cmake on macos/JDK11/J9

---

build-farm/platform-specific-configurations/aix.sh

Not pretty (and if anyone wants to implement another solution then go for it) but this will exclude the Jenkins Agent's PATH from ending up in the java executables, since that has the potential to be confusing.

Strip java directories from the AIX LIBPATH

---

build-farm/platform-specific-configurations/linux.sh

Supercedes https://github.com/AdoptOpenJDK/openjdk-build/pull/1758 based on a slack discussion with the RISC-V team as Will is out and I cannot edit his PR.

Force RISCV build JDK to be JDK11

---

sbin/build.sh

Error from [latest bulid](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv-openj9/2/console)
`
Error executing 'java' does not exist in '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-riscv-openj9/workspace/build/src/build/linux-riscv64-normal-server-release/images/jdk'.
`
I'd prefer a bit more generic support for cross-compiled builds but this is the only one we have at present so I'm happy with this "quick fix" on one platform for now.
@johnoliver Can you comment on the line in here please:
```
```
When does jenkins look for these, and what are the implications if that portion is skipped on these builds?

Do not attempt to run java -version on riscv cross-compile

---

pipelines/build/common/openjdk_build_pipeline.groovy

* Only JDK and JRE files are needed for the installer, ignore all others

Improve installer filter parsing

---

sbin/common/common.sh

* Prevents cygwin from misunderstanding the path and setting JDK_BOOT_DIR to /cygdrive
Closes: #1093 

Quotate JDK_BOOT_DIR setup

---

sbin/build.sh

This isn't the best idea, but if it works to get green pipelines I'll take it for now until someone implementes a better solution. I'm not sure what the implications are of faking the metadata like this, but we're a little short of options. I suspect the best option would be to modify the code that reads it and handle an empty case.
[EDIT: The more i think about this the more I dislike it event as a temporary solution]
[@M-Davies @Willsparker If you can figure out how it's used and implement a better alternative that might be useful]

Fake version.txt on cross compiles on RISC-V

---

build-farm/platform-specific-configurations/linux.sh

Use an Openj9 nightly as the "build" (not boot) JDK for the RISC-V cross compilation process.

Use OpenJ9 x64 nightly as RISC-V build jdk

---

build-farm/platform-specific-configurations/linux.sh

ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv-openj9/12/console
Nightly failed as it was unable to find the `buildjdk` folder - addition of the `f` flag to `rm` will stop it failing if it isn't there.
ping @sxa

add 'f' tag to riscv specific config

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/openjdk_build_pipeline.groovy

https://github.com/AdoptOpenJDK/openjdk-build/issues/1514
Closes #1514 
Signed-off-by: Shishir Halaharvi <shishir.neo95@gmail.com>

Update hardcoded JDK next values

---

pipelines/build/common/openjdk_build_pipeline.groovy

* Asynchronous cleanup does not remove workspace directories
* This is a workaround until [1] is resolved
* [1] https://issues.jenkins-ci.org/browse/JENKINS-53579
Closes: #453 

Clean up properly on windows

---

build-farm/platform-specific-configurations/linux.sh
pipelines/jobs/configurations/jdk11_pipeline_config.groovy

This should really have been riscv64 from the start as that's what `uname -m` is on the boxes, and it's a 64-bit build. Hopefully these are the only places it needs to be changed :-)

Rename riscv in pipelines to riscv64

---

sbin/build.sh

This is resulting in duplicate messages in the log as the pigz setting and information message is duplicated from https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/common/common.sh#L100
```
12:34:48  Archiving the build OpenJDK image and compressing with gzip
12:34:48  OpenJDK JDK path will be jdk-11.0.8+5. JRE path will be jdk-11.0.8+5-jre
12:34:49  Archiving the build OpenJDK image and compressing with gzip
12:35:40  Your final archive was created at /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-hotspot/workspace/build/src/build/linux-aarch64-normal-server-release/images/OpenJDK.tar.gz
```

Remove duplicate pigz + debug code from build.sh

---

build-farm/platform-specific-configurations/linux.sh
pipelines/jobs/configurations/jdk11_pipeline_config.groovy
sbin/build.sh

Pushing this through as it's a build break. Missed it from the last PR

Remove java -version from riscv64 instead of riscv

---

shellcheck.sh

```
You are downloading ShellCheck from an outdated URL!
Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
```

Update shellcheck script to avoid error

---

sbin/prepareWorkspace.sh

Fixes: #1809 
This should stop the error mentioned in the issue above, as well as keep the fix implemented by #1708 .
Signed-off-by: William Parker <william.parker1@ibm.com>

prepworkspace: Stop error when checking valid git repo

---

pipelines/jobs/configurations/jdk15.groovy

Enable OpenJ9 builds of JDK-Next (15)

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

Closes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1826

Fail build if valid boot dir isn't found

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/openjdk_build_pipeline.groovy

Uses the info/available_releases/ endpoint to obtain the JDK-HEAD version number
Closes: #1820 

Query the adopt api to get the JDK-Head version

---

pipelines/build/common/openjdk_build_pipeline.groovy

* Windows XL binaries are not picked up using the outdated filter

Account for windowsXL installers

---

pipelines/gradle/wrapper/gradle-wrapper.properties

Discussion from : https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1591349831452800?thread_ts=1590055621.250700&cid=C09NW3L2J
This is due to the issue with the latest JDK11 not being able to run the current version of Gradle (`5.2.1`), on Windows. It was determined that the previous version of Gradle wasn't necessarily pinned for any particular reason, it was just the latest version at the time it was added to the build-scripts. 
I've tested on a local Windows VM with `jdk8u252-b09` and `jdk-11.0.7+10` and they both worked.
ping @karianna @sxa

Gradle: Update Gradle to the latest version (6.5)

---

sbin/prepareWorkspace.sh

This is to aid debugging. At the moment if `downloadFile` (in `prepareWorkspace.sh`) failures to download, it continues regardless. This can lead to error messages further down the line which are harder to diagnose.
This will ensure that the script aborts if the download operation with `curl` or `wget` fails.
Note that without `--fail`, curl does not abort on an HTTP/404.
Validating with a bad URL at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/618/ across platforms to ensure that `--fail` is valid, hence WIP

If an HTTP download fails in downloadFile, abort rather than fail later

---

sbin/prepareWorkspace.sh

Reverts AdoptOpenJDK/openjdk-build#1837
I missed this PR https://github.com/AdoptOpenJDK/openjdk-build/pull/1708. So this change is trying to revert my previous change by adding using `grep or` logic to check whether the REPOSITORY is right or not.

prepareWorkspace: fix `REPOSITORY` does not end with `.git`

---

sbin/build.sh

Overnight build failure demonstrated set -e shell exit not disabled around gradlew retry logic:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/366/console
This PR adds set +e around the gradle retry

Disable cmd line shell exit for gradle re-try logic

---

sbin/prepareWorkspace.sh

The prepareWorkspace.sh check for the git remote (fetch) url was not allowing for the fact that "jdk"(next) version repository string is a sub-string of jdk11u...
Added a "\s"(whitespace) match to REPOSITORY grep.
and a comment to explain!!
Verified fix here: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/andrew-jdk14u-linux-x64-openj9/14/console

Ensure jdk(next) prepareWorkspace validates cache correctly

---

sbin/prepareWorkspace.sh

This PR adds a retry logic to the prepareWorkspace checkout logic, to handle cases of failure due to corrupt/invalid caches.
It also adds more verbose failure output for better diagnosis.

Add retry logic for build prepareWorkspace checkout

---

pipelines/build/common/openjdk_build_pipeline.groovy

related to multiple failure #1834
This is the last filter which work without issue before splitting jre/jdk into two installer job.
This filter is less selective.
If error continue we can know for sure this is not related to this filter.
If this filter is not enough precise we can copy more artefact than needed .. but I don't think so

revert to last good copyArtifact filter

---

sbin/build.sh

One of the builds last night failed after three attempts. Putting this delay in will avoid any problems if it really is with the connection to the server and it's very temporary.

Gradle slow retry

---

pipelines/jobs/configurations/jdk15_pipeline_config.groovy

Part of https://github.com/AdoptOpenJDK/openjdk-build/issues/1819 - seems reasonable to switch the latest version over first... This will obviously affect minimum OS levels (although it will bring them in line with Linux on other architectures).
I have a GoDaddy RHEL7 box earmarked for build that's been used for some other jobs that can be used for this.

Switch JDK15 Linux/x64 builds to CentOS7/RHEL7

---

pipelines/build/common/create_job_from_template.groovy
pipelines/jobs/pipeline_job_template.groovy

* copyArtifactPermissionProperty might be deprecated in prod mode
Closes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1879

Trial copyArtifactPermission

---

build-farm/make-adopt-build-farm.sh
sbin/common/common.sh

This may only be required temporarily in order to debug the issue described in https://github.com/AdoptOpenJDK/openjdk-build/issues/1873 but we need to see the headers of the operation we're storing the result from and not the retry.
As far as I can tell `-v` does not impact the capturing of the stdout of the operation.

Verbose curl to retrieve latest API version

---

build-farm/make-adopt-build-farm.sh
sbin/common/common.sh

* Adds retry logic to the script based api calls (groovy ones will be updated in the jenkins helper) to try and pull info from the api 5 times before breaking and failing the build
Inspired by recent instability seen in #1873 

Add retry logic to script based api queries

---

pipelines/build/common/openjdk_build_pipeline.groovy

* Also disables DeferredWipeout on hotspot builds because why not
Closes: #1855 

Manually delete problimatic file on windows

---

build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

* Aix already uses OpenJ9 boot jdk's
Closes: #1890 

Use OpenJ9 boot jdk for JDK15+ J9 builds

---

docker-build.sh

Fixes: #1909 
I renamed `dockerfile_generator.sh` to `dockerfile-generator.sh` and forgot to update `docker-build.sh` afterwards.
Signed off by: William Parker william.parker1@ibm.com

docker: Refer to dockerfile-generator correctly in docker-build

---

README.md
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/library/src/ParseVersion.groovy
pipelines/library/src/common/VersionInfo.groovy
pipelines/src/test/groovy/VersionInfoTest.groovy
sbin/build.sh
sbin/build.template

* Adds the output of java --version and bash configure to VersionInfo
* Adds version tests to account for the changes
* Documentation updates
Closes: #11 
Closes: #367 

Add java version and configure to VersionInfo

---

pipelines/build/common/config_regeneration.groovy
pipelines/build/prTester/pr_test_pipeline.groovy

* Adds context to println's so they actually print out now
* Tries to get the config file twice now instead of failing once
* Cleans up if all the pipelines pass
* Enables tip (currently JDK16)
* Fixes a bug in the regenerator where the lastbuild endpoint doesn't
exist if the job hasn't been built before
Issue: #1770 (doesn't close it)
Closes: #1528 
Closes: #1793 

Add context to printlns and adapt new filenames

---

docker/buildDocker.sh

This PR is to allow for Eclipse's `mkDocker.sh` script ( https://github.com/eclipse/openj9/pull/9371 ) to be tested under the `DockerfileCheck` [Jenkins Job](https://ci.adoptopenjdk.net/job/DockerfileCheck/)
Currently there are some concerns that the `git gc --agressive --prune=all` command will fail when building the image due to the command taking up to 8GB of Memory (https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1592317252094400 ). However, this will depend on a change in the Eclipse/OpenJ9 repository. Once that's fixed, the `DockerfileCheck` job should work for the Eclipse Dockerfiles. 
The `cleanWorkspace` option has been put in so the `DockerfileCheck` job won't use old dockerfiles or create multiple copies of `mkDocker.sh` when running with the Eclipse option.

docker: Update buildDocker.sh to use new eclipse dockerfile script

---

pipelines/build/common/openjdk_build_pipeline.groovy

* To debug https://github.com/AdoptOpenJDK/openjdk-build/issues/1834 (and potentially https://github.com/AdoptOpenJDK/openjdk-build/issues/1878). 
* Far from ideal but we're running short of options.

Dump stack trace on build failure

---

docker/dockerfile-generator.sh

ref: https://ci.adoptopenjdk.net/job/DockerfileCheck/151/label=docker-aws-ubuntu1604-x64-1,variant=j9,version=jdk8u/
Unfortunately this was missed as part of #1912, as the issue doesn't occur on `macOS`, the machine this was tested on.
The variable has to have a value assigned to it before it is compared in an `if` statement on linux, otherwise the following error message occurs:
```
docker/dockerfile-generator.sh: line 91: cleanRepo: unbound variable
```
ping @sxa

docker: Ensure cleanRep var is bound in dockerfile-generator.sh

---

docker/dockerfile-generator.sh

ref: #1912 
https://ci.adoptopenjdk.net/job/DockerfileCheck/153/ - Missed out a couple backslashes

docker: Put in missing backslash to dockerfile-generator.sh

---

configureBuild.sh

* If both --jdk-boot-dir exists and JAVA_HOME doesn't
Closes: #1308 

Set JAVA_HOME to --jdk-boot-dir

---

pipelines/build.gradle
pipelines/build/common/openjdk_build_pipeline.groovy

This reverts https://github.com/AdoptOpenJDK/openjdk-build/pull/1934 and https://github.com/AdoptOpenJDK/openjdk-build/pull/1936 as they have broken the nighttly builds and I cannot risk things being broken over the weekend.

Undo gradlebreaks

---

sbin/common/config_init.sh
sbin/prepareWorkspace.sh

Introducing 2 additional config arguments to `sbin/prepareWorkspace.sh`, for other vendors to have the option to build openjdk with different openjdk-build source code.
`OPENJDK_BUILD_REPO_BRANCH`
and
`OPENJDK_BUILD_REPO_URI`

add config arguments for adopt build repo uri and branch

---

.gitignore
configureBuild.sh
pipelines/build/common/build_base_file.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk14u_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy
pipelines/src/main/groovy/testDoubles/ContextStub.groovy
pipelines/src/test/groovy/IndividualBuildConfigTest.groovy

Swaps all <15 hotspot builds to use the centos6 build image (https://hub.docker.com/r/adoptopenjdk/centos6_build_image)
Also adds codebuild machines to handle the docker images (saves us maintaining any docker only machines.
This PR technically allows us to use a docker build environment for any architecture that supports docker.
I'm currently not doing this on OpenJ9 because it requires CUDA which bloats the docker image substantially, I'm working on a solution for that.

switch linux x64 builds to use docker

---

build-farm/make-adopt-build-farm.sh
sbin/common/common.sh

Display return code from the final debug `curl -v` since it doesn't appear to be showing any output when it fails (Ref: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1593680142251300)
Also modifies the main curl commands to use `-q` to curl instead of `-v` as the `-v` can only cause confusion to the subsequent grep operation which will always remove all the verbose stuff anyway.

If API retries exceeeded, show RC of curl command

---

build-farm/platform-specific-configurations/aix.sh

We're hitting intermittent (but now quite frequent) resource limit issues consistent with those we first saw on the OpenJ9 builds. This implements the same fix to HotSpot
```
22:15:06  Creating java.net.http.jmod
22:15:06  Creating java.prefs.jmod
22:15:08  gmake[3]: CreateJmods.gmk:57: fork: Resource temporarily unavailable
22:15:08  gmake[3]: CreateJmods.gmk:221: fork: Resource temporarily unavailable
22:15:08  /opt/freeware/bin/bash: fork: retry: No child processes
22:15:08  gmake[3]: CreateJmods.gmk:221: fork: Resource temporarily unavailable
22:15:08  gmake[3]: CreateJmods.gmk:221: fork: Resource temporarily unavailable
22:15:08  Creating java.rmi.jmod
22:15:08  gmake[3]: fork: Resource temporarily unavailable
```

Reduce parallelism on AIX JDK14+ hotspot builds

---

README.md
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/src/main/groovy/testDoubles/ContextStub.groovy
sbin/prepareWorkspace.sh

Hooks up the scmRef in the metadata to whatever the tag has been specified as OR whatever the output of git describe is. On a failed git describe, the tag is used whether it is an empty string or not
Closes: #474 

Populate metadata scmRef

---

pipelines/build/common/openjdk_build_pipeline.groovy

ref: https://github.com/AdoptOpenJDK/openjdk-build/pull/1892/ , https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1419 , https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1396
Changes to allow the problematic `..the_` file to be deleted for both Softlayer and Azure windows machines before `cleanWS` is used. I was unsure if there was a specific variable that could've been used to make this more general ( i.e. ` context.sh(script: "rm -rf {buildconfig.WORKSPACE}/build/src/build/*/jdk/gensrc` , if anyone could enlighten me?
ping @M-Davies @sxa @karianna 
Signed-off-by: William Parker <william.parker1@ibm.com>

pipeline: Manually delete problematic file for Azure Windows

---

sbin/build.sh
sbin/common/config_init.sh

Proposing a small improvement to make GRADLE_USER_HOME configurable through `BUILD_CONFIG`.
In Azure Pipelines, we need to specify the location of `GRADLE_USER_HOME` in order to perform gradle caching between builds. This improvement grants us control for that location and prevents future issues when the location of GRADLE_USER_HOME gets modified.

set GRADLE_USER_HOME only when it's unset

---

build-farm/platform-specific-configurations/linux.sh

I am proposing pushing this into the July quarterly release this week since we cannot currently make https requests
Ref: https://github.com/AdoptOpenJDK/openjdk-support/issues/33#issuecomment-657340402

arm32: Build with gcc 7.5 on JDK8/arm32/HotSpot

---

git-hg/jdk8u/merge.sh
git-hg/jdk8u/updateRepo.sh

this ensures that the hg repo can be overridden for `aarch64`
switch https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-aarch64-jdk8u/ back to using master on merge

fix mirror script

---

pipelines/build/prTester/pr_test_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk14u_pipeline_config.groovy
pipelines/jobs/configurations/jdk15_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy

This PR switches the aarch64 builds to use the centos7 dockerimage: https://hub.docker.com/repository/docker/adoptopenjdk/centos7_build_image
The agents are dynamically provisioned using the Amazon EC2 Jenkins plugin
Also added aarch64 to PR testing because we can spin up the agents very quickly

build: switch aarch64 builds to be docker based

---

docker/dockerfile-generator.sh

Currently, the dockerfile that `dockerfile-generator.sh` generates for JDK11/J9 doesn't work, as the `gcc-7` its using (from https://ci.adoptopenjdk.net/userContent/gcc/ ), isn't able to pickup the libraries. This is only an issue on JDK11/J9 because that's the only run that uses `cmake`.
Using the `gcc-7` installed via `apt` allows `cmake` to pick up the `libdwarf` and `zlib` libraries, whilst still working for building the other JDKs. It also more accurately reflects what we do on the playbooks, as seen using `vagrantPlaybookCheck` ( https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Ubuntu1804,label=vagrant/722/console )

docker: Make OpenJ9 dockerfiles use ubuntu default gcc-7

---

pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk16_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy

* Stops the pipelines from holding up a master executor for the whole build

Remove master node from pipeline files

---

docker/buildDocker.sh

Ref: 
https://ci.adoptopenjdk.net/view/Tooling/job/DockerfileCheck/159/
https://ci.adoptopenjdk.net/view/Tooling/job/DockerfileCheck/162/
(The job for both of these runs had the config changed to run from this branch to test it)
A big refactor of `buildDocker.sh` changing the following:
- Rename variables, replace duplicated file paths with variables, add whitespace where it makes the code more readable
- Use the same logic in `dockerfile-generator.sh` ( using the API ) to set `JDK_MAX` and `JDK_GA`, so the script doesn't have to be changed in the future to add in later JDKs.
- The script runs within the openjdk-build directory it's executed, instead of re-cloning the openjdk-build repository again (requested by @sxa )
- Removed the `all` option as it seemed superfluous.

docker: Refactor of buildDocker.sh

---

sbin/build.sh

This should help the APi order these correctly. At the moment as the result of the `-internal` suffix the `pre` string in [VersionInfo.groovy](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/library/src/common/VersionInfo.groovy#L100) is causing them to be sorted in an inconsistent manner.
This also updates the date field in the output to be current, although I don't think that particular information is actively used fo the sort order.

Adjust faked version string on cross-compiled RISC-V builds

---

pipelines/build/common/openjdk_build_pipeline.groovy

String.includes(String) does not appear to exist, which I'm sure was
a typo, so I'm replacing it with count(String).
String.contains(String) is another option, but I didn't use that
because the API says it isn't mandatory for JDK 1.5+. There's also
String.indexOf, according to the error message, but I'm not seeing
that in the API doc, so let's play it safe.

Replace string includes with count

---

pipelines/jobs/configurations/jdk14u.groovy
pipelines/jobs/configurations/jdk15.groovy
pipelines/jobs/configurations/jdk15_pipeline_config.groovy

This is being done because we've passed the last release for jdk14,
and we need start testing 15 in preparation for the September release.
Most JDK15 builds are already active, but there are a few platforms
(windows 32bit and XL variants) that needed to be added, based on the
fact that jdk14 was creating builds for them.

Disable jdk14 build+test, and enable jdk15 build+test

---

pipelines/build/prTester/pr_test_pipeline.groovy

JDK14 is done and dusted, so we gain nothing from testing on it.

Remove jdk14 from pr test pipeline

---

build-farm/platform-specific-configurations/linux.sh
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk15_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Ref https://github.com/AdoptOpenJDK/openjdk-build/pull/802 - we are not building openssl on most platforms so I want to try re-enabling ccache on our JDK11+ buillds as (mentioned in the original PR) this was only supposed to be temporary.
Note that this will not be of too much benefit with the docker builds unless some additional creativity is employed (but shouldn't impact negatively other than populating a cache that isn't subsequently used!) but will still provide benefits for others.

Re-enable ccache as I don't think original reasons still hold

---

pipelines/jobs/configurations/jdk15_pipeline_config.groovy

Dtrace does not accept the "auto" option on jdk15, and configure
fails if it is set. Changing this so it matches the other usages
in the same groovy file.

Correct dtrace argument for jdk15

---

pipelines/jobs/configurations/jdk8u.groovy

@knn-k has confirmed to me that the JDK8 repositories for OpenJ9 now have all the changes in to build on the Linux/aarch64 platform so we should start building it along with JDK11 and JDK15 :-D
(For reference, parallel PR for the standalone OpenJ9 CI is at https://github.com/eclipse/openj9/pull/10291)

enable OpenJ9 builds of JDK8 on Linux/aarch64

---

sbin/build.sh

This is not necessarily a hard failure as first thought since gradle will still run without gradleJavaHome set
Fixes: #1989 

Re-jig Gradle not found as warning

---

build-farm/make-adopt-build-farm.sh

Moving the reading of the platform specific environment variable as it can adjust the `JDK_BOOT_DIR` and the `make-adopt-build-farm.sh` processes it. https://github.com/AdoptOpenJDK/openjdk-build/pull/2004 introduced an additional check which showed up this problem where if the logic has to kick in to auto-download a boot JDK within the platform script the build would abort.

Move location of platform sourcing so JDK_BOOT_DIR processed correctly

---

pipelines/build/regeneration/README.md
pipelines/build/regeneration/build_pipeline_generator.groovy

* Moves the current build-pipeline-generator script into github
* Adds a retired versions array to skip non existent versions
* Also modifies it to account for a new parameter, disablePipelineSchedule
* By default, we generate top level pipeline jobs with triggerSchedule pulled from config files. If param false, default logic is overridden pipeline jobs are generated without a trigger
Closes: #2016 
Fixes: #2017 

Top generator moved, disablePipelineSchedule param added

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

test build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv64-openj9/92/

switch riscv builds to use dockerfile

---

pipelines/jobs/pipeline_job_template.groovy

Currently the PR tester triggers lots of installer jobs which all back up and can add up to an hour to the pipeline.
fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/2030

skip installer stage for PR testing

---

README.md
configureBuild.sh
sbin/build.sh
sbin/common/config_init.sh
sbin/prepareWorkspace.sh

**By default, this PR changes nothing. It just adds the ability to pause a build before the jmods are created and then continue.**
This PR allows us to create an exploded image `--make-exploded-image` (an image before the jmods have been compressed)
This allows us to then codesign the jmods before the get packaged up and then continue the build job using the `--assemble-exploded-image` flag.

add exploded image build to scripts

---

sbin/common/config_init.sh

Works locally:
```bash
➜  openjdk-build git:(master) ✗ ./makejdk-any-platform.sh --help
Starting ./makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
Parsing opt: --help
➜  openjdk-build git:(manpage) ✗ 
```
Fixes: #2060 

Prevent --help from running build

---

build-farm/platform-specific-configurations/mac.sh
sign.sh

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1382
When unlocking a keychain, according to the `security unlock-keychain` syntax, if a keychain isn't specified, it will attempt to unlock the system keychain, which the Jenkins user isn't able to do. This can lead to the infra issue referenced above.

mac: Specify which keychain to unlock when signing mac builds

---

pipelines/jobs/configurations/jdk15u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Starting with 15, building the client VM together with the server VM on Windows causes the exclusion of modules/functionality related to Graal, namely:
```
jdk.internal.vm.compiler@15
jdk.internal.vm.compiler.management@15
```
Windows is the last x64 platform that we build the client VM on together with the server VM. Of the other vendors I checked (OpenJDK, Oracle, Azul, Bellsoft), only Bellsoft Liberica still has a client VM bundled with their Windows x64 build of OpenJDK **14**. The state of 15 for Bellsoft is unknown to me. From a technical standpoint, the server VM is superior nowadays (higher memory limits, ...) and the slower start-up compared to the client VM shouldn't really be an issue anymore.
I therefore propose dropping the client/server combination VM on Windows x64 starting …

Stop building client VM on Windows for 15, 16

---

sbin/build.sh

This only impacts RISC-V and won't touch JDK15 or any production platform so I'd quite like to get this tested ASAP since I'm getting asked about it. Happy to force it back immedaitely if it causes any issues.

Fix RISC-V version string so it gets sorted correctly in API

---

sbin/build.sh

Adds a check to prevent Github Actions from failing due to a git error inside the release file. the error occurs when it attempts to `git rev-parse` in a directory with no tree as GHA doesn't seem to create one for the build repository.
Also adds comments to provide status reports in the console during release file generation.
Signed-off-by: Austin Bailey <Austin.Bailey@ibm.com>

Add checks to prevent Github Actions error

---

pipelines/build/common/openjdk_build_pipeline.groovy

Ref (& possible fix): https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1556
The windows installer jobs and the sign build jobs have intermittent issues of finding the `windows.p12` file that is stored in `C:/Users/Jenkins`, despite the file being there. The current theory is that this is due to there being other directories on the build machines in the `C:\Users` folder following the format `jenkins.<something_random>`, that may be confusing these sign/installer jobs. 
I've made copies of the `windows.p12` files and put them in `C:\openjdk` directory on all 4 of the Windows build machines. I've kept them in their original place as well, in case this PR doesn't fix the issue and needs to be reverted.

Change location of windows.p12 file for signing/installer jobs

---

pipelines/jobs/configurations/jdk16.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Add x32 Windows to jdk16

---

README.md
sbin/build.sh
sbin/common/config_init.sh

Currently, we either have the option to make the images alone or with the debug symbols included in the same tar.gz/zip file.
This change is to have the option of including the debug symbols in a separate package, outside the JDK archive. If this option is called, we basically take the debug symbols of each platform, copy them to a new folder and then delete them from the images folder, and that folder just created is zipped as an artifact.
Issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2042

Add option to create debug-symbols in a separate file

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/jobs/configurations/jdk10u_pipeline_config.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk12u_pipeline_config.groovy
pipelines/jobs/configurations/jdk13u_pipeline_config.groovy
pipelines/jobs/configurations/jdk14u_pipeline_config.groovy
pipelines/jobs/configurations/jdk15u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
pipelines/jobs/configurations/jdk9u_pipeline_config.groovy

Set standard set of top-level test targets run nightly, weekly. Per release combined nightly and weekly targets will run
1. Keep all pipeline jobs runs the same targets as before.
2. Keep job configuration testList as simple as a placeholder
3. Possible key value for testlist
> no test enabled: test: false, or no test as key of configuration.
> standard set -->  test: "default"
> others --> 
```
test                : [
nightly: [customized target lists, could be empty too],
weekly : [customized target lists, could be empty too]
],
```
Close #1116 

Trigger tests with standard set

---

pipelines/build/common/config_regeneration.groovy

* Advanced sleep doesn't work correctly on groovy scripts
Follow up to #2070 

Use basic sleep on groovy scripts

---

sbin/build.sh

Solaris sort does not support "-s" option, so this PR changes the stable sort to simply use line numbering to achieve the same...
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

Solaris "sort" does not support stable sort option for sorting JDK tag sequence

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

- enable sanity and extended.functional testing to Aarch64 nightly builds
- Issue:AdoptOpenJDK/openjdk-build#2085
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

enable sanity and extended.functional testing to Aarch64 nightly builds

---

build-farm/platform-specific-configurations/windows.sh

Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1578
`vagrantPlaybookCheck` run to check these changes & https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1597 : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/886/
Updating the `windows.sh` platform specific configuration to use the latest version of OpenSSL. (Changes made by running `sed -i -e 's/1.1.1g/1.1.1h/g' windows.sh`)
Note: `OpenSSL1.1.1h 64-bit built with VS2019` has been put on all of the windows build machines too, however, it appears to not be used yet.

windows: Use OpenSSL 1.1.1h for builds

---

sbin/prepareWorkspace.sh

This will fetch the current latest version (1.1.1h)
for MacOS as well as all linuxs and AIX
Fixes #2123

Update OpenSSL to version 1.1.1h for all non-Windows platforms

---

sbin/prepareWorkspace.sh

The logic to reclone the openjdk src checks for the absence of .git, but does not clean any old src directory before doing so.

Ensure any old openjdk src repository is removed before re-clone

---

README.md

Adds some basic documentation for the Metadata .json file generated with every build.
Includes documentation for https://github.com/AdoptOpenJDK/openjdk-build/pull/2077 preemptively.
Signed-off-by: Austin Bailey <Austin.Bailey@ibm.com>

Add documentation for the Json Metadata file

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
sbin/build.sh

As Shenandoah is ready for production in 16, I'm assuming the flag is not required there.

Fixes #2114 - Add Shenandoah for Java 11 builds.

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk16_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/jobs/pipeline_job_template.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy
pipelines/src/test/groovy/IndividualBuildConfigTest.groovy

Currently, if there are no active nodes that match a build job's
labels, we fail immediately.
This change is intended to add a modifiable timeout value, so if we
don't find an active node that matches the build job's labels, we
wait for x minutes, periodically checking to see if a node matching
the labels has come online.

WIP: Active Node Timeout for Build Pipelines

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk16_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/jobs/pipeline_job_template.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy
pipelines/src/test/groovy/IndividualBuildConfigTest.groovy

This allows us to set the active node timeout once in the build
job, and for it to pass through to any test jobs launched by it.
Blocked on:
- PR 2130 in this repo - done
- PR 2012 in the openjdk-tests repo - done
Lacking any of those will prevent this change from working.

Pass active node timeout variable to tests

---

sbin/common/common.sh

I did experiment with adding some code to download a jdk if an invalid one is detected but it proved a little too convoluted, proving easier just to ask the user to download one themselves
Closes: #2054 

Terminate build on invalid boot jdk

---

pipelines/build/common/openjdk_build_pipeline.groovy

Docker nodes do not exist prior to us trying to use them, as they
are dynamically generated.
So waiting for one to become active prior to use is a futile effort,
and the inevitable timeout causes build failure.
So this change removes the "wait for active node" step from the
docker builds.

Remove Node Existence Check Prior to Docker Build

---

pipelines/jobs/configurations/jdk15u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Restores glibc 2.12 support and aligns us with upstream (https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms).
Fixes #2097.

Build JDK 15, 16 (x64) on CentOS 6

---

sbin/build.sh

The vendor-version-string has historically defaulted to AdoptOpenJDK.

vendor-version-string should default to AdoptOpenJDK

---

pipelines/build/common/build_base_file.groovy

Many jobs in queue during release, we will have to assess what is possible during the surge of capacity requirements during a release.

Temporarily remove weekly test list

---

pipelines/build/common/openjdk_build_pipeline.groovy

There a chance something downstream is preventing test runs on
Docker platforms because the NodeHelper isn't initiated prior to
the build (which was the case prior to an earlier commit).

Initiate NodeHelper before running build

---

sbin/build.sh

Shenandoah was not being correctly enabled in https://github.com/AdoptOpenJDK/openjdk-build/pull/2125 due the the use of a numeric `-eq` comparison on a string field that was `jdk11`.
Error in the log:
`/home/adoptopenjdk/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-hotspot/sbin/build.sh: line 81: [: jdk11: integer expression expected`
This fixes it so that Shendandoah will be correctly enabled on the builds where it should have been.
Fixes #2176 

Fix shenandoah conditional so it is correctly enabled

---

pipelines/build/common/openjdk_build_pipeline.groovy

* The JSON files of all builds except the latest are deleted from Jenkins, making it hard to debug historical metadata issues.
* This PR will spit out the metadata to the console each time there is a writeout to it, allowing you to see what the metadata was and is, even if the JSON files have been deleted
Spun off from effort to debug #2172 (doesn't fix or close it)

Output metadata to log

---

pipelines/build/common/create_job_from_template.groovy

I assume this was missed when the new scripts were
merged to master.
Related #525

Update branch name to master in job template

---

build-farm/platform-specific-configurations/solaris.sh

the ansible setup machines seem to have freetype installed in the correct location

solaris: only specify freetype location on sparcv9

---

sbin/prepareWorkspace.sh

Currently on Solaris the git repo gets wiped and re-cloned each time because the built-In grep isn't capable of handling the or statement: `"${BUILD_CONFIG[REPOSITORY]}.git\|${BUILD_CONFIG[REPOSITORY]}\`
This PR forces Solaris to use gnu grep

fix grep logic on solaris

---

sbin/build.sh

Commit https://github.com/AdoptOpenJDK/openjdk-build/commit/433c6f2324d2b6f52a8fcf4611ab642c89ee77e3#diff-bf1a71b6b982bb100bd797f1aac5049b232b43398baf9494c8f2823c62c8aa82
accidentally changed the Corretto version.txt location.
Corretto has it's own src version.txt which contains the jdk version level, this is different to the build generated metadata/version.txt.

Correct Corretto version.txt location

---

sbin/prepareWorkspace.sh

Had an issue today where we had this. the `downloadFile:` message says `url` which is no use, and we should make the error message afterwards be explicit to assist debugging. This PR improves the messages to expedite people trying to resolve bulid issues.
```
00:39:41  downloadFile: Saving url to alsa-lib.tar.bz2
00:39:41    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
00:39:41                                   Dload  Upload   Total   Spent    Left  Speed
00:40:10  
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:03 …
```

Improve error message on prereq download failures

---

sbin/build.sh

Currently, any platform-specific config args are added after the
user's config args, so the user's args get overridden by them.
This is suboptimal, as the user should be in control, regardless of
whether the scripts think a config arg is a good idea.

Restructure config args to give user args override priority

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy

Since all machines are configured the same way, this PR removes the need for the `buildj9` tag on the machines (The rather convoluted `(buildj9||build)&&openj9` we had on some of the builds was pointless.
All Windows and zLinux machines have all relevant tags. The only place we have differences in in AIX (due to the base OS level we build on) and therefore I believe this code is now superfluous.
As a side observation, it's a shame we have to have what looks like an identical code block duplicated in the generation code.

Remove use of buildj9 label on Windows and zLinux

---

pipelines/build/common/openjdk_build_pipeline.groovy

- If release_tag is provided, set OPENJ9_BRANCH to release_tag
(buildConfig.SCM_REF). Otherwise, set OPENJ9_BRANCH to master
- If release_tag is provided, set JDK_BRANCH to release_tag
(buildConfig.SCM_REF). Otherwise, set JDK_BRANCH according to
buildConfig.VARIANT
Resolves: #2131
Related: AdoptOpenJDK/openjdk-tests#2006
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

Set OPENJ9_BRANCH and JDK_BRANCH to release_tag in test pipeline

---

.github/workflows/build.yml

GitHub switched to 12 on Oct 20:
https://github.com/actions/virtual-environments/issues/1712
Should fix build problems that manifest as 
```
configure: error: Xcode 4, 9, 10 or 11 is required to build JDK 8, the version found was 12.0.1. Use --with-xcode-path to specify the location of Xcode or make Xcode active by using xcode-select. configure exiting with result code 1 Makefile:55: *** Cannot continue. Stop.
```

Select Xcode 11.7 for building the JDK

---

build-farm/platform-specific-configurations/linux.sh

This change will ensure arm-specific config options are appended to
CONFIGURE_ARGS_FOR_ANY_PLATFORM, instead of the arm options erasing
and replacing CONFIGURE_ARGS_FOR_ANY_PLATFORM's contents.

Ensure CONFIGURE_ARGS isn't replaced on ARM

---

build-farm/make-adopt-build-farm.sh

The user should always have the ability to specify options on the
commandline. It's useful for debugging, releasing, prototyping fixes,
etc.
However, giving the user a lower priority than the options provided
by the platform-specific scripts means that the user's options can
be overridden, and the user then has to go digging around in
various files to figure out why the scripts aren't doing why they're
told.
I think this is effort wasted, and the user's commands should always
have priority, even if it breaks things.
This command ensures that the user (or at least the surface params
that the user can trivially see and change in jenkins) always has
priority.

Give build pipeline user priority control over config options

---

pipelines/build/common/openjdk_build_pipeline.groovy

ref: #1956 , https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1662 , https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1396
Manually delete the `_the..` file that is unable to be cleared up. Like the referenced PR that proceeded this, it's a hacky way of fixing the issue, so I'll raise a separate issue to fix this properly.
(not sure of which label(s) to apply, sorry)
Signed-off-by: William Parker <wills.parker@outlook.com>

pipelines: Manually delete problematic file for IBMCloud Windows

---

build-farm/platform-specific-configurations/windows.sh

Requested via https://github.com/AdoptOpenJDK/openjdk-build/issues/466#issuecomment-717285975

Update JDK8/J9/Win to use VS2013 instead of VS2010

---

pipelines/build/common/openjdk_build_pipeline.groovy

Fix https://github.com/AdoptOpenJDK/openjdk-build/issues/2210
Only propagate OPENJ9_BRANCH to tests when building openj9.

Set OPENJ9_BRANCH only if buiding openj9

---

pipelines/jobs/configurations/jdk8u.groovy

Sparc builds are rather slow, but they do complete in an acceptable time for the overnight runs, so we should re-enable them
This reverts commit ec72cf53e326b6b77377c63719c9ba423a7310de.

Revert "Skip solaris sparcv9"

---

pipelines/build/common/openjdk_build_pipeline.groovy

Solaris sparc builds are currently over 6 hours (in part due to problems in the gradle phase causing a ~2 hour delay) so we cannot get releases out with the current setting.
Ref:
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/
- https://github.com/AdoptOpenJDK/openjdk-build/issues/2206

Increase build timeout as Solaris/SPARC builds are currently >6 hrs

---

pipelines/build/common/openjdk_build_pipeline.groovy
sbin/build.sh

Allow for null versionData.patch for installer creation and tag sorting

---

pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Passing "false" in as the value of these variables appears to cause
a Groovy error where it says "No signature of method:
java.lang.Boolean.clear() is applicable for argument types: ()
values: []"
Switching the values to empty arrays, as on the other platforms, to
fix this.

Convert false values to empty arrays to prevent boolean error

---

pipelines/jobs/configurations/jdk15u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2244.
If the underlying issue is not being addressed then this is the right solution to get the nightly builds stable again.

Stop using docker for JDK15/16 ppc64le builds

---

pipelines/jobs/configurations/jdk16.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

XL builds were included in the jdk15 pipeline, but were not
included in the jdk16 pipeline.
As per build issue 2174, the OpenJ9 team has confirmed that XL
builds should be included here.

Add XL builds to jdk16 pipeline

---

pipelines/jobs/configurations/jdk16_pipeline_config.groovy

An errant c+p removed commas between multiple elements in a list,
causing pipeline failure. This change restores those commas.

Add missing commas to jdk16 config file

---

sbin/build.sh

This reverts commit 1a60958cf7e51329ef3a0597e96d0130fe76d74f from https://github.com/AdoptOpenJDK/openjdk-build/pull/2252
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2255

Revert "Ensure createOpenJDKTarArchive is in the working directory

---

build-farm/platform-specific-configurations/windows.sh

Reinstantes https://github.com/AdoptOpenJDK/openjdk-build/pull/2191.
Interestingly we reverted this to do 8u272-b01 but it didn't break the OpenJ9 nightlies, which suggests it may not be as tightly coupled to the other PRs as was initially suggested via https://github.com/AdoptOpenJDK/openjdk-build/pull/2191#issuecomment-718780513
FYI @pshipton since we've been buiding with 2010 again for the last week or so

Revert "Temporarily change jdk8 openj9 back to using vs2010 (#2227)"

---

pipelines/build/common/openjdk_build_pipeline.groovy

* Now will only output metadata on first writeout to prevent duped spam
Follow up to https://github.com/AdoptOpenJDK/openjdk-build/pull/2175

Adjust Metadata debug output during build

---

build-farm/platform-specific-configurations/linux.sh

Freetype itself has various dependencies on external libraries,
some of which are not present on certain Linux distros.
Better to use the system's freetype library, so the user can handle
their own affairs, reducing the risk of issues (e.g. segmentation
faults on Fedora 28 while starting Eclipse).

Skip freetype build and bundling on Linux

---

sbin/build.sh

Some of the sbin/build.sh functions had specific dependency on being the the correct directory, but also didn't locate correctly to getJdkVersion().

Ensure build.sh getFirstTagFromOpenJDKGitRepo works in the workspace root git directory

---

pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/common/riscv_version_out.groovy
sbin/build.sh

* Instead of retrieving the faked version string, we run a downstream job on a riscv machine after the build that runs java version and passes it back to the pipeline in time for parseVersionOutput()
* Also clears up white spaces in openjdk_build_pipeline.groovy
Fixes: #1773 

Retrieve RISC-V Version String job

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/openjdk_build_pipeline.groovy

* Sometimes a FlowInterruptedException occurs that isn't from timeout
* Usually from the failure of a downstream job
* This PR adds notes to the error message in these unique cases
* That the user should check the downstream job results
* And not assume a timeout was reached

Add note to timeout error log

---

build-farm/platform-specific-configurations/solaris.sh

Hopefully fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2265 - or at least enables the build to get further

solaris: add /usr/sfw/bin to path so openssl is available

---

build-farm/platform-specific-configurations/linux.sh
pipelines/build/dockerFiles/gcc9.dockerfile
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

All installer related jobs are private so we need to skip these steps when built on other Jenkins. So I propose we use "enableInstallers" to skip the signing step as well.
A failure example in ci.dragonwell : http://ci.dragonwell-jdk.io/view/build_scripts/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/48/
Issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2231, #2149

Add buildConfig enableSigner to skip signing step

---

sbin/prepareWorkspace.sh

The change to using egrep in prepareWorkspace needed the | escape removing
https://github.com/AdoptOpenJDK/openjdk-build/commit/3732a85790c5975fb8857c78c8fc328b042da6ad

egrep regex search | does not need escaping

---

pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy

Nightly builds do not cleanWorkspace, thus the "workspace" folder can contain 1000s of files which on some machines can take many minutes, sometimes exceeding the Jenkins enforced 10minute timeout for git clean -fdx
This PR disables the git clean on the SCM checkout and explicitly performs the clean afterwards.

Perform openjdk-build git clean after scm checkout

---

sbin/prepareWorkspace.sh

This needs to go in today to prevent a build break. Solaris `sleep` doesn't support the `s` parameter. I suspect it's a pathway that is now being run as a result of https://github.com/AdoptOpenJDK/openjdk-buil/pull/2275 being merged.
Problem description from the build log:
```
14:10:57  Resetting the git openjdk source repository at /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src in 10 seconds...
14:10:57  sleep: bad character in argument
```

fix sleep command syntax in prepareWorkspace.sh

---

build-farm/platform-specific-configurations/windows.sh

If a folder has a space in its name, then we need to substitute it
with its shortname on Windows.
If there isn't one for that folder, then we throw an error here.
It's OK not to find CUDA. It's not OK if the machine config is
*preventing* us from correctly identifying whether CUDA is there.

Check for missing folder shortnames where needed

---

sbin/common/common.sh

Fixes: #1707
Fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1725
Stops attempting to find & setting the `JDK-BOOT-DIR` when running `configure_build` on the host machine of a docker-build. This works because the  `BUILD_CONFIG[DOCKER_FILE_PATH]` variable isn't set until right before the docker container is built, therefore it doesn't skip setting the `JDK-BOOT-DIR` when running the build within the docker container. 
Tested / currently testing at: https://ci.adoptopenjdk.net/job/DockerfileCheck/179/ & https://ci.adoptopenjdk.net/job/DockerfileCheck/180/

Stop setting bootjdk on host when running docker-build

---

pipelines/gradlew

Likely cause of java.lang.StackOverflowError build failures, see: https://github.com/AdoptOpenJDK/openjdk-build/issues/2139

Increase gradlew java build to use -Xmx512m

---

sbin/build.sh

Since this is currently causing [significant delays](https://github.com/AdoptOpenJDK/openjdk-build/issues/2206) in the Solaris/SPARC pipelines and [this Slack discussion](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1605110513432600) did not provide a full conclusion as to whether it was needed (I've seen people hit issues with it on ARM builds as well in the past) we should remove this stage unless we can determine whether it is really required for something (metadata is all I can see that might utilise it but if the only reason for the shared lib is to use parseVersion during the build then we should perhaps come up with an alternate method)
[VPC run to check across build environments](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/924/)
Signed-off-by: Stewart X …

Stop building shared libs as it hangs on Solaris

---

docker-build.sh

Similar to https://github.com/AdoptOpenJDK/openjdk-build/pull/672.
`${BUILD_CONFIG[DOCKER_SOURCE_VOLUME_NAME]}` is a Docker volume, and according to the code, it's not shared so a `Z` is not required since it's implicit.

Fix docker-build.sh with SELinux

---

README.md
build-farm/make-adopt-build-farm.sh
pipelines/build/common/create_job_from_template.groovy
sbin/build.sh

Currently, we lose these speech marks when they get passed from
make-adopt-build-farm.sh to makejdk-any-platform.sh
This change prevents that.

Allow speech marks in configure args

---

pipelines/jobs/configurations/jdk16.groovy

Partially reverts https://github.com/AdoptOpenJDK/openjdk-build/pull/2251/files (@M-Davies I'm assume the pipeline configuration files don't need to have backed out here too)
Mitigation for https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1652
FYI @pshipton @aahlenst

JDK16: Temporarily stop JDK16/J9/XL/s390x builds due to capacity issues

---

build-farm/platform-specific-configurations/windows.sh
sbin/prepareWorkspace.sh

Draft until https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1753 is merged and [deployed on all machines](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1752)
Fixes #2297 

Update OpenJ9 to use OpenSSL 1.1.1i

---

sbin/build.sh

Only corretto jdk-8 has an extra "src" sub-folder now

Corretto jdk-11 does not have a src sub-folder any more

---

pipelines/build/common/openjdk_build_pipeline.groovy

I made this change for the JDK's but missed the second JRE block

fix win aarch64 installer build for JRE

---

build-farm/platform-specific-configurations/windows.sh
pipelines/jobs/configurations/jdk11u.groovy
pipelines/jobs/configurations/jdk8u.groovy

We could use AdoptOpenJDK pipelines to build Dragonwell on windows.
Dragonwell got a building limitation:
Dragonwell 8 Have to depend on bootstrap
So we may need to pull dragonwell windows release during build.
Also, we need this https://github.com/AdoptOpenJDK/openjdk-build/pull/2232 to build dragonwell on windows.

add Dragonwell on windows

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy

This fixes the current windows aarch64 build failure

buildArgs: allow args that aren't VM specific

---

sbin/build.sh
sbin/common/config_init.sh

CROSS_COMPILE is an environment variable relevant to OpenSSL make, the Adopt property is unrelated and for a different purpose

Rename BUILD_CONFIG CROSS_COMPILE to CROSSCOMPILE to avoid OpenSSL make conflict

---

RELEASING.md

Hopefully self-explanatory - this was missed for JDK17 (I've just done it)

docs: add pipeline calendar to new major version docs

---

build-farm/make-adopt-build-farm.sh

This constantly bugs me, so making it easier for manual invocation by telling people what's missing and fail fast!

make-adopt-build-farm.sh: fail fast if required env vars are missing

---

build-farm/platform-specific-configurations/windows.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2147 (OpenJ9 request)
Validating at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/978/

use VS2019 on OpenJ9 JDK15+ builds

---

build-farm/platform-specific-configurations/windows.sh

Update to https://github.com/AdoptOpenJDK/openjdk-build/pull/2339 to pick up the correct OpenSSL build

Adjust JDK15+/J9/Windows builds to pick up correct openssl

---

build-farm/platform-specific-configurations/windows.sh

I somehow hadn't commited an extra change that was on my machine in the last PR. Since this is a critical change I'm goign to push this through without approvals in order to ensure the nighly builds succeed in the same configuration as they've been running in previously

Fixup last PR

---

build-farm/platform-specific-configurations/windows.sh
pipelines/jobs/configurations/jdk16_pipeline_config.groovy

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2337
NOTE: I can't do the same for JDK17 for now as the jobs haven't been created, but doing this one step at a time to check machine capacity is a good thing. We could also wait until JDK15 is no longer needed before enabling JDK17 fully
Notes to reviewers:
1. PLEASE be certain I haven't made any typos in the syntax
2. PLEASE leave it for me to merge so I can do it at a time I'm paying attention to the pipelines when it first gooes through

Add default nightly testing on JDK16

---

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy

Not sure why, but at the moment the vendor version string doesn't work properly when on a non-alibaba build machine. It's something we need to understand (so this should NOT close issue https://github.com/AdoptOpenJDK/openjdk-build/issues/2329#issuecomment-750916933) but this will stabilise the builds and allow us to resolve any follow-on problems for now.

lock jdk11 dragonwell to alibaba build machines (for now)
