adoptium/temurin-build

pipelines/build/common/openjdk_build_pipeline.groovy

Sign and Installer job timeout should be managed in the Jenkins job config so as not to include the node queue in the timeout.

Don't timeout Sign and Installer jobs when queueing for node

---

pipelines/jobs/configurations/jdk15u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy
pipelines/jobs/configurations/jdk17_pipeline_config.groovy

Without centos7 the builds can also target the OSUSL pple Cloud which is currently not operational

Ensure jdk15/16/17 build ppcle on centos7 nodes

---

pipelines/build/common/openjdk_build_pipeline.groovy

This to prevent artifact accumulation, and eventual issues due
to an over-filled master node.

Clean up the artifacts on master after archiving them elsewhere

---

pipelines/build/common/openjdk_build_pipeline.groovy

Mac runs leave these behind. We should preserve the ones from the
current run to aid debugging, and delete the rest to prevent the
buildup of plaque.

Clean up redundant json and sha256 files from previous mac runs

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/jobs/configurations/jdk15u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy
pipelines/jobs/configurations/jdk17_pipeline_config.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy
pipelines/src/test/groovy/IndividualBuildConfigTest.groovy

Allow additional test labels, for example jdk15+ openj9 cannot run on centos6 or rhel6.

Add ADDITIONAL_TEST_LABEL to allow targeting variant test jobs appropriately

---

build-farm/platform-specific-configurations/windows.sh
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy

As per https://github.com/AdoptOpenJDK/openjdk-build/pull/2354#pullrequestreview-561238497 we need to have redundancy in our infrastructure to ensure things are not tied to single systems with customer configurations. Installing the Dragonwell boot JDK8 as per the playbooks means we can build Dragonwell on all systems.
Based on the comment at https://github.com/AdoptOpenJDK/openjdk-build/issues/2329#issuecomment-751429058 it is possible that https://github.com/AdoptOpenJDK/openjdk-build/pull/2352 resolves the JDK11 issue, so this reverts both #2341 and #2354
Merging this will give us additional time to diagnose the alibaba current alibaba build system issues, there this hopefully fixes #2329 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1832

Dragonwell Windows everywhere

---

RELEASING.md
pipelines/build/common/weekly_release_pipeline.groovy
pipelines/build/regeneration/build_pipeline_generator.groovy
pipelines/jobs/configurations/jdk11u.groovy
pipelines/jobs/configurations/jdk15u.groovy
pipelines/jobs/configurations/jdk16.groovy
pipelines/jobs/configurations/jdk17.groovy
pipelines/jobs/configurations/jdk8u.groovy
pipelines/jobs/weekly_release_pipeline_job_template.groovy

Add into the pipeline jdk job config weekly release build scmReference configuration, allowing the weekend weekly build to actually build the release tags/branches.

Add scmReference config for weekly release builds

---

pipelines/build/common/config_regeneration.groovy
pipelines/jobs/pipeline_job_template.groovy

Disabled as per the instructions now in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md
@andrew-m-leonard  I assume none of your recent scheduling changes will invalidate this way of disabling the tests

Disable nightly testing during January 2021 release cycle

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk16_pipeline.groovy
pipelines/build/openjdk17_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/jobs/pipeline_job_template.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy
pipelines/src/test/groovy/IndividualBuildConfigTest.groovy

Some AIX nodes at ci.AdoptOpenJDK only have about 35Gb of disk space, some j9 extended.functional testcases produce j9core.dmp files of the size 2-3Gb, a complete Test job may run this 10+ times using 20+Gb of disk space before the job completes and resulting in the machine runninf out of space and hanging...
This PR adds the following support for KEEP_REPORT_DIR which will delete the report dir containing the dumps after each successful testcase, thus the job will consujme far less space.
Add a new build pipeline param "keepTestReportDir" defaults to false
And corresponding BuildConfig: KEEP_TEST_REPORTDIR
Pass down to test job, but not for JUnit test jobs (eg.openjdk) which default to true.

Add pipeline param for test KEEP_REPORTDIR

---

pipelines/jobs/configurations/jdk11u.groovy
pipelines/jobs/configurations/jdk15u.groovy
pipelines/jobs/configurations/jdk8u.groovy

Now the releases are out the way we can change the weekend release test build back to building the HEAD branches.

Revert weekend test release pipeline builds to HEAD tags

---

pipelines/build/common/config_regeneration.groovy
pipelines/jobs/pipeline_job_template.groovy

GAs are mostly out at the time of writing so we should be safe to re-enable.
This reverts commit ea53ac3d1623de5ecefdcd9aee3379a776be84b2.

Revert "Disable nightly testing during January 2021 release cycle (#2392)

---

RELEASING.md
pipelines/build/regeneration/build_pipeline_generator.groovy
pipelines/jobs/configurations/jdk15u.groovy

Disable jdk15u pipeline now that it is retired

---

README.md
sbin/build.sh
sbin/common/config_init.sh

debug-image and debug-symbols archives were the same. I'm removing the debug-symbols folder and archive creation and instead redirect that logic to create a debug-image archive.
By default, for OpenJ9 the debug-image will be created (as it was already working), for other platforms, we must add the `--create-debug-image` option.

Unify debug-image and debug-symbols creation option

---

.github/workflows/build.yml
.github/workflows/compile.yml
.github/workflows/linter.yml

currently, we run builds on code that has been merged into master. This is a waste of executor time

actions: only run builds on pull request

---

pipelines/build/common/openjdk_build_pipeline.groovy

This is a temporary fix to clean workspaces on alibaba machines before builds. Currently both alibaba machines are facing this issue
```
18:10:26  ERROR: Failed to clean the workspace
18:10:26  jenkins.util.io.CompositeIOException: Unable to delete 'C:\Jenkins\temp'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
18:10:26  	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:90)
18:10:26  	at hudson.Util.deleteContentsRecursive(Util.java:262)
18:10:26  	at hudson.Util.deleteContentsRecursive(Util.java:251)
18:10:26  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:743)
```
This issue has affected other windows boxes, hence the pr https://github.com/AdoptOpenJDK/openjdk-build/pull/1956, so I am putting a similar …

Clean problematic files on alibaba workspaces

---

sbin/build.sh
sbin/prepareWorkspace.sh

Machines are now working at full speed after a reboot so these can be revoked ... Currently testing. We should however, consider if the Gradle step can be skipped everywhere since Solaris seems happy without it and it breaks more often than I'd like ([Ref this issue](https://github.com/AdoptOpenJDK/openjdk-build/issues/2139))
Reverts https://github.com/AdoptOpenJDK/openjdk-build/pull/2276 and https://github.com/AdoptOpenJDK/openjdk-build/pull/2228 and should maybe also revert https://github.com/AdoptOpenJDK/openjdk-build/pull/2225
Recommend taking care when this is merged as we may want ot keep the individual commits, or change the first line of the commit message

Remove overrides to remove gradle and cacerts from Solaris/SPARC

---

pipelines/build/common/build_base_file.groovy
pipelines/build/common/weekly_release_pipeline.groovy
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk16_pipeline.groovy
pipelines/build/openjdk17_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/jobs/pipeline_job_template.groovy

Add a new build pipeline param keepReleaseLogs which defaults to true, but weekend test builds set to false.

Update weekend release test pipelines so they do not lock Jenkins logs

---

.gitignore
pipelines/jobs/configurations/jdk11u.groovy
serverTimestamp.properties
sign.sh

This does the following:
- Implements timestamp server fallback as originally attempted in https://github.com/AdoptOpenJDK/openjdk-build/pull/2405 and https://github.com/AdoptOpenJDK/openjdk-build/pull/2374 - this supercedes both
- Adjusts the ordering so that the "known good" server is first in the list, reducing the likelihood of failure (globalsign is no longer working today)
- Unifies the `exe` and `dll` parts in a single `find`
- Adjusts the way the JDK directory is detected, thus removing the `find: 'basename' terminated by signal 13` that have been polluting the logs
- Uses `-q` on the `unzip` command in order to avoid filling the log with a list of all files in the JDK
The latest runs of [sign_build](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build) have …

Use multiple backup timeservers for Windows signing

---

pipelines/build/common/openjdk_build_pipeline.groovy

The openj9 extensions repo to runTests against was being determined incorrectly for the jdk(head) scenario.

Use the correct openj9 extensions repo name to runTests

---

pipelines/build/prTester/pr_test_pipeline.groovy

Update defaultJavaVersions in prTester to 8,11,16,17

---

sbin/build.sh
sbin/common/common.sh
sbin/prepareWorkspace.sh

Found this useful while running multiple builds in succession so I feel it could be beneficial here if we want to see which sections are fast/slow in different environments (also highlights [CaCerts](https://github.com/AdoptOpenJDK/openjdk-build/pull/2113) and [gradle timings](https://github.com/AdoptOpenJDK/openjdk-build/issues/2139))
This may be useful in optimising for third-party users of our build scripts
(If anyone feels particularly strongly about the removal of `showCompletionMessage()` let me know but it seems to be extra complexity wrapping a function around an echo statement :-) )

build.sh: Add eyecatcher timestamps to check build performance

---

pipelines/jobs/configurations/jdk8u.groovy

Until we have working Solaris x64 machines, we shall remove this from the nightly as it hangs the whole build pipeline.
See:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1871
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1865

Remove x64Solaris from nightly until a working build machine is available

---

FAQ.md
pipelines/build/common/build_base_file.groovy
pipelines/build/common/config_regeneration.groovy
pipelines/build/common/create_job_from_template.groovy
pipelines/build/common/openjdk_build_pipeline.groovy
pipelines/build/openjdk10_pipeline.groovy
pipelines/build/openjdk11_pipeline.groovy
pipelines/build/openjdk12_pipeline.groovy
pipelines/build/openjdk13_pipeline.groovy
pipelines/build/openjdk14_pipeline.groovy
pipelines/build/openjdk15_pipeline.groovy
pipelines/build/openjdk16_pipeline.groovy
pipelines/build/openjdk17_pipeline.groovy
pipelines/build/openjdk8_pipeline.groovy
pipelines/build/openjdk9_pipeline.groovy
pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
pipelines/jobs/configurations/jdk16_pipeline_config.groovy
pipelines/jobs/configurations/jdk17_pipeline_config.groovy
pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
pipelines/jobs/pipeline_job_template.groovy
pipelines/library/src/common/IndividualBuildConfig.groovy
pipelines/src/test/groovy/IndividualBuildConfigTest.groovy

Add the facility to clean the build workspace or just the workspace/build/src/build and workspace/target binary output at the end of the build. This provides a large saving of disk space, up to 30Gb for Build Output alone and an additional 6Gb for the whole workspace. The default settings for generated pipelines are:
- cleanWorkspaceAfterBuild : false
- cleanWorkspaceBuildOutputAfterBuild : true
Additionally, cleanWorkspaceAfterBuild can be specified in the jdk platform configuration if a specific platform requires cleaning only.

Add cleanWorkspaceAfterBuild and cleanWorkspaceBuildOutputAfterBuild

---

build-farm/platform-specific-configurations/windows.sh

Aligns AdoptOpenJDK with upstream which is already using VS 2019; see https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms.
For details, see gh-2432 and gh-2147.

Use VS 2019 to build OpenJDK 16+ on Windows

---

pipelines/build/common/openjdk_build_pipeline.groovy

currently, we are passing the incorrect SCM ref to the test repo for aarch64 and arm32.
Example: 
jdk8u aarch64 SCM_REF is set to `aarch64-shenandoah-jdk8u282-b08`.
This tag doesn't exist in the jdk8 source because it comes from a different repo. By using the `OVERRIDE_FILE_NAME_VERSION` variable we are able to select the correct tag

fix downstream SCM_REF in tests for aarch64 and arm32

---

pipelines/build/common/openjdk_build_pipeline.groovy

Previous clean workspace PR updated to use rm -rf *, which does not include hidden files.
This PR includes a post clean with cleanWs to clear the hidden files.

Update build pipeline clean workspace to delete hidden files

---

sbin/build.sh

Fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/2412
Currently the `HEAP_SIZE` value in the `release` file is incorrect and states "Large" while x86 OpenJ9 binaries are only produced with standard heap size. This PR adds a check for the architecture being built on and factors this in when setting the `HEAP_SIZE` value.
Old `release` file for x86:
```
JAVA_VERSION="1.8.0_282"
OS_NAME="Windows"
OS_VERSION="5.1"
OS_ARCH="i586"
SOURCE="OpenJDK:ab07c6a8fd OpenJ9:345e1b09e OMR:741e94ea8"
IMPLEMENTOR="AdoptOpenJDK"
BUILD_SOURCE="git:10223734"
FULL_VERSION="1.8.0_282-b08"
SEMANTIC_VERSION="8.0.282+8"
BUILD_INFO="OS: Windows Server 2012 R2 Version: 6.3"
JVM_VARIANT="Openj9"
JVM_VERSION="openj9-0.24.0"
HEAP_SIZE="Large"
IMAGE_TYPE="JDK"
```
New `release` file for x86:
```
``` …

Correct "HEAP_SIZE" release file value for x86 OpenJ9 builds

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

Draft PR to auto-set JDK_BOOT_DIR based on default locations symlinked by the ansible playbooks. This should remove the need to have JDKxx_BOOT_DIR definitions on the build machines in jenkins and reduce the number of times a boot JDK is downloaded dynamically during the builds
[VPC run](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/912/)

Autodetect boot JDK location based on playbook defaults

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

Reverts #1409 and allows a JDK10 boot JDK (For JDK11) to be auto-detected and downloaded, which https://github.com/AdoptOpenJDK/openjdk-build/pull/2167 was not able to do.
JDK7 (for JDK8) will still be detected if present, but will not be auto-downloaded (highly unlikely any machine would not have it set up anyway...)
Summary:
- Removes the conditional surrounding the detection/download
- Adjusts the "Downloading" message to print the API target we are downloading from (means moving that line to after `apiURL is set`)
- Changes indentation and the wrapping of one comment (which is why this looks more substantial than it is (Suggest reviewers do the review with whitespace ignored)
- Moves the printing of the `BOOT JDK` `java -version` output little earlier, and suppresses the printing on …

Remove java 11 boot JDK restriction (Reverts PR 1416 and then some!)

---

sbin/build.sh

Correctly find Mac dSYM folders only
Also add .map to Windows debug image
Also corrected missing -o find for failed build dump find

Correctly find MacOS dSYM folders only

---

build-farm/platform-specific-configurations/windows.sh

echo statement was correct, but the following line was incorrect due to a cut & paste error meaning it was set to the PATH on Linux/AIX systems instead of windows.

Fix for boot JDK autodetection in windows.sh

---

build-farm/make-adopt-build-farm.sh

Follow on from https://github.com/AdoptOpenJDK/openjdk-build/commit/238ad36cb85d19ce443f6f0a16ea2153ff4c10ce - autodetect default values (but tell user what is being defaulted so they can override easily if required ...
Testing with [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1058/) and [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/203/)

autodetect as much as possible in make-adopt-build-farm.sh

---

build-farm/platform-specific-configurations/mac.sh

We do not have a macos JDK7 to use as a bootstrap for JDK8
Problem introduced by a recent autodetect PR (Apparently macos systems didn't have a JDK7_BOOT_DIR pointing to this in their jenkins definition)
Fixes #1959

macos: Use JDK8 for bootstrapping JDK8

---

sbin/build.sh

The previous Mac debug symbol copy change was copying the directory but not its contents! this fixes that.

Copy MacOS dSYM folder contents

---

build-farm/make-adopt-build-farm.sh

Enable debug images for all platforms except AIX (upstream does not support external native debug symbols yet)

Enable debug images for all platforms except AIX

---

build-farm/platform-specific-configurations/aix.sh

ref https://github.com/eclipse/openj9/issues/12018 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1952
Ive updated the LIBPATH variable for AIX so that it provides a path to the library /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/8/pthread/libstdc++.a, which has a symlink in /opt/freeware/lib/pthread/ppc64.
This solves a cmake issue we seem to be getting, which causes the following error
```
13:56:15  Could not load program cmake:
13:56:15  Symbol resolution failed for cmake because:
13:56:15  	Symbol _ZTINSt6thread6_StateE (number 358) is not exported from dependent
13:56:15  	  module /opt/freeware/lib/libstdc++.a[libstdc++.so.6].
13:56:15  	Symbol _ZTVNSt6thread6_StateE (number 359) is not exported from dependent
13:56:15  	  module …
```

AIX: LIBPATH to include /opt/freeware/lib/pthread/ppc64 at the front

---

build-farm/platform-specific-configurations/windows.sh

fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/2493

windows: switch aarch64 builds to use correct boot jdk version

---

build-farm/platform-specific-configurations/aix.sh

Issue https://github.com/AdoptOpenJDK/openjdk-build/issues/2466 when building jdk16/17 AIX hotspot, using a hotspot boot jdk instead avoids the problem.

Use AIX hotspot bootjdk to avoid issue #2466

---

build-farm/platform-specific-configurations/linux.sh

Logical and `&&` should be used together with `[[ ]]` in condition statements, replace with `-a` when using `[ ]`.
#2485 breaks openj9 riscv build pipeline.

Fix syntax error in build-farm/platform-specific-configurations/linux.sh

---

sbin/prepareWorkspace.sh

Probably introduced as part of https://github.com/AdoptOpenJDK/openjdk-build/pull/2485/files
I've seen this a couple of times today:
```
/home/sxa/dw/openjdk-build/sbin/prepareWorkspace.sh: line 59: [: missing `]'
/home/sxa/dw/openjdk-build/sbin/prepareWorkspace.sh: line 59: dragonwell: command not found
```

Fix syntax error in sbin/prepareWorkspace.sh

---

build-farm/platform-specific-configurations/linux.sh

Related issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2501
In https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-dragonwell/164/console , we should be using 
```
CC=/usr/local/gcc9/bin/gcc-9.3
```
Also, limit GCC only on  aarch64 platform

Fix gcc-9.3 build error and limit gcc 9.3 on dragonwell aarch64

---

FAQ.md

* Twin PR for ci-jenkins-pipelines -> https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/67

Update FAQ to account for #2463

---

build-farm/platform-specific-configurations/windows.sh

Reverts AdoptOpenJDK/openjdk-build#2494
Partially fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2511

Revert "windows: switch aarch64 builds to use correct boot jdk version"

---

build-farm/platform-specific-configurations/linux.sh

Currently the builds scripts are hard coded to build using a cross-compiler on RISC-V.
While this is fine for OpenJ9, this is not curently testd for Bisheng (https://github.com/AdoptOpenJDK/openjdk-build/issues/2420) therefore this PR will detect if we are building for a RISC-V target on an x86_64 host and if not it will disable the cross compiler options.
Alternative options: Use "if not riscv64" instead of "if x86_64" although I doubt anyone's going to try and cross compile elsewhere, and if they do then the message will be the same as it is if they try the same trick elsewhere :-)

De-duplicate RISCV cross compile code and allow native builds too

---

build-farm/platform-specific-configurations/linux.sh

Blatant error that didn't get picked up in reviews of https://github.com/AdoptOpenJDK/openjdk-build/pull/2509 ;-)
Luckily there wasn't a JDK11 build last night as this would have broken RISC-V since it was merged in the evening (something that #2504 would likely have helped with :-P )

Fix RISC-V cross-compilation environment detection

---

build-farm/platform-specific-configurations/linux.sh

The original check of `[ ! -x "$CXX" ]` returns false when the location exists, so the `set -e` causes the script to fail at that point which is not the desired behaviour. This reverses the logic so it works as expected. I'm on a roll today ...
This needs to be put in before the nightly builds

Fixup RISC-V cross-compiler check so it doesn't fail with set -e

---

build-farm/platform-specific-configurations/linux.sh

We lost the `--disable-ddr` and build JDK options required for OpenJ9 in https://github.com/AdoptOpenJDK/openjdk-build/pull/2509/files - this reinstates them to allow it to build properly again.
Running some tests to verify but I'm confident this will fix everything. Will also need https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/81 but I'm confident that this will end up with the simplest code that will build OpenJ9 and the Bisheng RISC-V builds in the desired tested environments and configurations.
Please leave me to merge this once after review to ensure I've completed testing.

Unbreak RISC-V OpenJ9 build

---

build-farm/sign-releases.sh
sign.sh

Add param SIGN_TOOL that will allow other signing
tools to be used.
Add case for Windows "ucl" sign tool.
Default to signtool.exe on Windows.

Allow other sign tools via param SIGN_TOOL

---

build-farm/make-adopt-build-farm.sh

Found while verifying https://github.com/AdoptOpenJDK/openjdk-build/pull/2539. Introduced with the new autodetection in https://github.com/AdoptOpenJDK/openjdk-build/commit/3ec1ae9aa9d66114ee07be15205a2b6064c85101 (which isn't used by our pipelines)
While we use `armv7l` for `OS_ARCHITECTURE`, the `ARCHITECTURE` variables should be `arm` for arm32 builds.

make-adopt-build-farm: Use arm instead of armv7l

---

configureBuild.sh

Surprised this didn't cause any problems, but it was introfuced by https://github.com/AdoptOpenJDK/openjdk-build/commit/87f799024a58d392255eead1cd83d93515410b2e (for which I was one of the co-reviewers - apologies)

Missing ] in configureBuild.sh for arm

---

sbin/build.sh

Linux/x64 build logs have:
```
17:00:21  ===RELEASE FILE GENERATED===
17:00:21  basename: invalid option -- 's'
17:00:21  Try `basename --help' for more information.
```
I believe this is equivalent to what the `-s` was intending to trap.

Stop use of 'basename -s' which does not work on Cent/RHEL6

---

build-farm/platform-specific-configurations/linux.sh

We often have scaleway build machines offline - most recently [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2061) - this is to add some extra checks that will be performed on those systems before a build is executed to see if there are any obvious problems. I do not anticipate this being permanent.

checks for processes on Linux/arm32 builds for scaleway

---

sbin/build.sh

* Causes issues on mac with ls

Disable shellcheck and quotes on JRE mirror

---

sbin/build.sh

Update jdk11+ java.vendor.version for Adopt binaries to be:
AdoptOpenJDK-\<metadata version\>

Add metadata version to java.vendor.version

---

build-farm/platform-specific-configurations/aix.sh

Warn user if AIX ulimit is too low to perform the git checkout operations.
For all but JDK11, the default AIX limit of `1048575` should (only just for JDK8 - it needs 860Mb at the time of writing) work. Our jenkins users have this limit larger by defualt, but for anyone running our scripts themselves, this will warn them and pause to try and encourage to read the message otherwise they are likely to end up with things like this:
```
Cloning into 'openjdk-jdk11u'...
fatal: write error: A file cannot be larger than the value set by ulimit.
fatal: index-pack failed
```

Add warning if AIX ulimit -n is too low

---

sbin/build.sh
sbin/prepareWorkspace.sh

When this value is empty ("") it will cause git commands
to fail because "" will be picked up as an argument
Introduced by 962e6febfeb

Remove quotes from BUILD_CONFIG[SHALLOW_CLONE_OPTION]

---

build-farm/platform-specific-configurations/linux.sh
configureBuild.sh
sbin/build.sh
sbin/common/config_init.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2531 - I've removed the processing of `version.txt` from this because Bisheng doesn't have a `version.txt` that I can see - perhaps that needs to chnage?
Tag processing will need extra work before this is finalised - specifically [this line](https://github.com/AdoptOpenJDK/openjdk-build/blob/bd103bb984217fe49082db2a843692cf7880d6cb/sbin/build.sh#L873):
```
TAG_SEARCH="jdk-*+*bisheng_riscv"
```

add support for Bisheng JDK8 and 8/11 on non-RISCV platforms

---

build-farm/platform-specific-configurations/mac.sh

Fixes the following configure error:
```bash
17:52:59  checking for metal... [not found]
17:52:59  checking if metal can be run using xcrun... no
17:52:59  configure: error: XCode tool 'metal' neither found in path nor with xcrun
17:52:59  configure exiting with result code 1
```

macos: use full xcode for jdk17+

---

test/functional/buildAndPackage/src/net/adoptopenjdk/test/BundledFreetypeTest.java
test/functional/buildAndPackage/src/net/adoptopenjdk/test/package-info.java

Currently, BundledFreetypeTest cannot find the freetype file it's
looking for on Windows, as that file is named "freetype.dll" (no lib).
Modifying the regex to match this, while still allowing
libfreetype.dylib (the macos file name).

Fix for BundledFreetypeTest on Windows

---

test/functional/buildAndPackage/playlist.xml
test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java

Enable arch ppc64 for smoke tests
related https://github.com/adoptium/ci-jenkins-pipelines/issues/127

Enable arch ppc64 for smoke tests

---

test/functional/buildAndPackage/src/net/adoptopenjdk/test/CudaEnabledTest.java
test/functional/buildAndPackage/src/net/adoptopenjdk/test/VendorPropertiesTest.java

Update smoke test to work with openj9 jdk
Related: https://github.com/adoptium/ci-jenkins-pipelines/issues/127#issuecomment-819194309

Update smoke test to work with openj9 jdk

---

build-farm/platform-specific-configurations/mac.sh

Fixes the bug reported in https://github.com/AdoptOpenJDK/openjdk-build/issues/1922#issuecomment-820747121
Essentially the arm64 macs were still cross-compiling for x64 rather than building on arm64
Confirmed to be fixed:
```bash
file java
java: Mach-O 64-bit executable arm64
```

macOS: prevent m1 builds from cross compiling x64

---

test/functional/buildAndPackage/src/net/adoptopenjdk/test/FeatureTests.java

As per the Shenandoah project webpage, if shenandoah is set as a
with-jvm-features option during pre-build configuration (which Adopt
does), then we should expect Shenandoah to be both present and
functional in the build.
My assumption is that Windows 32bit was simply skipped during smoke
test pre-deployment testing, and this problem was simply not seen
as a result.

Shenandoah present on win32

---

build-farm/platform-specific-configurations/alpine-linux.sh

This makes us consistent with other linux builds, which also
do not bundle freetype to avoid various problems.

Don't bundle freetype with alpine linux

---

sbin/build.sh

Fixes https://github.com/adoptium/adoptium-support/issues/298 (Rogue symlink to something that gets deleted)

Remove invalid debuginfo symlink

---

test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkVersion.java
test/functional/buildAndPackage/src/net/adoptopenjdk/test/VendorPropertiesTest.java

The vendor name (AdoptOpenJDK) is only present in JDK8 Hotspot
java -version output because AdoptOpenJDK added this functionality
into their fork of the source code.
Until this code gets added to the source for other VMs, we should not
look for it on non-Hotspot JDK8 builds.

Skip test for missing vendor name in minus version on JDK8 OpenJ9

---

sbin/build.sh

SEM_VER calculation from build tag was incorrectly removing "0" from anywhere in the tag.
Fixes: adoptium/adoptium-support#295

Correct jdk8u SEM_VER creation from build tag

---

test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

As reported by @andrew-m-leonard
```bash
19:38:37      [javac] /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-ppc64le-hotspot_SmokeTests/openjdk-tests/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java:26: error: package net.adoptopenjdk.test does not exist
19:38:37      [javac] import static net.adoptopenjdk.test.JdkVersion.VM;
```

fix broken vendor version test

---

build-farm/platform-specific-configurations/mac.sh
sign.sh

Currently this only works for Windows and macOS (jdk8u). I will need to fix up the remaining macOS versions.

Switch codesigning to use Eclipse Foundation certificate

---

build-farm/platform-specific-configurations/linux.sh

Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2119 until https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2145 is resolved.
[VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1169) / [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/261/)

Tactical fix to force OpenJ9 JDK16+ to download a HotSpot boot JDK

---

test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

"java.vendor.version" was added to JDK10. Disable tests for jdk8 
Close #2583 

Disable javaVendorVersion tests for jdk8

---

sign.sh

Currently, the executable bit isn't added back to the codesigned binary:
```bash
bin/java: Permission denied
```

Fix Windows codesign permissions

---

build-farm/sign-releases.sh

Using the EF signing tool we lose over 45 minutes signing these two archives

skip codesigning testimage and debugimage

---

sbin/build.sh

On Alpine the "sort" behaviour for empty numeric sort fields is different, eg.jdk-16<.0.0>+36
Pad field fully before sorting

Handle get jdk tag sort behaviour on Alpine for empty field behaviour

---

sbin/build.sh

This is required as part of the EF codesign work
These commands originally came from https://github.com/adoptium/installer/pull/316

modify plist values as part of build instead of installer

---

test/functional/buildAndPackage/src/net/adoptium/test/JdkVersion.java
test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

This exception is specific to OpenJ9, so the exception should mention
it by name.

Clarify test exception for JDK8 on OpenJ9

---

.github/ISSUE_TEMPLATE/buildbreak.md
RELEASING.md
docker/buildDocker.sh
sbin/build.sh

These repositories are now in the eclipse-openj9 organization:
* https://github.com/eclipse-openj9/openj9
* https://github.com/eclipse-openj9/openj9-omr

Update openj9 URLs

---

sbin/build.sh

It was removed as part of https://github.com/adoptium/temurin-build/pull/2417 but it was clearly missed for the exploded image

Remove showCompletionMessage

---

sbin/build.sh

This is required so that make will only touch the jmods and not re-compile them after signing

add make -t to make command before creating assembled image

---

sbin/build.sh

These steps are all run on regular builds but weren't added to the ASSEMBLE_EXPLODED_IMAGE function

Add missing steps for ASSEMBLE_EXPLODED_IMAGE build

---

sbin/build.sh

Fixes the JDK11 OpenJ9 build failure on macOS:
```bash
09:14:56  **********************************************************************
09:14:56  ***                                                                ***
09:14:56  ***   OpenSSL has been successfully configured                     ***
09:14:56  ***                                                                ***
09:14:56  ***   If you encounter a problem while building, please open an    ***
09:14:56  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
09:14:56  ***   and include the output from the following command:           ***
09:14:56  ***                                                                ***
09:14:56  ***       perl configdata.pm --dump                                ***
09:14:56  *** …
```

skip running configure again after signing exploded image

---

sbin/build.sh

Prevents:
```bash
FULL_CONFIGURE: unbound variable
```

add fake value to FULL_CONFIGURE variable when assembling

---

test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

The vendor name in the -version output check has been modified to
match the vendor name we're expecting to find after a recent
change to the build configurations.
We also need the hard-coded vendor name to match the vendor name
present in the adoptium implimentation of the VmPropertiesChecks
interface (AdoptiumPropertiesChecks).
Lastly, the test has been modified so it compiles.

WIP: Fix smoke test to expect the right vendor name, plus other fixes

---

makejdk-any-platform.sh
sbin/build.sh
sbin/build.template
sbin/prepareWorkspace.sh

Extensions for re-recreatable builds as per: adoptium/temurin-build#2594 (comment)
Follow-on PR for ci-jenkins-pipelines will enable in metadata: https://github.com/adoptium/ci-jenkins-pipelines/pull/153

Add extended buildinfo to metadata

---

.github/workflows/build.yml

This should allow us to better test the changes that have recently gone in to support EF codesigning.
We took macOS out because we were starving the pool and builds were taking too long. I've reduced this to only build JDK8 and JDK11 hotspot so it should cope much better

actions: add macOS back to the pool to include exploded build testing

---

test/functional/buildAndPackage/src/net/adoptium/test/BundledFreetypeTest.java

The default behaviour for openjdk builds on AIX for JDK13+ is to bundle
freetype by default. So our freetype bundling test should be modified to 
expect this.

Expect bundled freetype on aix for JDK13 and up

---

test/functional/buildAndPackage/playlist.xml
test/functional/buildAndPackage/src/net/adoptium/test/CudaEnabledTest.java
test/functional/buildAndPackage/testng.xml

This changeset includes several upgrades to the cuda enablement test,
including:
- testing for enablement on Windows
- tolerance for all platforms
- tolerance for multiple-vm builds
- tolerance for builds with their j9prt file in a new place
and
- some tidying up for the playlist and testng files to bring this
j9 feature test in-line with the convention used for hotspot feature
tests.

Improve cuda enablement test

---

test/functional/buildAndPackage/playlist.xml
test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

This change includes a playlist tweak to enable the hotspot smoke
tests to run, and also modifies the expected system property
"java.vm.vendor" for adoptium's Hotspot JDK to be "Eclipse Foundation".
As this change brings "java.vm.vendor" in line with the values
expected from other properties, I'm asserting that this is likely
not a bug, but I'll consult with my fellow developers before
merging, just to be safe.

Enabling Hotspot Smoke Tests and correcting an expected value

---

sbin/build.sh

JDK8 version output:
```output
openjdk version "1.8.0_302-beta"
OpenJDK Runtime Environment (Eclipse Foundation)(build 1.8.0_302-beta-202106101234-b05)
OpenJDK 64-Bit Server VM (Eclipse Foundation)(build 25.302-b05, mixed mode)
```
JDK11+ version output:
```output
openjdk version "11.0.12-beta" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+5-202106101358 (build 11.0.12-beta+5-202106101358)
OpenJDK 64-Bit Server VM Temurin-11.0.12+5-202106101358 (build 11.0.12-beta+5-202106101358, mixed mode)
```

add beta to nightly version output

---

sbin/build.sh

Recent openj9 builds support both compressed and non-compressed object references.

OpenJ9: Remove obsolete 'HEAP_SIZE' property from release file

---

sbin/build.sh

Version out to be more consistent with JDK11+
```
openjdk version "1.8.0_302-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-beta-202106101522-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b05, mixed mode)
```

Set company name for JDK8 to label version output as Temurin

---

sbin/build.sh

Freetype is not installed in default workdir for Windows, so unless user specified FREETYPE_DIRECTORY --with-freetype cannot be used.

Correct freetypeDir check for jdk8 Windows where it is not installed

---

sbin/build.sh

Use bash functions to implement tag selection.
In the previous version, the second sort step didn't consider the line number inserted by the use of `nl` and thus might not return the appropriate tag.

Fix identification of latest git tag

---

.github/workflows/build.yml

I must have missed this when I copied from the Linux job

fix file extension for windows CI builds

---

build-farm/platform-specific-configurations/linux.sh

This will allow us to sped up the arm32 builds by running them in docker containers on the larger aarch64 hosts which we have. (Note that at present the main build will work but `make images` in the JDK currently requires a modified `uname` command which gives the correct result)
Related: https://github.com/adoptium/infrastructure/pull/2201

Allow building of arm32 target on aarch64 kernels with default 32-bit userspace (and use >4 cores)

---

sbin/common/config_init.sh

For the "reproducible builds" issue: https://github.com/adoptium/temurin-build/issues/2594#issuecomment-841199132
the key piece of information missing from the built "BUILD_CONFIG" was the full os version level the binary was built on, this adds that info.

Add BUILD_CONFIG[OS_FULL_VERSION]

---

sbin/common/config_init.sh

Arm machines do not have /etc/system-release, but do have /etc/os-release, default to NAME & VERSION from that if no system-release

Arm machines do not have /etc/system-release use /etc/os-release

---

build-farm/make-adopt-build-farm.sh
build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

OpenJ9 must use jdk-11 bootjdk for building jdk-11.
Also currently build-farm issues msg:
```
19:38:27  Required boot JDK version: 10
```
but does not actually always use this version.
Correct this logic and pass settings down to where boot jdk download logic is.

Ensure correct boot jdk is used for openj9 and correct required boot jdk console msg

---

build-farm/platform-specific-configurations/linux.sh
sbin/build.sh

A few changes here - mostly in the interests of usability of our scripts:
- Allow cross compilation in environments other than x86-64 (`NATIVE_API_ARCH` variable)
- Set `BUILD_CC` and `BUILD_CXX` for Bisheng if building natively on RISC-V
- Abort immediately if the build JDK is not usable.
- Allow Debian/Ubuntu-supplied native cross compilers from `/usr/bin` to be used
- Allow `RISCV_SYSROOT` to be overriden but still use `/opt/fedora28_riscv_root` *(what Adopt uses) as the default.
- If the tag detection logic fails e.g. building from a different openjdk repository and [--disable-adopt-branch-safety](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/FAQ.md#i-want-to-build-code-from-my-own-forkbranch-of-openjdk-in-jenkins) is specified, use 8u000-b00 or jdk-nn-0.0.0+0 to allow …

Updates to better handle RISC-V cross envs and alternate OpenJDK repos

---

makejdk-any-platform.1
sbin/build.sh
sbin/common/config_init.sh

This is useful to see the exact sources that were used when
building the JDK.
After this patch `./makejdk-any-platform.sh --create-source-archive` can be used to produce `-sources` tarballs/zips.
Closes #2698

Add support for creating source archives

---

README.md
sbin/build.sh
sbin/common/config_init.sh
test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

As discussed in the marketing group meeting and in the Adoptium Workgroup Steering Committee meetings this week. This should remove ambiguity to end users by clarifying that this is the "Adoptium" build.

Change vendor from Eclipse Foundation to Eclipse Adoptium

---

.azure-devops/build/steps/macOS/before.yml
.azure-devops/build/steps/windows/before.yml
.github/workflows/labeler.yml
build-farm/make-adopt-build-farm.sh
build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh
docker/buildDocker.sh
docker/dockerfile-generator.sh
sbin/common/common.sh

This fixes the failing JDK tip builds
fixes: https://github.com/adoptium/temurin-build/issues/2704
I really want to split these horrible blocks of code into a shared function but will work on that in a follow-up PR

switch bootJDK download scripts to use adoptium binaries

---

build-farm/platform-specific-configurations/mac.sh

This was broken when the architecture was renamed from `arm64` to `aarch64` in https://github.com/adoptium/ci-jenkins-pipelines/pull/147
Fixes: https://github.com/adoptium/temurin-build/issues/1922

fix macos aarch64 builds

---

sbin/NOTICE.template

This NOTICE file may be used for JDK17 (or later) builds.

Update for jdk17u repository reference

---

build-farm/platform-specific-configurations/windows.sh
sbin/prepareWorkspace.sh

Reviews welcome but this is draft for now until the deployment has been done to all Windows boxes (@Haroon-Khel can you run the openssl role on all of them now that https://github.com/adoptium/infrastructure/pull/2299 has been merged, then we can look at merging this.

Update OpenSSL version to 1.1.1l

---

sbin/build.sh

- For one the target filename gets now properly replaced by using
sed over Bash variable substitution.
- For two, add an extra check to fail the build if the resulting
tarball name doesn't contain string `-sources`
- For three, add '-' file argument passed to grep so as to properly
set the return code as if expressions rely on them
Closes #2722

Fix source archive creation

---

configureBuild.sh
sbin/build.sh

We do not ship JRE's on JDK16+. This PR skips building them but can be overridden if another vendor is using our scripts

skip building JRE's on JDK16+

---

sbin/build.sh

Possibly due to changes in `awk`, current builds have the following content in the `release` file, which is hard to parse:
```
BUILD_INFO="OS: Mac OS X Version: 10.14.6
18G84"
```
This change fixes the shell command to no longer produce newlines, which should restore the normal nature of this entry. I was unable to test this change as it was reported to me by a user of one of my programs, and I don't have a Mac to verify on, but they ran the command that is now there and confirmed it does not produce a newline-separator anymore.

Fix macOS build info containing newline

---

sbin/build.sh

Issue:
After downloading a macOS tar.gz file build by AdoptOpenJDK and try to access the content directly (for example: `./jdk-11.0.10+9/Contents/Home/bin/java -version`). A dialog will pop up and warn the user that the package is damaged:
Same problem exist for Corretto & Microsoft Build of OpenJDK (https://github.com/microsoft/openjdk/issues/10). However, Zulu tar.gz file does not have this problem.
I notice the signature information is a little bit different by using: `codesign -dvvv {directory}`:
Zulu:
```
Executable=/Users/junyuanz/Downloads/zulu11.45.27-ca-jdk11.0.10-macosx_x64/zulu-11.jdk/Contents/MacOS/libjli.dylib
Identifier=com.azul.zulu.11.0.10.jdk
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=805 flags=0x10000(runtime) hashes=16+5 location=embedded
Hash …
```

code signing macOS binary directory before creating tar.gz file

---

sbin/build.sh

This partially reverts https://github.com/adoptium/temurin-build/pull/2705 and makes the version output say `(Temurin)` instead of `(Eclipse Adoptium)` to make it consistent with other versions and vendors
NOTE: Does not currently have the desired effect as this also causes `java.vendor` to become `Temurin` again on JDK8

Revert removal of Temurin name from JDK8 java -version output

---

build-farm/platform-specific-configurations/linux.sh

We only build this on JDK11 so this hard coding will work for now until we can find a suitable API call for the Semeru nightlies.
Workaround for https://github.com/adoptium/temurin-build/issues/2726

Temporary fudge to make RISC-V OpenJ9 builds work again

---

.github/workflows/build.yml

Currently, if a user pushes several commits to a PR the CI will try to build each commit. This wastes both time and resources.
This PR adds a task that will cancel any other builds for the same PR.

Actions: auto cancel builds if user pushes another commit

---

build-farm/platform-specific-configurations/linux.sh
sbin/prepareWorkspace.sh

This is impacting the OpenJ9 buids which use freemarker and I believe `curl` will work on the affected systems (or at least many of them!) as it uses it's own CA store.
FYI @AdamBrousseau 

Use curl and not wget by default to avoid LetsEncrypt SSL handshake for freemarker and boot JDK downloads

---

docker/dockerfile-generator.sh

This pull request address the issue #2776 by using Java 11 to build Java 11, instead of failing to get Java 10 from https://api.adoptium.net/v3/info/available_releases.
Additionally, Dockerfile now will git clone the jenkins pipeline instead of trying (and failing) to copy it.
I tested it by comparing Dockerfile generated for Java 11, 17 and 18 from master and this branch,

Fix Dockerfile generator for Java 11

---

test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

- Since java vendor was set to `adoptium`, other vendors are not recognized
- Add VmPropertiesChecks for ibm to fix the smoke test failure
- Related Issue: ibm_backlog/625
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

Add support for more java vendors

---

.gitignore
docker/buildDocker.sh
docker/dockerfile-generator.sh

This pull request address the issue on #2771 and add a wget/curl wrapper on the `buildDocker.sh` and `dockerfile-generator.sh` so that it work out of the box on macOS, where `wget` is not available.
I tested by running it on macOS with curl, Ubuntu 20.04 with wget and on the master branch, and the Dockerfile generated is the same.
DCO 1.1 Signed-off-by: David Dadon

Add wget curl wrapper

---

README.md
build-farm/make-adopt-build-farm.sh
configureBuild.sh
makejdk-any-platform.1
sbin/build.sh
sbin/common/config_init.sh

Add a new argument to the build scripts: --create-jre-image.
A JRE image is produced when this argument is set. It is optional for
JDK16 and above.
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

Add support for on-demand JREs for JDK16+

---

sbin/prepareWorkspace.sh

For performance reasons it is significantly faster to use github directly from the Adoptium Equinix machines.

Avoid using github proxy for downloading dragonwell submodules

---

test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java

- Fix vendor ibm corporation not found error
- Related Issue: ibm_backlog 686
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

Fix vendor ibm corporation not found error

---

build-farm/platform-specific-configurations/mac.sh

The JDK8u build no longer needs this flag
fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/47

remove COMPILER_WARNINGS_FATAL from macOS build

---

.gitignore
cyclonedx-lib/build.xml
cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
cyclonedx-lib/src/temurin/sbom/package-info.java
sbin/build.sh
sbin/common/config_init.sh

Download the necessary CycloneDX libraries and dependencies, and build a TemurinGenSBOM.java app framework.
Added a new BUILD_ARGS --create-sbom, default is "false", which when set builds the library and invokes TemurinGenSBOM at the end of the build.
**CycloneDX and dependent libraries and licenses:**
cyclonedx-core-java : v5.0.4 : Apache License, Version 2.0
jackson-core : v2.12.4 : Apache License, Version 2.0
jackson-dataformat-xml : v2.12.4 : Apache License, Version 2.0
jackson-databind : v2.12.4 : Apache License, Version 2.0
jackson-annotations : v2.12.4 : Apache License, Version 2.0
json-schema-validator : v1.0.58 : Apache License, Version 2.0
commons-codec : v1.15 : Apache License, Version 2.0
commons-io : v2.11.0 : Apache License, Version 2.0
github-package-url : v1.4.0 : MIT …

Add cyclonedx-lib build and --create-sbom option

---

sbin/build.sh

classpath to run TemurinGenSBOM on Windows had the wrong separators
also removed un-needed set -+eu

Make TemurinGenSBOM run on Windows

---

build-farm/platform-specific-configurations/linux.sh

Can be implemented now that https://github.com/adoptium/infrastructure/pull/2420 has been merged
Fixes https://github.com/adoptium/temurin-build/issues/2787 (Although for now not including JDK17)

Enable building with GCC 10.3 for JDK18 and above on Linux (Excluding OpenJ9)

---

RELEASING.md

Straightforward enough - new parameter has been introduced through https://github.com/adoptium/ci-jenkins-pipelines/pull/229 to allow us to lock the AQAvit testing to the correct consistent version for the JDK under test and the naming convention is described in https://github.com/adoptium/aqa-tests/issues/2776

doc: Add aqaReference pipeline parameter requirement to RELEASING.md

---

build-farm/make-adopt-build-farm.sh
build-farm/set-platform-specific-configurations.sh
sbin/build.sh
sbin/prepareWorkspace.sh
security/mk-cacerts.sh

This PR enables "reproducible build" support for jdk-19+ builds by enabling:
- --with-source-date option enables openjdk make reproducible build option
- --with-build-user=adoptium ensure determinstic jvm build user
- --with-cacerts option to pass the mozilla cacerts folder into the openjdk build keystore tool which is determinsitic

Enable jdk-19+ reproducible build options

---

build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

I don't believe this will adversely affect anyone any more, so hard coding this in light of the changes made in https://github.com/adoptium/temurin-build/pull/2818 so that the API call does not try to use `temurin`
Alternate solution would be to use a bash specific construct of `${VARIANT/temurin/hotspot}`
(Causes JDK19 to fail to build as it won't be able to download a boot JDK and we don't install that one via the playbooks yet as it's not a GA level)

When auto-downloading boot JDK, default to hotspot (Don't use temurin in API)

---

test/functional/buildAndPackage/src/net/adoptium/test/FeatureTests.java

Shenandoah and ZGC are available for jdk17+ PPC64LE, ZGC on mac-aarch64

---

build-farm/platform-specific-configurations/linux.sh

May add this into the playbooks in future, but for now I'm going to download dynamically during the build. Required to execute `constgen`. Should fix https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv64-openj9/

Add qemu into build process for OpenJ9 RISC-V cross-compiles

---

build-farm/platform-specific-configurations/linux.sh

We enabled GCC10 for JDK18+ at https://github.com/adoptium/temurin-build/pull/2824.
This PR switches JDK17 as well as per [the original request](https://github.com/adoptium/temurin-build/pull/2824) and keeps us in line with Oracle (See mailing list) We held back on changing this for 17 previously because we were too close to the start of the January release cycle.
Adding this in ASAP will allow us to verify that there are no regressions well in advance of the April release of 17.0.3

Switch JDK17 to GCC10 as well as JDK18+

---

sbin/build.sh

Currently has `JVM_VARIANT="Temurin"` which is not what we want.
Fixes https://github.com/adoptium/temurin-build/issues/2862

`release` file in root of JDK8 tarball should have `JVM_VARIANT=Hotspot`

---

cyclonedx-lib/build.xml
cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
sbin/build.sh

Integrate the new CycloneDX Java API plugin into the build-scripts bill of materials generation.
This PR creates the SBOM file: ${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[TARGET_DIR]}/metadata/sbom.json
A 2nd PR for ci-jenkins-pipelines will create a new Artifact from sbom.json.

Integrate CycloneDX SBOM API into build.sh

---

sbin/build.sh
sbin/common/common.sh

Check archive result if targetfile is created and empty, otherwise exit 1 from createArchive()
Ref: https://github.com/adoptium/temurin-build/issues/2261

Fix: fail build.sh if archive not produced by createArchive()

---

sbin/build.sh

- to handle version in format e.g 11.0.14.10.0-GA
- keep smae logic in jdk8 without change
Ref: https://github.com/adoptium/temurin-build/issues/2889

fix: Dragonwell builds fail due to incorrect version

---

build-farm/make-adopt-build-farm.sh

mac was not being auto-detected correctly. Also wrong variable was used for the solaris detection, so I'm fixing that here too.

Auto-detect TARGET_OS for mac in make-adopt-build-farm.sh

---

build-farm/platform-specific-configurations/mac.sh

It probably makes sense to use full Xcode for JDK11 on both MacOS architectures, but I was definitely getting build failures when using just the command line tools on aarch64.
Will likely be superceded by the changes in https://github.com/adoptium/temurin-build/pull/2876 at some point.

Use full xcode for MacOS/aarch64 JDK11

---

build-farm/platform-specific-configurations/mac.sh

ref https://github.com/adoptium/infrastructure/pull/2498
MacOS bootjdks install into either `/Library/Java/JavaVirtualMachines/temurin-*` or  `/Library/Java/JavaVirtualMachines/adoptopenjdk-*`. After the linked pr is merged, the build scripts can instead look into `/Library/Java/JavaVirtualMachines/jdk-* ` which will be a symlink to either `temurin-*` or `adoptopenjdk-*`
Merge after release, and after the linked infra pr is merged and after such changes have been made to build and test MacOS machines

Appropriately name MacOS bootjdk directories

---

build-farm/platform-specific-configurations/solaris.sh

Fixes https://github.com/adoptium/temurin-build/issues/2894. Supercedes https://github.com/adoptium/ci-jenkins-pipelines/pull/283
I believe this will set `BUILD_ARGS` to the right thing in the pipelines - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/795/ seems to be running happily with this in place:
```
"BUILD_ARGS": "--make-args SHELL=/bin/bash",
```

Force make to use SHELL=/bin/bash on Solaris

---

security/mk-cacerts.sh

Fixes https://github.com/adoptium/temurin-build/issues/2902

mk-cacerts: Use more portable syntax for converting to lower case

---

build-farm/platform-specific-configurations/aix.sh

Future builds of jdk11u will require xlc 16.1. This PR updates the version used to build those jdk versions.
https://github.com/adoptium/temurin-build/issues/2882
DCO 1.1 Signed-off-by: Tyler Steele

Update compiler version for jdk11+ on AIX.

---

build-farm/platform-specific-configurations/windows.sh

Windows build fixed to be able to compile
openssl on the fly rather than using system
pre-compiled binaries.

OpenJ9: Change Windows to OpenSSL fetched

---

build-farm/platform-specific-configurations/linux.sh

I'm not really comfortable with downloading a boot JDK from a third party site during the build process for the boot JDK but since the two platforms it affects are built by us in disposable docker containers I'm less concerned... This change leaves the door open for an option of adding it to the playbooks too

Force use of Dragonwell 8 boot JDK for building itself

---

sbin/prepareWorkspace.sh

See also eclipse-openj9/openj9#14994.

Update OpenJ9 builds to use OpenSSL 1.1.1o

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/linux.sh
sbin/prepareWorkspace.sh

Dragonwell 8 is a monorepo now, and get_source is removed.

Remove get_source_dragonwell.sh, Dragonwell8 is monorepo

---

sbin/common/config_init.sh

Reverts adoptium/temurin-build#2926
Since we still have problem on Windows and AIX, till they are fixed, we cannot turn this as default feature, thus revert commit and fall back to add flag in [config groovy files ](https://github.com/adoptium/ci-jenkins-pipelines/pull/297)

Revert "feat: enable SBOM as default behavior"

---

build-farm/platform-specific-configurations/linux.sh

#2824 enabled building with gcc10, but with an exception for openj9. eclipse-openj9/openj9#14219 has been fixed so that exception is no longer necessary.
Also fix inconsistent check for openj9 variant.
In draft mode until eclipse/omr#6301 promotes to openj9.

Remove exception for avoiding use of gcc10 with openj9

---

cyclonedx-lib/build.xml
cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
sbin/build.sh

Fix:
- Ant does not recognize cygwin path, add logic check if it is running on Windows
https://ant.apache.org/manual/platform.html
running test: https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-temurin/82/console with debug info enabled
- uplift cyclondx-core and jackson SDK to latest version
- uplift to new schema to use FRAMEWORK than APPLICATION
- update to use eclipse than adoptium as vendor
Test on
[non-win](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-temurin/168/)   => works
[win](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x86-32-temurin/58/console) => failed in build jdk because the …

fix: ant build Sbom on Windows

---

sbin/build.sh

fix: missing JAVA_HOME set for Solaris build when call sbom

---

sbin/common/config_init.sh

This reverts commit 8d87dd642382b72337ee48e6b74c98cf1f234c89.
- windows is working with --create-sbom
- re-enable default to "true" again
Ref: https://github.com/adoptium/temurin-build/issues/2900

Revert "Revert "feat: enable SBOM as default behavior"

---

sbin/build.sh

- fix check on file not dir
- fix path, cannot be absolute
- rename variable to be more meaningful
-
test run log: (without stripping debug)
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-temurin/176/console
```
18:13:34  DEBUG OpenJDK SBOM file is ../../../../../target/metadata/sbom.json.
18:13:34  -rw-r--r-- 1 jenkins jenkins 6016 May 26 16:02 ../../../../../target/metadata/sbom.json
18:13:34  DEBUG content /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-temurin/workspace
18:13:34  total 24
18:13:34  drwxr-xr-x  3 jenkins jenkins 4096 May 26 16:02 target
18:13:34  drwxr-xr-x  4 jenkins jenkins 4096 May 26 15:58 build
18:13:34  drwxr-xr-x  2 jenkins jenkins 4096 May 26 15:57 config
18:13:34  drwxr-xr-x  2 jenkins jenkins 4096 May 26 15:55 …
```

fix: sbom.json archive

---

sbin/build.sh

This reverts part of https://github.com/adoptium/temurin-build/pull/635 which is inappropriate since https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/568.

Revert use of '--with-add-source-root' for openj9/jdk8

---

build-farm/sign-releases.sh
sbin/build.sh
sign.sh

This PR fixes: https://github.com/adoptium/temurin-build/issues/2952
Fixes:
1. Modified SBOM archiving to archive plain sbom.json as a artifact rather than tar.gz
2. Update sign-release.sh to not to try signing an sbom archive
3. Add set -eu to sign.sh so exceptions/failures are not ignored. Currently a failure to sign an executeable will be ignored.
4. Update sign.sh to check if not files found to sign, preventing http 500 failure on Mac.

Update sbom archiving for just sbom.json and fix sign_release sbom and exception handling

---

.github/workflows/build.yml

- we set ANT_HOME in ansible for VM but not in GH action, we need to append it as env variable to GITHUB_ENV (which is a file , sourced by GH step)
- windows-2019 pre-instealld ant, no need install again
- after temurin-build we need to reset ANT_HOME back to its old value which is  used in run-aqa to run "ant" also build_tests.xml need it to find resource
test run log:
https://github.com/adoptium/temurin-build/runs/6635265682?check_suite_focus=true

fix: add ANT_HOME to PATH and export

---

sbin/build.sh

JDK_BOOT_DIR variable is not present in sbin/build.sh shell as it was only set in the make-adopt-build-farm.sh shell.
The BUILD_CONFIG[JDK_BOOT_DIR] variable contains the value passed from the make-adopt-build-farm.sh shell.

Correct CycloneDX JDK_BOOT_DIR variable reference for JAVA_HOME

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/2949
Ensures Mac Plist change to Eclipse Temurin is only done for jdk8, and logic is correctly checked for jdk11+.

Ensure Mac Plist update to Temurin is performed for only jdk8

---

build-farm/platform-specific-configurations/linux.sh

We haven't got GCC11 on all the build systems yet, but this will allow the builds to start using it for JDK19+ as and when they are deployed.
@andrew-m-leonard I don't expect this wil have any impact on the reproducible build stuff, but if you want to check it LMK

Use GCC11.2 for JDK19 where available

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/windows.sh
sbin/build.sh

Switches the JDK8u x64 build to use VS2017 (same as the version tested in the OpenJDK codebase https://github.com/adoptium/jdk8u/blob/master/.github/workflows/submit.yml#L864-L876)
Also bumps freetype to 2.8.1 (required to be built with VS2017)

windows: bump JDK8u x64 build to use VS2017

---

build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

api.adoptium.net does [auto mapping ](https://github.com/adoptium/api.adoptium.net/blob/2dfab50a252bccf757b11c5997f79b74dfb118f8/adoptium-models-parent/adoptium-api-v3-adoptium-specific-models/src/main/kotlin/net/adoptium/api/v3/models/AdoptiumVendor.kt#L19) so it is not broken for us

fix: update vendor from adoptium to eclipse when use Api service as default

---

sbin/build.sh

The x86 Windows JDK8 build is currently broken since my Freetype PR was merged. This PR removes the patch for x86 builds. This is related to the visual studio version still being 2013 for Windows x86.

windows: only apply JDK8 freetype patch on x64

---

sbin/build.sh

from conversation: https://adoptium.slack.com/archives/C09NW3L2J/p1655804491202619?thread_ts=1655802669.491939&cid=C09NW3L2J
we only store os kernal which does not help much for alpine, centos, rhel etc 
Ref: https://github.com/adoptium/temurin-build/issues/2983

fix: use OS_FULL_VERSION than OS_KERNEL in sbom to include more

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/windows.sh

The Visual Studio 2019 backport is now complete for JDK11 which means we should be able to start building using VS2019

build: switch Windows JDK11 builds to use VS2019

---

sbin/build.sh

- e.g freemarker is used by openj9 but not temurin

feat: always add sbom component, for those not have values set to "N.A"

---

sbin/build.sh

When new versions are branched, eg.jdk-18.0.2 from jdk-18.0.1 a "0" build tag is tagged at the commit prior to the new branch commit, and thus prior any changes or proper builds for that new version. Version jdk-18.0.1 may still be doing builds or .1 builds after that. Not until the make/conf/version-numbers.conf is changed and a jdk-18.0.2+1 build is tagged is that considered the latest.
Fixes: https://github.com/adoptium/temurin-build/issues/2998

Do not match jdk build '0' new version branching tags

---

cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
sbin/build.sh
sbin/common/sbom.sh
sbin/sbom.sh

- create sbom.json, moved related functions away from build.sh
- make createsbom function purely create sbom, not adding component
- add --addMetadataComponent
- add --addMetadatatool
- format
Fixes: https://github.com/adoptium/temurin-build/issues/3011

fix invalid sbom.json 

---

build-farm/platform-specific-configurations/aix.sh

We are still seeing problems with errors in /tmp/ on AIX systems (Specifically build-osuosl-aix71*1)
This will clear out all such entries on AIX when running under jenkins (username=jenkins and `WORKSPACE` is defined).
Broadly copies what is in the crontab on the machines
Ref: https://github.com/adoptium/infrastructure/issues/929

aix: Remove /tmp/sh-np.* before building

---

build-farm/platform-specific-configurations/linux.sh
build-farm/set-platform-specific-configurations.sh
sbin/build.sh

In our current build, after add "--disable-ccache" some jobs showing:
`Completed configuring the version string parameter, config args are now:  --with-vendor-name="Eclipse Adoptium" --with-vendor-url=https://adoptium.net/ --with-vendor-bug-url=https://github.com/adoptium/adoptium-support/issues --with-vendor-vm-bug-url=https://github.com/adoptium/adoptium-support/issues --without-version-opt --without-version-pre --with-version-build=7 --with-vendor-version-string=Temurin-17.0.4+7 --with-boot-jdk=/usr/lib/jvm/jdk-16 --with-debug-level=release --with-native-debug-symbols=external --with-jvm-variants=server,client --with-cacerts-file=/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-arm-temurin/sbin/../security/cacerts --with-jobs=80  --disable-warnings-as-errors …

fix: do not have both --enable-ccache and --disable-ccache set and only RELEASE type has --disable-ccache

---

sbin/build.sh

This "precaution" `if` has been there since it was authored.
I can't understand why it is there. The code seems to work
without it. It seems to unintentionally be moving those
values for every non-milestone release. That is, the code
works for milestones only but for releases it moves minor
to tags.
eg. 0.29.0-m1 becomes 0, 29, 0, m1 which is correct
but 0.29.0 becomes 0, 0, 0, 29 which is incorrect
Related #2077

Remove check that moves minor to tags in variant JSON

---

.github/workflows/ca-cert-updater.yml

I can't be the only one getting these emails frequently. This PR prevents this

prevent CA cert updater from running on forks

---

build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh

I've had issues on one of my 4GB aarch64 systems with two `ld` processes being started to perform linking of the final `libjvm` in parallel which use over 1.5Gb each and ultimately result in the system going heavily into swap and not completing in a reasonable amount of time. This change - which will only take effect on low memory systems - will use the option ([man page here](https://sourceware.org/binutils/docs-2.38/ld.html)) which will reduce the memory usage of the `ld` command at the expense of some performance (which is why I am not enabling it by default)
[Side notes: https://wiki.debian.org/ReduceBuildMemoryOverhead mentions other `ld` options that might reduce memory further, but the one in this PR should have enough of an effect]

reduce RAM usage during build on Linux systems with <4GB

---

RELEASING.md

docs: revert back to only use _adopt as git tag suffix

---

sbin/build.sh
sbin/prepareWorkspace.sh
security/mk-cacerts.sh

Fixes https://github.com/adoptium/adoptium-support/issues/540
The nokeystore logic for reproducible cacerts creation had a uniqueness bug in the cert file renaming
for input to openjdk GenerateCacerts tool. The logic was removing digits from the alias which then resulted in
some aliases mapping to the same filename.
Corrected the alias file name uniqueness and updated logic to mirror both generation methods, and also verify
a cert filename clash does not occur.
Also corrected an existing bug with the detection of duplicate aliases, which was actually causing
certificate: "QuoVadis Root CA 3" to be missing as it is a substring of "QuoVadis Root CA 3 G3"
Corrected the invocation of mk-cacerts.sh with --nokeystore to be jdk-17+. --with-cacerts-src is backported to jdk17,18,19
Signed-off-by: …

Correct mk-cacerts.sh nokeystore alias file renaming to be unique

---

security/mk-ca-bundle.pl
security/mk-cacerts.sh

- if enable --nokeysotre(reproducible build): current *.cert file nr. == return from perl - duplicated
- if not set --nokeysotre: keytool -list == return from perl - duplicated
Fixes: https://github.com/adoptium/temurin-build/issues/3034

feat: add post check for imported ca certs number

---

sbin/build.sh

The patch is only applicable for freetype version 2.8.1 and OpenJ9 doesn't need (or want) that patch applied (for any version).

Don't patch freetype for OpenJ9

---

test/functional/buildAndPackage/src/net/adoptium/test/JdkVersion.java
test/functional/buildAndPackage/src/net/adoptium/test/VerifyCACertsTest.java
test/functional/buildAndPackage/testng.xml

- add new smoketest for cacerts into CommonFeatureTests
- only enable matching cacerts number at the moment
Positive case: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19/job/jdk19-mac-x64-temurin_SmokeTests/17/console
Negative case (when we had problem with cacerts unfixed):  https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-arm-temurin_SmokeTests/37/console
Ref test case from [jdk19](https://github.com/adoptium/jdk19/blob/master/test/jdk/sun/security/lib/cacerts/VerifyCACerts.java)
Ref: https://github.com/adoptium/temurin-build/issues/3034

feat: add smoketest for cacerts(check alias number)

---

sbin/build.sh
sbin/prepareWorkspace.sh

Ever since https://github.com/adoptium/temurin-build/pull/421/ was merged, we no longer use the downloaded version of freetype for JDK11+ (instead opting for the bundled version). This PR completely removes the unnecessary download of the freetype tarball.

freetype: skip unnecessary download on JDK11+

---

sbin/build.sh

Due to upstream change [make/hotspot/lib/CompileJvm.gmk](https://github.com/adoptium/jdk/commit/b4ab5fe1daf22a543e1bd973bcd34322360054b4#diff-d13a7651e18897b90a4f95c5d6dbdca71dec523606997303d29d467e4f6fe599) MacOS non-Release builds will fail
the notarization as the libjvm.dylib gets rebuilt due to a change in the HOTSPOT_BUILD_TIME on the 2nd pass make.
This PR ensures --with-hotspot-build-time is specified for all jdk-17+ non-release type reproducible builds.
Fixes: https://github.com/adoptium/temurin-build/issues/3025#issuecomment-1182454454

Set configure arg --with-hotspot-build-time for reproducible jdk17+ non-release builds

---

sbin/build.sh
sbin/common/config_init.sh

- disable create sbom by default (for build without using ci-jenkins-pipeline)
- enable our CI build from https://github.com/adoptium/ci-jenkins-pipelines/pull/369 
Ref: https://github.com/adoptium/temurin-build/issues/3047

revert: back to "false" for BUILD_CONFIG[CREATE_SBOM]

---

RELEASING.md

.sig regexp is missing from the RELEASING.md doc, causing releases to go out without .sig files

Docs: Add .sig regexp to RELEASING.md doc

---

build-farm/make-adopt-build-farm.sh

- to enable reproducible build for jdk17 cannot use jdk16 without -date support
- this will make jdk17 use jdk17 as boot
- jdk18 use jdk17 as boot
- jdk19 use jdk19 as boot etc
Ref: https://github.com/adoptium/temurin-build/issues/3057

feat: update to use jdk17 as boot jdk for jdk17 build to support reproducible builds

---

build-farm/platform-specific-configurations/windows.sh

These are the options used to build the last Semeru release (0.33 / jdk8u345).

Update OpenJ9 jdk8 builds to use freetype 2.9.1 and VS2017

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3048
We should possible look at the use of `OPENJDK_FEATURE_NUMBER` vs `OPENJDK_CORE_VERSION` in `build.sh` more in the future, but while this is inconsistent with most of the other comparisons in the script that use the latter, the former allows us to do the `-ge` comparison as it's purely numeric. The alternative with `OPENJDK_CORE_VERSION` would be to use an explicit list of versions that are not allowed.

Fix java version logic for repro params so it does not use undefined variable

---

sbin/build.sh

See https://github.com/microsoft/openjdk-aarch64#building-jdk-11 for context.
This will fix the failing windows aarch64 jdk11 builds

add jdk11u fixpath path for windows aarch64

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3075
While most timestamps in the builds are neutralised when some of the files are produced there are some files which have timestamps that are affected by the time zone setting, so if you build on a machine in a different time zone then the builds are not identical. I've seen this on xLinux (Timestamps within the `ct.sym` zipfile are different) as well as in the issue reference above between two Linux/s390x systems. This fix will set `TZ=UTC` alongside the other options when the reproducible builds are enabled.

Force TZ=UTC for reproducible release builds

---

build-farm/platform-specific-configurations/windows.sh

This change is already used for OpenJ9/Semeru 11.0.17 builds via https://github.com/ibmruntimes/temurin-build/pull/25
FYI OpenJ9 also needed this OpenJDK change https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/574 related to using VS2019, to include vcruntime140_1.dll into the build. Perhaps Temurin would benefit from the same.

Compile OpenJ9 Windows jdk11 with VS2019

---

RELEASING.md

For review: https://github.com/zdtsw/temurin-build/blob/wenzhou/docs3/RELEASING.md#steps-for-every-version (4)
updated some parts for the input values to build openjdkX-pipeline for release

docs: update release step options

---

configureBuild.sh

Repository was using an incorrect name (Still referencing adoptium rather than openjdk)

hotspot: use correct repo for non-temurin aarch32 builds

---

.github/workflows/build.yml

dont waste resource test jdk18

chore: remove jdk18 in GH action test

---

sbin/prepareWorkspace.sh

See also https://github.com/eclipse-openj9/openj9/pull/16236.

Update openssl to version 1.1.1s for OpenJ9

---

.github/ISSUE_TEMPLATE/documentation.md

1. Change the "about" field to "Request for updates to the Temurin build documentation".
2. Add a comma after "documented".
3. Add a full stop after "like to see in the documentation" before the asterisks.
Fixes: #3123

Correct documentation.md #3123

---

build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

That is, instead using of an external version.
This will be required once https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/631 is merged.

Build openj9 with the version of freetype bundled with jdk8

---

sbin/build.sh
sbin/common/config_init.sh

Add --build-reproducible-date=ISO8601_date build build arg, which sets the build date & time used in the build
so for nightly builds the pre/post version output date, and all build dates are reproducible.
A follow on PR will update Temurin nightly builds to use this along with a "dual-build" with the same nightly "date", then invoking the reproducible comparison job, publishing the reproducible % to the metadata and subsequent publish to website... (ok, maybe more than one PR to follow!)

Add --build-reproducible-date=ISO8601_date build option to allow reproducible nightly builds

---

build-farm/platform-specific-configurations/windows.sh
sbin/build.sh

The patches are no longer required now that https://github.com/openjdk/jdk11u/commit/40f4fc2da8532252a1660c7f082eb19046f4bc70 has been merged

remove windows aarch64 fixpath patch for JDK11u

---

build-farm/platform-specific-configurations/linux.sh

OpenJ9 get_source.sh will fetch the latest OpenSSL version
during the build. We should compile against that version
rather than 1.0.2r on the system.
Related AdoptOpenJDK/openjdk-infrastructure#2084

OpenJ9 linux always configure --with-openssl=fetched

---

.github/workflows/ossf-scorecard.yml

temurin-build `main` branch has the legacy name `master`. Update the filter to run there.

Update branch name

---

.github/workflows/ca-cert-updater.yml

fixes the CACert updater that has been broken for some time.

revert broken GitHub action update

---

.github/workflows/build.yml

Fix: https://github.com/adoptium/temurin-build/issues/3206
test result with only windows enabled https://github.com/adoptium/temurin-build/actions/runs/3891218116/jobs/6641190084 
final commit is squashed commits and enabled all platforms

debug: windows GH action failure

---

.github/workflows/build.yml
test/functional/buildAndPackage/src/net/adoptium/test/VerifyCACertsTest.java

Fix: https://github.com/adoptium/temurin-build/issues/3212
Test locally with 
```
./mk-ca-bundle.pl -n -d
./mk-cacerts.sh 
```
got` Number of certs processed: 139
`which matches smoketest result 139 
some more discussion: https://adoptium.slack.com/archives/C09NW3L2J/p1673446583214579

test: fix smoke cacert test expected number 

---

configureBuild.sh

As per https://github.com/adoptium/jdk8u/issues/11, we are splitting the JDK8u Alpine specific patches into their own separate mirror to keep our mainline jdk8u repo as clean as possible.

alpine: switch jdk8u to build from other fork

---

test/functional/buildAndPackage/src/net/adoptium/test/BundledFreetypeTest.java

- Fix Smoke Test openj9 AIX libfreetype error due to jdk 8 aix freetype update
Related Issue: ibm_git/runtimes/backlog/issues/766
Signed-off-by: LongyuZhang <longyu.zhang@ibm.com>

Fix Smoke Test openj9 AIX libfreetype error

---

.github/workflows/code-freeze.yml

This PR enables the Code Freeze bot on release branches such as `v2023.01`. A recent PMC conversation suggested that this would make sense to add.

Run code freeze bots on pull requests made to release branches

---

cyclonedx-lib/build.xml

Backout building of openkeystore, as breaks build due to jdk dependency.

Dont build openkeystore as breaks builds due to jdk requirement

---

RELEASING.md

Add steps to post to our mirror of the github releases as a backup so we have all of our released artefacts in multiple locations.

doc: add EclipseMirror to the end-of-release steps

---

.github/workflows/testsbom.yml
cyclonedx-lib/build.xml

Bump the cyclone DX core java library dependencies to 7.3.2 and associated dependency versions.

Move cyclonedx java library dependencies to 7.3.2 dep versions

---

test/functional/buildAndPackage/src/net/adoptium/test/FeatureTests.java

This test should be skipped on Aarch64 (like it is on x64)

skip ZGC test on Windows aarch64

---

test/functional/buildAndPackage/src/net/adoptium/test/FeatureTests.java

had a silly moment
Test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk20/job/jdk20-evaluation-windows-aarch64-temurin_SmokeTests/8/

fix broken logic in smoke test

---

sbin/build.sh

Ensure --with-vendor-url  is set to a value.
Also disabled shellcheck globbing SC2086, as many warnings and most needed.
Fixes: https://github.com/adoptium/temurin-build/issues/3283

Ensure --with-vendor-url is not blank, so plain hotspot can be built

---

sbin/prepareWorkspace.sh

`grep -E` is not supported by the default Solaris grep, and `egrep` should offer equivalent functionality everywhere.
(NOTE to committers: This does NOT need to be merged before the current release so it should wait until afterwards, however reviews are welcome)
Check in VPC at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1414/ but we should probably glance at the output and verify that this hasn't caused any functional changes.
Fixes this in the build logs:
```
19:06:03  grep: illegal option -- E
```

Replace 'grep -E' with 'egrep' for Solaris compatibility

---

configureBuild.sh

The backports of Linux/RISC-V to JDK 8, 11, and 17 are in progress. To get a head's start on building and testing these backports, we want to special-case these repositories.

Add configuration for jdk8u, jdk11u, and jdk17u on riscv64

---

tooling/linux_repro_build_compare.sh
tooling/linux_repro_compare.sh
tooling/linux_repro_process.sh
tooling/windows_build_as_temurin.sh
tooling/windows_repro_compare.sh
tooling/windows_repro_process.sh

A handful of reproducible build helper scripts, for:
- linux_repro_build_compare.sh : Build the selected JDK by SBOM metadata, and perform compare
- linux_repro_compare.sh : Compares two linux builds
- linux_repro_process.sh : Neutrallzing script for pre-processing a linux JDK for compare
- windows_repro_compare.sh : Compares two windows builds
- windows_repro_process.sh : Windows JDK binary Signature neutrallzing script for pre-processing a Windows JDK for compare
- windows_build_as_temurin.sh : Example script of building a trusted upstream openjdk as Temurin for the purpose of trusted comparison

Reproducible build comparison tooling

---

sbin/build.sh

Recent reproducible build/SBOM [change](https://github.com/adoptium/temurin-build/pull/3313) broke jdk8 Solaris due to date tool formating:
```
14:29:37  date: illegal option -- j
14:29:37  usage:	date [-u] mmddHHMM[[cc]yy][.SS]
14:29:37  	date [-u] [+format]
14:29:37  	date -a [-]sss[.fff]
```
Changed date formating to use simple bash cmds.
Tests on Solaris:
Current date:
```
-bash-3.2$ date -u +"%Y-%m-%d %H:%M:%S"
2023-04-13 15:37:02
```
Conversion:
```
-bash-3.2$ echo "2023-04-13 15:31:01" | cut -d":" -f1-2 | tr -d "\-: "
202304131531
```
Test Solaris non-release build to show timestamp: https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk8u/job/jdk8u-release-solaris-x64-temurin/6/console
```
user-release-suffix=202304131550
```

Make build timestamp changes work on Solaris

---

sbin/build.sh

v2023.04.01  Cherry pick: https://github.com/adoptium/temurin-build/commit/0dbabd36f7ce0418b168d294a59e557ef2aa5776

Make build timestamp changes work on Solaris (#3324)

---

build-farm/platform-specific-configurations/windows.sh
sbin/build.sh
sbin/prepareWorkspace.sh

Fixes https://github.com/adoptium/temurin-build/issues/3252
Resolves issue with testing https://github.com/adoptium/infrastructure/pull/3014
Other option is to switch the version of freemarker required, although this should not be necessary with the new build process used by default for OpenJ9 (Although has riscv64 been switched over yet?)

Remove freemarker options from OpenJ9 builds

---

sbin/build.sh
sbin/common/common.sh

Fixes https://github.com/adoptium/temurin-build/issues/3270
Sets --with-version-opt for LTS release builds jdk-21+

Set --with-version-opt=LTS for LTS versions from jdk-21

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3341
by making the internal binary text for the "build user" unique.

Make embedded jvm internal build user name unique

---

makejdk-any-platform.1
sbin/common/config_init.sh

Fixes https://github.com/adoptium/temurin-build/issues/3343
Change the ERROR exit policing of the vendor name, to just a WARNING.
And allow setting the vendor-url, vendor-bug-url, vendor-vm-bug-url.

Enable build scripts support for user vendor strings

---

tooling/linux_repro_build_compare.sh

Script references old adoptopenjdk.net endpoint, updated to adoptium.net
Also updated to support jdk(tip) builds, and bash tweaks to work on RHEL 7.

Update linux_repro_build_compare for adoptium.net

---

build-farm/platform-specific-configurations/windows.sh

OpenJ9 was missing the change to disable ccache for all versions.
Issue https://github.com/eclipse-openj9/openj9/issues/16701

Build OpenJ9 Windows jdk19+ with VS2022, and disable ccache

---

build-farm/platform-specific-configurations/linux.sh

Part of https://github.com/adoptium/temurin-build/issues/3096 - we should be verifing the GPG signatures when downloading a boot JDK during the build.
I've also taken this opportunity to split out a couple of large sections into functions which I've wanted to do for some time as it'll make the script easier to read and remove a lot of the stuff that is mostly not important when reading the file from the main flow, however it will mess with the `blame` history of the individual lines in there...
- `locateDragonwell8BootJDK`
- `setCrossCompilerEnvironment` (For RISC-V cross compilation)
- `downloadBootJDK` (The function I'm modifying here)
The downloadBootJDK additions are all of the lines relating to `gpg` and I've split the `curl | tar xpfz` pipe up so it does the curl download, then the …

linux.sh: Pull some parts into functions and do GPG signature checks on boot JDK downloads

---

build-farm/platform-specific-configurations/linux.sh
sbin/prepareWorkspace.sh

Two fixes for the code merged in https://github.com/adoptium/temurin-build/pull/3350 yesterday:
- The check for a valid download of the GA boot JDK was incorrect (Checking the curl return code is not a valid way to do it as curl will download a message with the error code and return success)
- On Alpine if the current directory used when running the check is more than 83 characters long then the receiving of the keys from the keyserver will fail, so I'm going to use the value of `WORKSPACE` instead of 
For future reference and search fodder:
Failure on s390x/arm (Platforms where we have no GA build for JDK20 so this shows up on JDK21 builds) because it tries to download the signature of something that isn't there.
```
09:23:15  gpg: can't open `bootjdk.tar.gz.sig': No such file or …
```

Fix GPG checking of boot JDK for EA downloads and Alpine

---

RELEASING.md

Once a new series of builds have been released, it is important to update the api to ensure that the data from the builds of the next new java major version can be accurately reported on.
This change documents when+how to carry out this change, similar to the example [here](https://github.com/adoptium/api.adoptium.net/pull/578/files).

Update api after build release

---

sbin/prepareWorkspace.sh

These two operating systems do not require ALSA support so we should stop downloading it during the build.
Also fixes https://github.com/adoptium/temurin-build/issues/3357
Approvals welcome but this is in draft until I do some more verification.

Stop downloading ALSA on AIX/Solaris during build

---

cyclonedx-lib/build.xml
cyclonedx-lib/sign_src/TemurinSignSBOM.java

openkeystore updates to change their jar name
and fix TemurinSignSBOM.java incorrect exception handling
Fixes https://github.com/adoptium/temurin-build/issues/3364

Fix TemurinSignSBOM build failures due to upstream pki jar changes

---

RELEASING.md

Update the example PR for post-release version retiring, noting it includes the evaluation pipeline.

Update version retire post-release section

---

sbin/build.sh
sbin/prepareWorkspace.sh

This is causing failures in the evaluation pipelines as per https://github.com/adoptium/temurin-build/issues/3378.
Bizarrely it also seems user specific - if I test without this fix using the `jenkins` ID and my own user ID, even in a subdirectory outside `/home` (I tested with a long name under `/dev/shm`) it fails as jenkins, not as `sxa`. I have not yet explained this, but this fix appears to work ok.
Fixed build: https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk20u/job/jdk20u-evaluation-linux-riscv64-temurin/32/console

Use alternate path for GNUPGHOME when path length >83 characters

---

sbin/build.sh

Adding an equals sign that needs to be present to make this a valid argument.

Remove typo in aix cflags argument

---

configureBuild.sh
docker-build.sh
sbin/build.sh

Upstream OpenJDK changed what the static-libs image means. It includes a static version of libjvm.a with JDK 22+. Therefore, in order to get a version without libjvm.a, static-libs-graal-image target is being used instead.
Closes: #3339

Use updated static libs target

---

sign.sh

Fixes issue #3337 
Remove an unneeded trim string function from the timeserver parsing.

signing: Remove redundant trimming of timeserver string

---

security/mk-cacerts.sh

Add "-nameopt compat" option to the openssl command used to generate the ALIAS name, and remove any leading spaces.
Fixes: https://github.com/adoptium/temurin-build/issues/3396

Ensure deterministic cacert ALIAS name

---

sbin/build.sh

Ref https://github.com/adoptium/temurin-build/issues/3013#issuecomment-1600900780

Use bundled zlib instead of system for JDK21+

---

build-farm/platform-specific-configurations/linux.sh

The current mechanism used a different sorting order for the releases which meant that the GPG signature was not always the correct one for the downloaded boot JDK. This change ensures that it is the correct one which will match the file by taking the target tarball name and appending `.sig` to it.
Note: The correct solution to this is to pull the GPG signature from the API but that can be changed in a follow up PR as this is a fix for a build break in (at least) JDK22. There is also a potential race condition if the latest is updated while the boot JDK is being downloaded but again that will be fixed subsequently by pulling the signature file from the API.

Boot JDK download not always using the correct gpg signature file for verification

---

security/mk-cacerts.sh

Fixes https://github.com/adoptium/temurin-build/issues/3407
Use rfc2253 openssl Subject format, and only use widely recognised DNs to form the ALIAS.

Ensure deterministic cacert ALIAS name by only using recognised DNs

---

security/mk-cacerts.sh

Fixes https://github.com/adoptium/temurin-build/issues/3418
Solaris sed does not recognise [[:space:]]
and don't split on escaped commas (\\,) in the subject

Fix mk-cacerts.sh Solaris sed failure and escaped subject commas

---

cyclonedx-lib/build.xml

Currently, we check the integrity of the first file, and then ant uses the "yes this file matches the sha256 we have on file" boolean (checksum.match) for all subsequent files.
This results in all files being declared intact, even if they don't match the shas we have for them.
To fix this, I've declared checksum.match to be a strictly local property, so we actually check every file. I also did the same for "downloaded.file.checksum" just to be safe, and I updated the checksums for the files which no longer match their checksum.

Check file integrity for sbom dependencies after download

---

sign.sh

Fixes #3428 
Include a 20 retry for each library, when it fails to sign at the first attempt.

Improve Resilience Of Signing Checks For MacOS

---

tooling/repro_common.sh
tooling/repro_compare.sh

Just print a line when the files differ.  Does not output a list of changes, which can be piped to wc -l to count the number of file different.
Fix #3437 

Add -q option for diff

---

tooling/repro_common.sh

Part of https://github.com/adoptium/ci-jenkins-pipelines/issues/763

Update reproducible mac sign process

---

sbin/common/config_init.sh

at system level.
See issue: https://github.com/adoptium/infrastructure/issues/1544
The playbooks have prefixed system level PATH with /opt/freeware/bin. As that contains _coreutils_ certain AIX commands that _coreutils_ has repeatedly denied to add an **AIX** argument (noteablu `-p`) this setting breaks many AIX management commands - even standard boot (ie, called from rcboot) scripts.
In the issue noted above it is stated that this is needed so that `gmake` is found.
This PR points the config at the actual binary `/opt/freeware/bin/make_64` rather than depend on PATH and symbolic links to call the application.

aix: use fullpath for (g)make so PATH does not need to be modified 

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3445
Currently GLIBC is not being detected correctly.
Bootjdk is also missing the "+build".
- Fixed various grep/sed and invocation issues with getting GLIBC settings from features.h, and ensure works on all platforms.
- Updated to detect libc type from the build configuration, and then handle MUSL or GLIBC accordingly.
- Fixed Bootjdk detect to find btto jdk location from the build configuration, and then obtain the java.runtime.version.

Fix SBOM glibc, gcc and bootjdk settings

---

sbin/build.sh

Fixes an issue with Alpine/aarch64 build pipelines periodically hanging because it's trying to use a buggy JDK11

sbom: Use latest LTS JDK (17) for CycloneDX in preference to 8/11

---

test/functional/buildAndPackage/playlist.xml

- This test will test the jre jave version under jdk folder
- Only add for openj9 jdk8
Related Issue: ibm_git/infrastructure/issues/7925

Add JDK JRE version test for openj9 jdk8

---

test/functional/buildAndPackage/src/net/adoptium/test/FeatureTests.java

Linux-RISCV comes with support for Shenandoah and ZGC, and it's been merged in Java 19 and backported to Java 17 (starting with 17.0.9)
Fixes https://github.com/adoptium/temurin-build/issues/3454

smoketest: fix shenandoah and zgc feature check on linux-riscv

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/1951

Use bundled zlib on all versions, not just 21

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3464
Ensure SBOM artifact filename is correct on Windows builds.

Correct Windows SBOM artifact filename

---

cyclonedx-lib/build.xml
cyclonedx-lib/getDependencies

We've had a number of sbom-creation failures related to corrupted downloads from maven, so this stores the jars we need on Jenkins to avoid the maven issue.
Also includes the build.xml changes needed to fetch the jars from their new location.

Store sbom dependencies as jenkins artifacts

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3469
Ensure reproducible jdk-17 & jdk-19+ builds disable ccache, as it produces non-deterministic binaries: https://github.com/adoptium/temurin-build/issues/2973#issuecomment-1150295701
Also, in similar vane, for nightly builds the TZ needs to always be set to UTC: https://github.com/adoptium/temurin-build/issues/3075

Ensure CCache disabled for all reproducible jdk-17 & jdk-19+ builds

---

tooling/comparable_patch.sh
tooling/repro_common.sh

Some fixes for comparable build script on Windows
- signtool needs picking up from PATH as location depends on local MSVS dev environment
- expandJDK was leaving the original files after expanding
- SELF_CERT not needed as script creates its own now

Some fixes for Windows comparable build script

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/windows.sh

jdk-21 Windows will use a latest MS VS2022 Installation.
Test build: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21/job/jdk21-windows-x64-temurin/77/
Updated .github/workflows/build.yml to support windows-2022 and vs2022 building.

Upgrade jdk-21 Windows builds to use MS VS2022

---

sign.sh

Add retry logic to sign.sh for Windows, due to frequent failures recently with 502 returned from eclipse sign service.
Also since the script uses "set -eu", if curl returns say rc 502, which is happening frequently the script exits... so added if return code check.

Add Windows sign.sh retry and check curl rc

---

sbin/build.sh
sbin/prepareWorkspace.sh

Fixes https://github.com/adoptium/temurin-build/issues/3493
Determines what type of FreeType build it was "system" or "bundled", then look for the freetype.h from that freetype installation/openjdk bundle, to determine the FREETYPE_MAJOR,MINOR,PATCH

Ensure SBOM FreeType version is set correctly for system and bundled settings

---

build-farm/platform-specific-configurations/mac.sh

Moving the if statement outside of the jdk8 only code will ensure that the `--openjdk-target=x86_64-apple-darwin` config argument is added to the build command for all x64 jdks being built on arm64 
related https://github.com/adoptium/ci-jenkins-pipelines/pull/825 and https://github.com/adoptium/temurin-build/pull/3492

Add --openjdk-target=x86_64-apple-darwin argument when crosscompiling jdk11+ (Mac)

---

RELEASING.md

A few minor tweaks for clarity plus
- One change of path since the cask files are now in subdirectories
- Making it explicit in the visible doc (not just the hyperlink) that the LTS tasks are in a different repository
- A formatting change so that the linux section is not attached to the end of the macos one.

Updates to homebrew info in `RELEASING.md`

---

build-farm/platform-specific-configurations/mac.sh

jdk8 x64 mac won't build on a x64 node as it tries to force Xcode 11.7

jdk8 select Xcode-11.7 only when cross-compiling

---

tooling/release_download_test.sh
tooling/validateSBOMcontent.sh

Provides basic IVT testing (Download from the github repos) and validation of GPG and sha checksums as well as some validation of the downloaded SBOM to ensure it meets the CycloneDX requirements and has sane data in it as required to achieve SLSA Level 3 compliance.
This will be run via the jenkins job at https://ci.adoptium.net/job/build-scripts/job/release/job/download_and_sbom_validation - currently restricted access as per other tools in the `release` folder in jenkins.
Fixes https://github.com/adoptium/temurin-build/issues/3506 (that issue has some follow-on ideas for improvements too)
Also probably implements all of the initial reuqirements of https://github.com/adoptium/temurin-build/issues/3484 but there will likely be some additions to check the formal mac/windows signing so I …

add download and sbom verification scripts

---

sbin/prepareWorkspace.sh

ref https://github.com/adoptium/temurin-build/issues/3509#issuecomment-1795762701
if `./configure --help` is run before `bash autogen.sh` then we get
```
* module: psnames   (Postscript & Unicode Glyph name handling)
cd builds/unix; \
./configure 
/bin/sh: ./configure: No such file or directory
make: *** [setup] Error 127
```
and therefore `pngArg="--with-png=no"` does not get set
Running it after the autogen.sh script works
```
bash-3.2$ arch -x86_64 ./configure --help | grep with-png
--with-png=[yes|no|auto]
```
Needs testing in jenkins

Freetype: run bash autogen.sh before any ./configure commands

---

tooling/validateSBOMcontent.sh

Code was missing.
Also removed erroneous `kd` from the file

Fix verification of Visual Studio version on JDK11 and 17 for x64

---

sbin/prepareWorkspace.sh

Right now, about 10% of alpine linux x64 builds fail due to timeouts when requesting keys from the keyserver.
Example: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-alpine-linux-x64-temurin/277
The hope is that these timeouts are just temporary slowness due to server load, and that an extended timeout is the correct fix.
Test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-alpine-linux-x64-temurin/279/

Extending keyserver timeout to make alpine build more forgiving

---

RELEASING.md

Clarity for something that came up during the October 2023 release cycle.

doc: RELEASING.md: clarify first version for a point release

---

RELEASING.md

We do not currently have any documentation on the process for creating point releases in the adoptium mirror repositories. This adds in the information for a one off patch using a branch from a GA tag. A subsequent PR should create the equivalent doc for covering perpetual floating patches in the codebase.
Preview this change at https://github.com/sxa/temurin-build/blob/pointreleases1/RELEASING.md#summary-on-point-releases

doc: how to add a one-off patch to a point release

---

tooling/ReproducibleBuilds.MD
tooling/comparable_patch.sh

- Fixes to handle differences in various module-info.classes caused by JMOD signing
- Various small improvements and fixes
- Add "Comparable build" doc

Updates to comparable_patch.sh to support Windows vendor neutral comparison

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/mac.sh

Switching JDK11 to a pinned Xcode version rather than command line tools for consistency

pin JDK11 x64 build to XCode rather than commandline tools

---

build-farm/make-adopt-build-farm.sh

It doesn't work reliably in a docker image, so bootstrap with the (maintained) cross-built (for now) JDK21.0.1+12.1
Note this has been tested on multiple systems so is good to go live ASAP.

RISC-V: Avoid using JDK20 as boot JDK for JDK21 

---

sbin/build.sh

Fixes: https://github.com/adoptium/temurin-build/issues/3533 https://github.com/adoptium/temurin-build/issues/3534
Draft until it's been tested in a build flow but reviews welcome in the meantime :-)

sbom: Updates to include builder name and CI link

---

tooling/linux_repro_build_compare.sh

Parsing the parameter from sbom jason file instead of metadata file
Install jq.
Fix #3542

Update parsing build parameters and dependent tools

---

build-farm/platform-specific-configurations/linux.sh

Fixes #3547 
On Ubuntu 22.04 onwards, the object files required for autoconf/configure are in a new path, due to a change relating to multiarch implementations in Ubuntu.
The new path required to be added to LIBRARY_PATH is : /usr/lib/x86_64-linux-gnu
In order to get configure to work, the new path is appended to the LIBRARY_PATH.

Add required library for Configure to work on Ubuntu 22 onwards.

---

.github/workflows/build-autotriage.yml
tooling/build_autotriage/autotriage_regexes.sh
tooling/build_autotriage/build_autotriage.sh

This will create a weekly issue that contains a list of the latest failing Temurin builds at Adoptium.
This is the MVP for https://github.com/adoptium/temurin-build/issues/3521

Creating an automated build triage script

---

build-farm/platform-specific-configurations/linux.sh

Extends the fix for https://github.com/adoptium/temurin-build/issues/3547
On Ubuntu 22.04 onwards, the object files required for autoconf/configure are in a new path, due to a change relating to multiarch implementations in Ubuntu.
The new path required to be added to LIBRARY_PATH is : /usr/lib/x86_64-linux-gnu for x64
The new path required to be added to LIBRARY_PATH is : /usr/lib/aarch64-linux-gnu for arm64
In order to get configure to work, the new path is appended to the LIBRARY_PATH.

Add required library for Configure to work on Ubuntu 22 onwards. ( for both Arm64 & x64 )

---

.github/workflows/build.yml

The tests for macos-13 fail due to an error when setting up the smoke tests.
This seems to be a pretty common problem, e.g. as documented here:
https://github.com/actions/runner-images/issues/6817
Workaround seems to be to either ignore the error or remove the files before running brew if they are present.

Add workaround for brew update failure when running aqa smoke tests

---

cyclonedx-lib/build.xml
cyclonedx-lib/getDependencies

I've verified that the `ant build` phase works ok with this upgrade.
This is a prerequisite to using the code to generate the `Formulation` section of the CycloneDX SBoM
Ref: https://github.com/adoptium/temurin-build/pull/3538 https://github.com/adoptium/temurin-build/issues/3535

Update CycloneDX core jar to 8.0.3 for 1.5 spec

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/aix.sh
build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh
test/functional/buildAndPackage/src/net/adoptium/test/BundledFreetypeTest.java

Fixes https://github.com/adoptium/temurin-build/issues/3504
PMC confirmed moving Temurin jdk21u to using "bundled" FreeType, to provide "consistent" and "reproducible" builds with FreeType.

Default Temurin jdk-21+ to use bundled FreeType

---

cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
sbin/build.sh
sbin/common/common.sh
sbin/common/sbom.sh

This fixes #3528 .
This is a draft PR to gather feedback on the used approach.
Right now I split up the sbom generation into 2 steps:
- generation of the overall sbom as before
- finish the sbom by adding information for each generated artifact with their hashes
this has to be done after all archives have been created and moved to their final destination. We could also generate the sbom completely at the end, though I am not sure if no files should be modified in the target directory at all.

Add subject info the sbom

---

cyclonedx-lib/build.xml
cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
sbin/build.sh
sbin/common/sbom.sh

**Note to reviewers: please allow me to merge this when approved.**
This is a test of including the CycloneDX jars (downloaded during the build process) into the SBoM.
There are several JAR files associated with the CycloneDX tool and this only covers one of them so is a "discussion starter" (hence raising this as a draft) as to how we should move forward if we want to capture this information in the SBoM. Is this the right place for it to be stored? Do we definitely need it? Would we exclude it if we downloaded this onto the machines via the playbooks? If we capture all of the JAR SHAs then what should the format be?
```
{
"name" : "FreeMarker",
"version" : "N.A"
},
{
"name" : "CycloneDX core java JAR SHA",
"version" : "88193228f85a955127dc73e1c72efc9e08e18a01d227df47d0865dc20eceffd1"
}, …
```

Capture CycloneDX JAR SHAs in SBoM

---

build-farm/platform-specific-configurations/mac.sh

Also included some aggregate logic to avoid cflags overriding other cflags unintentionally
Fixes #3562 
JDK11 (includes fix) test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-aarch64-temurin/299/
JDK21 (excludes fix) test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-aarch64-temurin/69/

Exclude excessive build warnings on mac for jdk11 and jdk17

---

sbin/build.sh

Discussions starter: I personally find that the display of the SBoM content is overly verbose, and it typically makes it harder to find what I want in the log because I have to start at the bottom and scroll back to the "good bits". This PR suggests changing it so that it prints the location on the file system instead of printing it out. While this may be useful for debug/development I don't think it should print it by default. Bear in mind this content will also be archived afterwards along with the build itself.
In addition we print the metadata out in the pipelines job at https://github.com/adoptium/ci-jenkins-pipelines/blob/833a06de53ae21ffec043863600a88a5dbbb6529/pipelines/build/common/openjdk_build_pipeline.groovy#L1275 which should probably be removed too, but I'm looking for …

Stop showing full SBoM output in build log

---

build-farm/platform-specific-configurations/linux.sh

Given the rapid evolution of RISC-V, the newer the GCC toolchain, the better.

Enable GCC 10 for RISC-V

---

.github/workflows/build-autotriage.yml

ref https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
For the JasonEtco/create-an-issue action, the commit points to https://github.com/JasonEtco/create-an-issue/commit/e27dddc79c92bc6e4562f268fffa5ed752639abd. Bit odd looking, just alot of deleted files. 
And though the commit says `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`, this tag is the same as the [release v2.9.1](https://github.com/JasonEtco/create-an-issue/releases/tag/v2.9.1) which is verified

Replace build-autotriage action version number with SHA

---

RELEASING.md

Should point to https://ci.adoptium.net/job/build-scripts/job/utils/job/release-pipeline-generator/

Corrected the Release Pipeline Generator link in RELEASING.md

---

cyclonedx-lib/README.md

This is very much a quick and dirty starter readme, but it will hopefully help people who need to add in new functionality into our SBoMs by giving pointers to the appropriate sections of this repository, and also to the upstream CycloneDX documentation.

Add initial README.md for the cyclonedx-lib tooling

---

sbin/build.sh

Currently, when we build an x64 mac build on an arm64 machine, we put arm64 all over the place by mistake.
This change is to partially compensate for that mistake until such time as we can implement a comprehensive separation of build architecture and target architecture in our build scripts.

Temporarily patch architecture confusion when cross-compiling on mac

---

RELEASING.md

We have a mirror of the github artifacts on an Eclipse-owned server. This is a manual step once all of the artifacts are in GitHub.
Note that because of how the credentials for pushing to the Eclipse repository are managed, this step has to be done on the Temurin Compliance jenkins instance.

doc: Add EclipseMirror information to RELEASING.md

---

build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
sbin/prepareWorkspace.sh

It's an issue on linux-riscv64 valuation pipelines for jdk23. See https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk23/job/jdk23-evaluation-linux-riscv64-temurin/2/console for example.
Should normally fix https://github.com/adoptium/temurin-build/issues/3378

Update GNUPGHOME variable more broadly

---

build-farm/make-adopt-build-farm.sh

This will help log information that we can give to end users to tell how much space is required for builds, and also help with capacity planning on machines

Add amount of disk space used by build to the log

---

sbin/prepareWorkspace.sh

Fixes https://github.com/adoptium/temurin-build/issues/3642
Need to use /tmp for Alpine

Alpine linux ALSA gpg fails due to path length

---

sbin/prepareWorkspace.sh

When build using makejdk-any-platform.sh, OPERATING_SYSTEM is not set:
```
build/sbin/prepareWorkspace.sh: line 323: OPERATING_SYSTEM: unbound variable
```
Need to check for Alpine like it does in https://github.com/adoptium/temurin-build/blob/c78dc6cf2d1f1ddbe689220afd80eb957ac6d2a5/build-farm/make-adopt-build-farm.sh#L46
Also GNUPGHOME setup for Alsa not correct if run directly from makejdk-any-platform.sh

Correct check for alpine when setting up GNUPGHOME

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3661
Path to openjdk source was missing
test build: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-temurin/100/artifact/workspace/target/OpenJDK21U-sbom_aarch64_linux_hotspot_2024-02-20-16-44.json

Ensure FreeType include header uses WORKSPACE PATH to source

---

sbin/prepareWorkspace.sh

Fixes https://github.com/adoptium/temurin-build/issues/3659
linux riscv64 GPG has folder path length limitations, similar to Alpine.
Successful GPG creation test: https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk21u/job/jdk21u-evaluation-linux-riscv64-temurin/142/

Ensure GPG temp dir can be created for long build folder paths on linux riscv64

---

sbin/common/config_init.sh

Incorrect "shift" when parsing --release
Fixes https://github.com/adoptium/temurin-build/issues/3667
In our release builds the next option happened to be --clean-libs, which was being ignored!

Correct --release build_args parsing

---

tooling/release_download_test.sh
tooling/validateSBOMcontent.sh

Post-GA fixes to the download + SBoM validation scripting introduced via https://github.com/adoptium/temurin-build/issues/3484. Note that this does not address the other issues with this as per #3621 #3565
- Stop forcing VERBOSE to false
- Show start/end times for downloads because ... it's interesting to note
- Stop displaying the GPG output in the log because it's just noise
- Fix minimum number of artifacts in tarballs (AIX static libs has 38)
- Stop checking for FREEMARKER as we don't use it
- Freetype version is now appearing as "Unknown" since [we started using bundled freetype](https://github.com/adoptium/temurin-build/pull/3557) - Raised at https://github.com/adoptium/temurin-build/issues/3661
- Multiple other freetype versions corrected.
- `OpenJDK Source Commit` in the SBoM …

Fixes to download + SBOM validation scripts

---

sbin/prepareWorkspace.sh

ALSA has moved to ftp2.osuosl.org
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://ftp2.osuosl.org/pub/blfs/conglomeration/alsa-lib/alsa-lib-1.1.6.tar.bz2">here</a>.</p>
<hr>
<address>Apache Server at ftp.osuosl.org Port 443</address>
</body></html>
```

ALSA has moved to ftp2.osuosl.org

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/linux.sh
sbin/build.sh
tooling/reproducible/comparable_patch.sh
tooling/reproducible/repro_common.sh

Updates to the comparable build scripts to support Linux comparisons, and also recent changes due to backports for debug symbol mapping:
- Removal of linux debug symbol mapping for https://bugs.openjdk.org/browse/JDK-8323667 which is now backported to jdk21u and can be removed
- Fixes to the comparable build scripts to support Linux comparisons

Reproducible jdk21u linux build fixes and updates for debug symbols

---

.github/workflows/ca-cert-updater.yml
security/mk-ca-bundle.pl

As noted in https://github.com/adoptium/temurin-build/pull/3697, we still have to manually update the total cert count

cacert: auto update smoke test counter

---

sbin/build.sh

Provide SHAs for the individual JARs, rather than using the CycloneDX core jar sha for non-CycloneDX jars.

Correct SBOM Generation Dependency SHAs

---

test/functional/buildAndPackage/build.xml

- Add getDependentLibs for smoke test
- Related Issus: https://github.com/eclipse-openj9/openj9/issues/19122

Add getDependentLibs for smoke test

---

sbin/build.sh

jdk-21.0.3 is missing upstream fix JDK-8326685
This PR adds cflags debug mapping as a workaround.
Requires PR: https://github.com/adoptium/temurin-build/pull/3696/files

Add debug symbol mapping for reproducible jdk-21.0.3 builds

---

build-farm/platform-specific-configurations/linux.sh

Related ibmruntimes/temurin-build#94
ibmruntimes/ci-jenkins-pipeline#182
Depends https://github.com/adoptium/ci-jenkins-pipelines/pull/982

OpenJ9: Set CUDA_HOME to a generic HOME folder

---

tooling/reproducible/ReproducibleBuilds.md
tooling/reproducible/comparable_patch.sh

This pull request replaces https://github.com/adoptium/temurin-build/pull/3732.  Instead of removing the .gnu_debuglink section, this patch set changes just the four CRC bytes in that ELF section to 0.

comparable_patch.sh: Zero out .gnu_debuglink CRCs (#3730)

---

sbin/build.sh
sbin/common/config_init.sh
sbin/prepareWorkspace.sh

Check and verify /usr/local/devkit for the required matching Adoptium DevKit
If not found then it will defer to downloading from devkit-runtimes

Enable checking for /usr/local/devkit matching required Adoptium DevKit

---

sbin/common/common.sh
sbin/prepareWorkspace.sh

There is couple of
```
echo  "doing osmething terrible in Xs"
sleep X
```
here in log only the `doing osmething terrible in Xs` appear. 
I think it may be better to print out proper dynamic countdown instead of just dark screen. WDYT?
I had put it to commn.sh, but some other place may be better. Also I had used it as example only on two places in prepareWorkspace, where there definitely is more applicable places over scripts.
WDYT?

Using proper laud countdown before cleaning of repository

---

.licenserc.yaml
serverTimestamp.properties

Regression caused by https://github.com/adoptium/temurin-build/pull/3721 
Don't add source file header to the `serverTimestamp.properties`

No source file header for serverTimestamp.properties

---

.github/workflows/build.yml

- Xcode 15 prereqs at least OSX >13.5, hence jdk11+ are now built on OSX 14
- We are also building using Xcode 15.2 now, that has bug fixes

Fix failing jdk11 macos CI checks due to Xcode 15 dependencies

---

makejdk-any-platform.1
sbin/common/common.sh

the main argument have actually very strict format of jdk8, jdk8u...,jdk, the build may fail later if this is not honoured.
If your repository have different name, have to go with --version or build from dir/snapshot

Added check to prevent input of invalid repo as main argument

---

.licenserc.yaml

...on the basis that they only contain version strings, jar names, and SHAs that are obtained from external sources.

dependency_data files do not need licenses

---

tooling/release_download_test.sh
tooling/validateSBOMcontent.sh

Fixes to mac compiler versions and freetype inclusion in the JDK21+ SBoMs (Bundled version in jdk11+ is 2.13.1)
- https://github.com/adoptium/infrastructure/issues/3353
- https://github.com/adoptium/temurin-build/pull/3497 should have set it correctly for bunled, although it was later set to unknown in https://github.com/adoptium/temurin-build/issues/3661
- GCC version for Linux is now 11.3.0 since we are now using a devkit

update SBOM validator for April 2024

---

sbin/common/common.sh

replacing -q by /dev/null
repalcing double -e by  or in regex itself

Making grep -q -e -e  usable on solaris

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3807 issue(2.)
Correctly obtain the ALSA version from the built spec.gmk

Correctly obtain ALSA version for SBOM

---

sbin/build.sh

See also https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/789.

Don't use --enable-compatible-cds-alignment for OpenJ9 builds

---

RELEASING.md

Related: https://github.com/adoptium/temurin/pull/41
Draft until the retrospective has been completed. This contains updates while it's fresh in my mind by other changes will be added pending the outcome from [the retrospective](https://github.com/adoptium/temurin-build/pull/3783)

April 2024 RELEASING.md updates

---

tooling/reproducible/comparable_patch.sh
tooling/reproducible/repro_common.sh
tooling/reproducible/repro_compare.sh

- Move common comparable_build functions into repro_common.sh
- Fix Windows functions that need "cygpath" expansion
- removeSystemModulesHashBuilderParams only needed for Windows & Mac due to Signatures

Reproducible compare for Windows and Mac updates

---

tooling/reproducible/macos_repro_build_compare.sh
tooling/reproducible/repro_common.sh

Fixes #3633 
Has been tested extensively as a standalone script: sample output:
```
Comparing src_jdk/Contents/Home with tar_jdk/Contents/Home ... output to file: repro_diff.out
Number of differences:      154
ReproduciblePercent = 99.85 %
```

Add Mac Build JDK From SBOM script

---

tooling/release_download_test.sh

Fixes https://github.com/adoptium/temurin/issues/28#issuecomment-2085303993
Recommend reviewing ignoring whitespace as this is a simple change but adds indents due to the if section.

IVT: Trap case where limited platforms mean no zip or no tgz exist in release

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3807
Only use the Adoptium downloaded ALSA if not using a DevKit ALSA.
This provides a single build component of reproducibility, namely the DevKit.
When DevKit is provided OpenJDK make picks ALSA from the SYSROOT of the DevKit, update SBOM ALSA version retrieval to correctly get version using CC compiler, as is done during the build.

Only use Adoptium downloaded ALSA if not using a DevKit ALSA

---

sbin/common/common.sh

Fix for jdk8u Solaris build break:
```
11:02:11  Resetting the git openjdk source repository at /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-sparcv9-temurin/workspace/build/src in 10 seconds...
11:02:11   10 sleep: bad character in argument
```
Solaris does not support the time duration suffix

Solaris sleep does not support suffix 's'

---

sbin/build.sh

This is a follow up to https://github.com/adoptium/temurin-build/pull/2725.
`uname -m` seems to return `arm64` on MacOS but the expected naming
seems to be `aarch64` ( which is consistend with linux and windows as
well) as observed in https://github.com/graalvm/mandrel-packaging/pull/415#issuecomment-2134025210
cc @jerboaa

Fix OS architecture for darwin aarch64 builds of static libs

---

makejdk-any-platform.sh

Fixes https://github.com/adoptium/temurin-build/issues/3834
Ensure makejdk-any-platform "quotes" when required
SBOM make args can then be correctly processed including --configure-args using:
```
args=( )
IFS= args=($(xargs --max-args=1 <<< "$makejdk_any_platform_args"))
for arg in "${args[@]}"
do
echo "$arg"
done
```

Ensure SBOM makejdk-any-platform quotes args when necessary

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/3845
Ensure SBOM Build Timestamp is derived from openjdk make spec.gmk configuration value, so we know it is exactly as is compiled into the binary.
Test build: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22u/job/jdk22u-windows-x64-temurin/13/
Looks good

Ensure SBOM build timestamp is set to the ACTUAL timestamp compiled from spec.gmk

---

sbin/build.sh

This should fix windows issue I see:
```
Certificate was added to keystore
Number of certs processed: 147
real	2m26.134s
user	0m42.929s
sys	0m24.072s
build.sh : 20:48:54 : Initiating build ...
Version: local dir; OPENJDK_BUILD_NUMBER set as
/home/tester/temurinbuild-1717011006/temurin-build/sbin/build.sh: line 193: ARCHITECTURE: unbound variable
+ BUILD_RESULT=1
+ popd
```
I'm just testing it on widows VM. But it seems that the ARCHITETURE is indeed not set. Please eyball carefully, I'm unable to judge the impact

replaced ${ARCHITECTURE}" by  "${BUILD_CONFIG[OS_ARCHITECTURE]}"

---

build-farm/platform-specific-configurations/windows.sh

The cuda path (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0) to v9.1 in Adoptium playbook.
Therefore update the CUDA_VERSION variable.
reference link: https://github.com/adoptium/infrastructure/pull/3587

Update CUDA_VERSION to 9.1

---

configureBuild.sh
sbin/common/common.sh
sbin/common/config_init.sh

Fixes: https://github.com/adoptium/temurin-build/issues/3841
Provides support for building jdk-23+ for hotspot and temurin, from the jdk(head) version branches.
"hotspot" build tests:
- "jdk" (ie."tip" jdk-24) : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot/658
- "jdk23" : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot/657

Update build-scripts to enable hotspot & temurin jdk(head) version branch builds

---

sbin/build.sh

I had hit this when I forget to run all the build chain with JAVA_HOME set.  It died, but without any trace. This PR is adding the trace of what went wrong.

Exit from setupAntEnv is not propagated to its only usecase

---

sbin/prepareWorkspace.sh

Sources tarballs and binaries are available both in zip, tar.gz and tar.xz.  "my" `-l/--openjdk-source-location` was counting only tarballs and was unpacking them with `tar -xf` with workaround around `--strip-components 1`. Now, if the file ends with `.zip` it is unpacked by `unzip` with same workaround for `--strip-components 1` as tar.

Added support for zipped sources

---

.github/workflows/build.yml

github retired their macos-11 support: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
The current github macos runners do not install Xcode-11.7 required to build jdk8u, without trying to download and install Xcode-11.7, it's going to be hard to build jdk8u mac.
Removing seems the easiest option at the moment.

macos-11 github runner no longer available, remove jdk8u mac github action build

---

test/system/reproducibleCompare/playlist.xml
tooling/reproducible/linux_repro_build_compare.sh
tooling/reproducible/windows_repro_build_compare.sh

Fix https://github.com/adoptium/aqa-tests/issues/5345

Update parsing TEMURIN_BUILD_ARGS

---

sbin/build.sh

This add another entry to the timestamps added in https://github.com/adoptium/temurin-build/pull/2417 to make it easier to keep an eye on stage times during the build

build.sh: Add time stamp for start of SBoM generation

---

build-farm/make-adopt-build-farm.sh

Fixes https://github.com/adoptium/infrastructure/issues/3620#issuecomment-2203533824
hopefully :-)

Jdk8 mac xcode restore after cross compiling on arm64 with Xcode-11.7

---

docker-build.sh
docker/dockerfile-generator.sh
makejdk-any-platform.1
sbin/common/common.sh
sbin/common/config_init.sh

it is also correctly passed to image generator, however taht is not tuned to work
https://github.com/adoptium/temurin-build/issues/3855

Added optional arg to -D/--podman/--docker base image to use

---

.github/workflows/build-autotriage.yml
tooling/build_autotriage/build_autotriage.sh

Includes:
- Removing jdk22
- Adding jdk23 (replacing jdk23head) and jdk24head
- Splits build and test failures into seperate sections
- Displays a short list of trss grid views for triaged pipelines
- Various bug fixes and improvements

Fixes, improvements, and jdk versions update for build triage script

---

build-farm/platform-specific-configurations/mac.sh

I recently completed the required backport work to compile JDK17u cleanly without the need for warnings to be disabled

build: remove C flags to disable warnings on JDK17

---

.github/workflows/build.yml
build-farm/platform-specific-configurations/windows.sh
sbin/build.sh

Updating to use VS2022 for all Temurin builds. This change has been approved by the PMC today, but if it causes any unexpected issues it can be reverted.
freetype patching can (and should be, otherwise it tries to reference things that don't exist) be skipped when we're not building JDK8 with VS2017 otherwise [it tries to reference a file that isn't where it's expecting](https://github.com/adoptium/temurin-build/issues/2922#issuecomment-2273611105).
I'm currently testing with this branch on a machine which only has the VS2022 build tools installed and will report back once it's complete, but it's got to the middle of the build with jdk8u so I'm confident no other issues will show up, and standalone testing before creating this PR looked good.
Alternate solutions:
- I was tempted to just …

Use VS 2022 by default for all JDK versions + skip freetype patching

---

test/system/reproducibleCompare/playlist.xml
tooling/reproducible/linux_repro_build_compare.sh

Mirrorlist has been deprecated following the EOL of Centos 7
Fix #3905

Update various calls to mirrorlist.centos.org with vault.centos.org

---

build-farm/platform-specific-configurations/mac.sh

This will partially fix https://github.com/adoptium/adoptium-support/issues/937 for macOS aarch64

only specify --openjdk-target when cross compiling

---

test/system/reproducibleCompare/playlist.xml
test/system/reproducibleCompare/reproducible.mk
tooling/reproducible/linux_repro_build_compare.sh
tooling/reproducible/repro_common.sh
tooling/reproducible/repro_process.sh

Fix #3920 
Using common compare script
Remove non-revolant files
Remove debuginfo if exists from aqa-tests level

Update reproducible comparing on linux

---

tooling/build_autotriage/build_autotriage.sh

The automatically-generated weekly build triage issues don't currently process the riscv results.
This PR fixes that.
Resolves https://github.com/adoptium/temurin-build/issues/3941

Add linux riscv to the list of autotriaged platforms

---

tooling/strace_analysis.sh

Looks like it fixes https://github.com/adoptium/temurin-build/issues/3960
I built https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-temurin/269/ off this branch, and the [SBOM](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-temurin/269/artifact/workspace/target/OpenJDK21U-sbom_aarch64_linux_hotspot_21.0.5_8-ea.json) has the correct package names
```
{
"name" : "openssl-libs-1.0.2k-26.el7_9.aarch64",
"value" : "openssl-libs-1.0.2k-26.el7_9.aarch64"
},
```
Instead of 
```
name	"opessl-libs-1.0.2k-26.el7_9.aach64"
value	"opessl-libs-1.0.2k-26.el7_9.aach64"
```

Fix translation of package names in SBOM

---

test/system/reproducibleCompare/playlist.xml
tooling/reproducible/repro_common.sh
tooling/reproducible/repro_compare.sh
tooling/reproducible/windows_repro_build_compare.sh

Simplify the parsing logic of makejdk_any_platform_args

---

sbin/common/downloaders.sh

Fixes #3978 
Amends the curl command used to validate the signature URL to check either Location or location.
Test build running here: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk23u/job/jdk23u-linux-riscv64-temurin/16/console

Update Signature URL in BootJDK download, so Location field longer case sensitive.

---

cyclonedx-lib/getDependencies

This was used to test a set of code changes in an earlier PR, but is no longer needed.
Resolves #3969

Removing developer code link from code

---

sbin/build.sh
sbin/prepareWorkspace.sh

Fixes https://github.com/adoptium/temurin-build/issues/3887
Adds partial support for an Adoptium Windows DevKit, that consists of purely the Redist DLLs from https://github.com/adoptium/devkit-binaries/releases/tag/vs2022_redist_14.40.33807_10.0.26100.0
eg.
```
--use-adoptium-devkit vs2022_redist_14.40.33807_10.0.26100.0
```
**Test builds:**
- jdk17u Windows x64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x64-temurin/536/ - Success
- jdk17u Windows x86-32 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x86-32-temurin/367/ - Success
- jdk21u Windows x64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-x64-temurin/169/
- jdk21u Windows aarch64 : …

Add support for Windows Redist DLL as Adoptium DevKit

---

tooling/reproducible/comparable_patch.sh

https://github.com/adoptium/temurin-build/commit/08621c72262ba260e4bb6451a9c75bf1c0ab365d#diff-65e4993f80b74f0a4078e853b798cbf6770215b4c31ae1377aa2704eec01ae16R254

adapting comparable_patch.sh to new signature of removeExcludedFiles

---

tooling/reproducible/comparable_patch.sh

Hello! SSIA, Sorry I missed it befofre. I run it from fork, where I had fixed both but later commited only half (https://github.com/adoptium/temurin-build/commit/eb6b68e02579cb8ba113fc4beef77aa9db1f66a4)

The removeSystemModulesHashBuilderParams also changed signature from JDK to jdk OS java_home

---

test/system/reproducibleCompare/playlist.xml
tooling/reproducible/linux_repro_build_compare.sh
tooling/reproducible/repro_compare.sh

Enable IPV6  by configuring namespaced kernel parameters (sysctls) at runtime (--sysctl). 
Show verbose diff if there are files are different.
Close #3967

Enable IPV6 at runtime

---

sbin/build.sh
tooling/reproducible/windows_repro_build_compare.sh

Fixes https://github.com/adoptium/temurin-build/issues/4021
Don't check local Windows system UCRT if --use-adoptium-devkit used, as the correct versions will be downloaded.
Grinder test: https://ci.adoptium.net/job/Grinder/11287/

Update windows_repro_build_compare.sh to allow for windows Redist devkit

---

tooling/reproducible/repro_common.sh
tooling/reproducible/repro_compare.sh
tooling/reproducible/repro_process.sh

This adds time stamps to the steps in the reproducible comparison script just to be able to compare how long it takes when it's running (particularly on machines with different disks). 
It slightly changes the wording on some of the echo statements to to clarify what tools are being used for each step.
I've also enabled the use of `unzip -q` instead of `unzip ... > /dev/null` which looks nicer.
I have also added `-quiet` to the `openssl` commands which should mask the line with all the `.` and `+` characters but that doesn't seem to do the job on the windows/cygwin environment. I'm leaving it in anyway on the basis that it will hopefully make the output cleaner in some circumstances, including on windows if an update to openssl comes in that's happier with it.
Not tested on macos - it …

Add timestamps to  repro_compare.sh and friends

---

build-farm/platform-specific-configurations/alpine-linux.sh
build-farm/platform-specific-configurations/linux.sh
build-farm/platform-specific-configurations/mac.sh
build-farm/platform-specific-configurations/windows.sh

Ref https://github.com/adoptium/infrastructure/issues/2912 and the infra pr https://github.com/adoptium/infrastructure/pull/3773
The pr removes the hyphen from the bootjdk symlinks, ie /usr/lib/jvm/jdk-11 becomes /usr/lib/jvm/jdk11. The change has been made to the linux, mac and windows playbooks, so the build scripts need to be updated to be able to detect the new symlinks.
Leaving this as a draft so it doesnt get merged before or during the release

Remove hyphen from bootjdk symlinks

---

test/system/reproducibleCompare/playlist.xml

Depends https://github.com/adoptium/ci-jenkins-pipelines/pull/1136
https://github.com/adoptium/temurin-build/pull/4026

Enable reproducible comparing tests on jdk21+ macos

---

test/functional/buildAndPackage/src/net/adoptium/test/FeatureTests.java

This adds a smoke test for Eclipse Temurin builds which, after #4039, would expect the included `jlink` to have the capability enabled.
Grinder with this fix included is here:
https://ci.adoptium.net/job/Grinder/11381/console
Note in particular this output:
```
19:20:04  Nov 14, 2024 6:20:03 PM net.adoptium.test.FeatureTests testLinkableRuntimeJDK24Plus
19:20:04  INFO: Matched 'Capabilities:' line: Linking from run-time image enabled
```
and
```
19:20:04  PASSED: testLinkableRuntimeJDK24Plus
```
While at it I've reduced some code duplication which is now done via `@BeforeTest` once.
Thoughts?

Add smoke test for enabled JEP 493 for Eclipse Temurin builds

---

sbin/build.sh

For JDK's including JEP 493, enable the build option for producing a `jlink` that is capable of linking from the run-time image. A build with it no longer contains the `jmods` folder. Thus, the size savings. See below for some numbers.
Closes #4035

Add --enable-linkable-runtime for JDK 24+

---

SmokeTesting.md

Update the document that details how to run the smoke tests to cover passing the vendor specific options to get.sh rather than setting them as environment variables.

Doc: Update Executing Smoke Tests Document

---

build-farm/platform-specific-configurations/mac.sh
tooling/build_autotriage/build_autotriage.sh

This lets us accommodate the unexpected boot jdk location on Orka nodes until the template can be updated.

Add potential boot location for jdk10 on orka mac

---

.licenserc.yaml

Otterdog files are provided as templated text, that does not come with a specific license header.

Excuse the Otterdog blueprints

---

sbin/build.sh

https://github.com/adoptium/temurin-build/issues/4065
I may have limited availability today. If it is ok, feel free to merge as necessary.

restoring the --openjdk-source-location after PR#2702

---

cyclonedx-lib/build.xml
cyclonedx-lib/src/temurin/sbom/TemurinGenCDXA.java
cyclonedx-lib/src/temurin/sbom/TemurinGenSBOM.java
sbin/build.sh
tooling/validateSBOMcontent.sh

- Fix benign build ERROR with createSBOM jar SHA list
```
11:37:51  ERROR: Cannot determine jar version from /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-linux-x64-temurin/sbin/../cyclonedx-lib/dependency_data/dependency_data.properties for SBOM creation dependency temurin-gen-cdxa.jar.
```
- Bom.metadata not being created correctly for addComponentProp, luckily it is the first method called, so didn't cause a problem!
- Rededundent addExternalReference and addComponentExtRef were not removed and unittests were actually failing, but they were no being tested with fail on error! so passed!
- Metadata.tools has been deprecated in CycloneDX 1.0.6 spec and will be removed at some point, replaced by ToolInformation.Component
- Add the 3 new extra CycloneDX 1.0.6 dependency jars to …

Fix various SBOM creation problems

---

test/system/reproducibleCompare/reproducible.mk
tooling/reproducible/macos_repro_build_compare.sh
tooling/reproducible/windows_repro_build_compare.sh

Fixes #4079
If no SBOM and JDK file available fail the job.
Related https://github.com/adoptium/temurin-build/issues/4079

Enhance SBOM and JDK file check

---

test/functional/buildAndPackage/src/net/adoptium/test/FeatureTests.java

Basically runs `jlink --add-modules java.base --output <output> --verbose`. This is to ensure that signing of builds don't break the jlink functionality. Especially when linking from the run-time image (JEP 493 in JDK 24+).

Add basic jlink smoke test for Temurin

---

.github/workflows/build-autotriage.yml

Adds JDK25 to the autotriage tool, identifies it as the new head stream, and re-identifies jdk24 as its own version.

Adding JDK25 to autotriage

---

tooling/reproducible/windows_repro_build_compare.sh

Fixes #4062 
Update the ant validation logic in the windows reproducible build script to allow any minor version of the correct major version. Both are defined in the script header, 1.10.{X} will be treated as allowed, rather than pinning to the exact version in the SBOM.

Amend Windows Reproducible Ant Check To Be Less Strict

---

sbin/prepareWorkspace.sh

Fixes https://github.com/adoptium/temurin-build/issues/4086
Upgrade Windows Redist devkit UCRT to 10.0.26100.1742
Test builds:
- x64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-x64-temurin/241 - SUCCESS
- aarch64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-windows-aarch64-temurin/34 - UNSTABLE
- Known failures: [hotspot_tier1_runtime_0, hotspot_tier1_serviceability_0](https://trss.adoptium.net/allTestsInfo?buildId=6757f1909e1252006e1ea70e&limit=1&hasChildren=true)

Update to Windows Redist devkit vs2022_redist_14.40.33807_10.0.26100.1742

---

tooling/release_download_test.sh
tooling/reproducible/linux_repro_build_compare.sh
tooling/reproducible/macos_repro_build_compare.sh
tooling/reproducible/windows_repro_build_compare.sh

Fixes https://github.com/adoptium/temurin-build/issues/4096
CDX 1.6 spec deprecates metadata.tools, replaced by metadata.tools.components ToolInformation
https://github.com/adoptium/temurin-build/blob/master/tooling/release_download_test.sh also needs updating to download latest cyclonedx-cli to support CDX 1.6
Grinder: https://ci.adoptium.net/job/Grinder/12138/console

Update reproducible tooling to select updated CDX 1.6 tools

---

cyclonedx-lib/sign_src/TemurinSignSBOM.java

As per https://github.com/adoptium/temurin-build/issues/3946#issuecomment-2548167639 
These changes allow a user to pass in the private key as STDIN using the `--privateKeyFileSTDIN` option
`java temurin.sbom.TemurinSignSBOM --verbose --signSBOM --jsonFile $SBOM_FILE --privateKeyFileSTDIN`
The way we intend to use it in https://ci.adoptium.net/job/build-scripts/job/release/job/sign_temurin_jsf is by piping the decrypted private key at STDIN into the above command, to prevent the decrypted key from being stored as a file

Pass in private key as STDIN to TemurinSignSBOM

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/4103

Fix Windows create-sbom failure when TARGET_DIR has no trailing /

---

sign.sh

Cherry pick 7331a24158ed97ba2b62b3a7e11bc7e015fa1e39 https://github.com/adoptium/temurin-build/pull/4112

[v2025.01.01] Update jdk8u sign.sh Eclipse signing to not sign apims Microsoft files (#4112)

---

RELEASING.md

Hopefully self-explanatory. I had to do this during the January 2024 release so figured it's be useful to others to have this in the guide ;-)

RELEASING.md: Add not on how to remove an incorrect tag

---

README.md
configureBuild.sh
makejdk-any-platform.1
sbin/common/config_init.sh

For easy testing.
Open to alternative ways of doing it, adding these params seemed to make the script run end to end in wsl, so I think it would be good to have a way to run the script in wsl mode.
FWIW, I run using
` ./makejdk-any-platform.sh -J /usr/lib/jvm/java-21-openjdk-amd64 --create-sbom --wsl jdk21`

Add option to build in wsl

---

tooling/reproducible/ReproducibleBuilds.md

I may be misunderstanding, but it seems, that if you run `comparable_patch.sh` you can not use `repro_compare.sh` for final comparison. You would get false negatives. Run plain `diff jdk1 jdk2` Should be the only  thing to call. 
I would like to add this as warning to the readme.

warn on false negatives if repro_compare.sh is run after  comparable_patch.sh in  ReproducibleBuilds.md

---

tooling/reproducible/ReproducibleBuilds.md
tooling/reproducible/repro_compare.sh

Hello!
When I was following the:  https://github.com/adoptium/temurin-build/commit/d1c15a677275e44c3fed8c287159743794e88f6a, I realised that after the `diff jdk1 jdk2` I'm moreover replicating what repro_compare.sh is doing.  Thus I thought it would be better to leave it all on repro_compare.sh
, and just allow it to skip the whole preprocessing. WDYT?

Same results for similar and identical

---

.github/workflows/build.yml

Tests build on jdk21u in GHA. (I think it should do build testing of all LTS jdks)

Test build on jdk21u in GHA

---

test/system/reproducibleCompare/playlist.xml
tooling/reproducible/linux_repro_build_compare.sh
tooling/reproducible/macos_repro_build_compare.sh
tooling/reproducible/windows_repro_build_compare.sh

Reduce reproducible tests output to console. Redirect all output to build.log, which will be archived as part of testoutput.
Also add sbom.json to testoutput for mac and win. (linux already enabled.)
Related https://github.com/adoptium/ci-jenkins-pipelines/issues/1188

Redirect output to build.log and add all related info to testoutput

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/4152
With ALSA from system or devkit, the ALSA_CFLAGS is not set, only ALSA_LIBS is set, the SBOM ALSA check needs to check both, then get for system/devkit if not ALSA_CFLAGS is specified
Test build: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-temurin/291/ - SBOM ALSA correct (1.1.6)
jdk8u test: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-temurin/522/ - Good

Correct SBOM ALSA version check

---

FAQ.md
README.md

The image link in the documentation is broken as the file has been moved to another repo.

Fix documentation `AdoptOpenJDK_Build_Script_Relationships.png` image location

---

.github/workflows/build.yml
sbin/build.sh

Due to upstream make changes the "internal Eclipse signing" procedure involving "make -t" fails.
bug: https://bugs.openjdk.org/browse/JDK-8363942
- make -t fails with GNU make 3.81, causing: make[1]: *** wait: No child processes.  Stop.
- After a successful "make -t" the image targets are not regenerated, the workaround for this is to remove the make generated artifact "create-main-targets-include" if it exists
Mac Orka images need updating to use GNU make 4.4+
Windows images already using GNU make 4.4.1
Note: Removed Windows jdk11u runner build failure in jdk.crypto.ec due to bug https://bugs.openjdk.org/browse/JDK-8357657
**Test builds:**
- jdk25 Windows x64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk25/job/jdk25-windows-x64-temurin/18/ - SUCCESS
- jdk11u Mac x64 : …

Fix jdk-25+ Mac & Windows build

---

build-farm/platform-specific-configurations/mac.sh

Fixes https://github.com/adoptium/temurin-build/issues/4205
With the updated jdk25 openjdk make files, the make -t build/sign/assemble Mac procedure requires GNU make 3.81, however jdk8-24 requires GNU make 3.81 (OSX system default make) for successful "make -t".
ci.adoptium.net Orka nodes now have GNU make 4.4.1 install, which openjdk will find by default, to override its selection for jdk8-24, the openjdk configureArg "MAKE=/usr/bin/make" can be used.
Test builds:
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/561/ - SUCCESS
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-aarch64-temurin/380/ - SUCCESS
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-temurin/426/ - SUCCESS
- …

Set configureArgs for temurin on Mac to use GNU make 3.8.1 for jdk8->24

---

sbin/solaris/build-simple.sh

Fixes a few things in the files:
```
$ grep sha256 *json
OpenJDK8U-debugimage_sparcv9_solaris_hotspot_8u462b08.tar.gz.json:"sha256": "62213208862bcf29c2ad565b945f37d60af0e5e2f3efddcaaf2423d03c4540ec,
OpenJDK8U-jdk_sparcv9_solaris_hotspot_8u462b08.tar.gz.json:"sha256": "debugimage,
OpenJDK8U-jre_sparcv9_solaris_hotspot_8u462b08.tar.gz.json:"sha256": "jdk,
OpenJDK8U-sbom_sparcv9_solaris_hotspot_8u462b08-metadata.json:"sha256": "jre,
```
- The sha256 fields in the metadata files were missing a quote at the end of the strings and so the API code couldn't parse them
- The `$bin_type` parameter shouldn't be used in the call to `createMetaData` (it's blank on the first run through so works correctly for the debugimage, then is set to non-blank for the others and so the previous `bin_type` takes …

simple-build.sh: Fix quoting of sha256, fix and quote params to `createMetadata` to protect against empty variables

---

sbin/build.sh

Fixes https://github.com/adoptium/temurin-build/issues/4203
Fixes https://github.com/adoptium/temurin-build/issues/4189
The above issues are occuring on Mac and Windows due to the two pass build make_exploded & assemble_image, the 2nd phase does not setup the build tag correctly in this scenario and defaults to getting the latest "tag" from the remote repo, which will not be always correct, eg.when building an old tag.
Note: The actual code being built was correct, it is just the jdk home folder naming that ended up incorrect.
This PR adds the logic that is already done in the 1st phase ([here](https://github.com/adoptium/temurin-build/blob/43cabe30d73b951bfa9c0324ca407a3d651a9ea2/sbin/prepareWorkspace.sh#L228)) to the 2nd phase getOpenJDK tag.
Test builds of old EA tag jdk-21.0.8+6 : 
- …

Correctly set build tag based on SCM_REF|BRANCH|TAG

---

sbin/prepareWorkspace.sh

This avoids dependency of bundled freetype on system harfbuzz, as it can cause [issue with unresolved symbols](https://github.com/adoptium/temurin-build/issues/4159) depending on system.
Problem is, that harfbuzz in turn depends on freetype (also see [docs](https://github.com/freetype/freetype/blob/48f91b53311929deaf0a26140f06d9f657f1db13/docs/INSTALL.UNIX#L109)), but if version of system freetype is different (newer) than bundled freetype version, (system) harfbuzz fails on unresolved symbols.
Freetype automatically builds with harfbuzz support, if found. (linking against system harfbuzz). This explicitly disables harfbuzz support in freetype. It only affects builds (jdk < 11) with bundled freetype. Another option would be to also bundle harfbuzz.
Note that temurin builds on linux [no …

Avoid dependency of bundled freetype on harfbuzz

---

sbin/solaris/simplepipe.groovy

solaris/simplepipe.groovy is incorrectly calling the release build job, because it is not checking the RELEASE param correctly.
Running re-builds of EA build jdk8u472-b05-ea-beta:
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin-simplepipe/87/console - Good Published
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin-simplepipe/174/console - Good Published
-

Correct solaris/simplepipe.groovy params checking

---

tooling/validateSBOMcontent.sh

Fixes https://github.com/adoptium/temurin-build/issues/4129#issuecomment-3257655920
Done some tests and this allows [jdk-25+36-ea-beta](https://ci.adoptium.net/job/build-scripts/job/release/job/download_and_sbom_validation/106/) to pass but oddly the job I tried on the [latest 17 ea](https://ci.adoptium.net/job/build-scripts/job/release/job/download_and_sbom_validation/107/) wasn't happy for no immediately obvious reason.
Noting that as part of this I have also made the jobs automatically show the version and build branch that was used for the run (I usually add the tag manually when I'm running these) as part of https://github.com/adoptium/infrastructure/issues/434
Draft for now (but reviews welcome) to avoid merging for now in case until the jdk17 thing is understood (slightly possible …

validateSBOM: Update expected ALSA versions and RISC-V compiler
