makejdk.sh, sbin/build.sh, sbin/jtreg.sh
- Refactored blocks of bash code in makejdk.sh into respective bash functions...
- Added default values to global variables used across the script
- Corrected boolean comparisons - wrapped them around quotes, fixed issue...
- Added {} braces around a number of variables within double quotes
=> Refactor makejdk script

sbin/build.sh, sbin/jtreg.sh
Note: please do not merge this PR till previous PR (https://github.com/AdoptOpenJDK/openjdk-build/pull/36) has been merged. Once its are merge git will show the actual change (as commits).
- Refactored blocks of code in build.sh into respective functions. 
- Made function name consistent across scripts in one case.
=> Refactor build script

sbin/jtreg.sh
Extracted the dependency file name string for JTReg into a variable, controllable via an environment variable in the jtreg.sh script
=> Jtreg script dependency refactor

makejdk.1, makejdk.sh, sbin/build.sh, sbin/jtreg.sh, sbin/jtreg_prep.sh
Related to closer PR #54 (refer for discussion/history).
Fully resolves issue #53.
=> Refactoring jtreg prep script and dependent scripts

makejdk-any-platform.sh
Fixes issue https://github.com/AdoptOpenJDK/openjdk-build/issues/70
=> Replaced --with-num-cores with --with-jobs in makejdk-any-platform.sh

makejdk.sh
We should check out master for now as it is automatically updating. We can revert this when the dev branch is being automatically updated and having extra patches added
=> checkout master until dev is working

makejdk.sh, sbin/build.sh, sbin/common-functions.sh
Thanks @sunnythepooh for testing this out on the windows VM and bringing it this far.
Changes made to make it work on the Windows machine:
- Amended a couple of functions to not pass additional configure params for Windows builds
- Added time measurement checks to see how much time cloning and updating Git repos took
=> Adapt scripts for Windows builds

git-hg/add-branch.sh, git-hg/diff.sh, git-hg/import-common.sh, git-hg/setup8.sh, git-hg/setup9.sh, git-hg/update.sh
adds the script that will be used to check every night that we have not drifted from the mercurial repos
=> add diff checking script

makejdk.1, makejdk.sh, sbin/jtreg_prep.sh
To speed up cloning of openjdk repo on local env and VMs
=> Shallow git clone

makejdk.1, makejdk.sh
add the option to disable colour output
=> add disable colour option

makejdk.1, makejdk.sh, sbin/build.sh, sbin/common-functions.sh
Okay so this PR puts together all the required features and tweaks for the aix build
=> platform: add aix support

.gitignore, makejdk.sh, sbin/build.sh, sbin/jtreg_prep.sh
1st fix: removes error fatal: No tags can describe ''.
2nd fix: renames j2sdk-image to be the tag name making it clearer once
extracted
3rd fix: remove case sensitive dependancy for checking repo name
4th fix: shallow clone the `git fetch --tags` command
=> build: fixups

sbin/build.sh, sbin/common-functions.sh, sbin/jtreg.sh, sbin/jtreg_prep.sh
On the back of complains from Shellcheck via TravisCI - https://travis-ci.org/AdoptOpenJDK/openjdk-build/builds/252972791?utm_source=email&utm_medium=notification, tried to address many of the warnings but not all of them
=> Apply shellcheck suggestions via TravisCI across a number of scripts

makejdk.sh, sbin/build.sh
as requested in https://github.com/AdoptOpenJDK/openjdk-build/issues/161
=> Add signtool options for code signing windows binaries/dll's

sbin/common-functions.sh, sbin/jtreg.sh, sbin/jtreg_prep.sh
Replaced all 'if [ $(...) -ne 0 ]; then' style if conditions with 'if ! (...) ; then' across a number of bash scripts.
Fixes issue #174
=> Bash if condition fix in a few scripts

docker/README.md
- Wrap markdown as well.
[ci skip] Documentation only change
Signed-off-by: Matthew Gaudet <magaudet@ca.ibm.com>
=> Remove confusing mention of IBM runtimes

README.md
Partially corrected the README.md file mostly point 2, which was mentioned to refer the correct filenames. 
DCO 1.1 Signed-off-by: Pawan Jangid
=> Partial README.md file changes to refer the correct filenames in the manual. 

makejdk.sh
fixes docker builds - repeat builds and builds with -c
#194 resolves issues on Mac - not been able to test on Linux yet
=> Resolve docker build issues with volumes

makejdk.sh, sbin/build.sh
=> Allow user to pass bespoke configure parameters to configure.sh

makejdk.sh
This reverts commit d0e331732423bcb8d9086975b7191dd4d04badb6.
=> Revert "Update branch of openjdk8-openj9 to openj9-0.8"

pipelines/openjdk8_openj9_nightly_pipeline.groovy
Fix pipeline failure due to extra )
=> Remove stray ')' from pipeline script

pipelines/openjdk10_openj9_nightly_pipeline.groovy
=> Enable openjdktest builds in openjdk10-openj9

pipelines/openjdk8_nightly_pipeline.groovy, pipelines/openjdk8_openj9_nightly_pipeline.groovy
=> Add perftest, externaltests for openjdk8 and openjdk8-openj9 sdk

pipelines/openjdk_amber_nightly_pipeline.groovy
=> Add amber tests on Linux and Mac

pipelines/openjdk10_nightly_pipeline.groovy, pipelines/openjdk10_openj9_nightly_pipeline.groovy, pipelines/openjdk8_nightly_pipeline.groovy, pipelines/openjdk8_openj9_nightly_pipeline.groovy, pipelines/openjdk9_nightly_pipeline.groovy, pipelines/openjdk9_openj9_nightly_pipeline.groovy
Also update to enable capability of test build triggered per test type.
=> Add openjdktest build on Windows

pipelines/openjdk8_release_pipeline.groovy
add TAG to build pipeline for jdk8u
=> add TAG to build pipeline for jdk8u

pipelines/openjdk10_nightly_pipeline.groovy, pipelines/openjdk8_openj9_release_pipeline.groovy, pipelines/openjdk8_release_pipeline.groovy
Also add Win testing to release pipelines
Fixes #343 
Signed-off-by: smlambert <slambert@gmail.com>
=> Add arm64 jdk10 to pipeline

git-hg/updateforesttags.sh
=> Fix jdk9u Mercurial repo name

pipelines/openjdk8_openj9_nightly_pipeline.groovy, pipelines/openjdk9_openj9_nightly_pipeline.groovy
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/351
=> Update release tags for AO8/J9 and AO9/J9

git-hg/mirrorMercurialIntoGit.sh
=> remove git gc command from mirror scripts

sbin/jtreg.sh
=> Enable openjdk code coverage stats

pipelines/openjdk10_nightly_pipeline.groovy, pipelines/openjdk10_release_pipeline.groovy, pipelines/openjdk8_nightly_pipeline.groovy, pipelines/openjdk8_release_pipeline.groovy, pipelines/openjdk9_nightly_pipeline.groovy, pipelines/openjdk_amber_nightly_pipeline.groovy
=> Remove undefined variable ALT_BRANCH

pipelines/openjdk10_nightly_pipeline.groovy, pipelines/openjdk10_release_pipeline.groovy
Forcing this one through as it's blocking the release pipelines at present
=> Remove ao10/arm32 testing as jobs do not yet exist

pipelines/openjdk9_openj9_release_pipeline.groovy
This is only ever going to be run once, but I'm creating this so we have it on record along with all the otehr release pipelines :-)
=> Add AO9/J9 release pipeline

pipelines/openjdk10_openj9_release_pipeline.groovy
@lumpfish can you review this please? Addition of release pipelines for AO9/J9 and AO10/J9. Once this is merged we can kick them off, and hopefully they'll work :-)
=> Add release pipeline scripts in for AO9/J9 and AO10/J9

makejdk-any-platform.1
=> Adding Docker bug info to man page

README.md
Link to Github SHH help added in readme
=> Link to Github SHH help added in readme

pipelines/openjdk8_nightly_pipeline.groovy, pipelines/openjdk8_openj9_nightly_pipeline.groovy
Add triggers for external_extended tests
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>
=> Add triggers for external_extended tests

pipelines/build/openjdk_build_pipeline.groovy
Depends on accepting:
https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/pull/23
=>  Use shared library for node and job detection

pipelines/build/openjdk8_pipeline.groovy
Enable systemtest for jdk8 on aarch64
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>
=> Enable systemtest for jdk8 on aarch64

sbin/common/config_init.sh
https://github.com/AdoptOpenJDK/openjdk-build/pull/602 seems to have broken the build scripts
=> revert PR 602

configureBuild.sh
Forms part of https://github.com/AdoptOpenJDK/openjdk-build/issues/406
=> Build server VM on arm32 (except JDK8/HotSpot)

sbin/build.sh, sbin/prepareWorkspace.sh
(Approvers, please approve but allow me or Martijn to do the final merge)
=> Add OpenSSL download/build parameters for OpenJ9 builds

sbin/prepareWorkspace.sh
=> Update OpenJ9 to use OpenSSL 1.1.1

pipelines/build/openjdk8_pipeline.groovy
=> Add --skip-freetype for AO9/J9/Win

sbin/prepareWorkspace.sh
=> Use wget to pull JEP319 cacerts on Windows

pipelines/build/openjdk8_pipeline.groovy
=> Undo additional BuildArgs

sbin/build.sh, sbin/prepareWorkspace.sh
=> Ensure openssl is only enabled for JDK8/J9, not later versions

sbin/prepareWorkspace.sh
=> Fix cut & paste error in last commit

build-farm/platform-specific-configurations/aix.sh
Another thing to try and resolve https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/517
=> Set LDR_CNTRL in AIX environment for OpenJ9 builds

build-farm/platform-specific-configurations/aix.sh, build-farm/platform-specific-configurations/linux.sh, build-farm/platform-specific-configurations/windows.sh, sbin/build.sh
=> Use pre-built openssl 1.1.1 for JDK8/J9

docker-build.sh
=> removed -lst flag from docker run

build-farm/platform-specific-configurations/aix.sh, build-farm/platform-specific-configurations/linux.sh, build-farm/platform-specific-configurations/windows.sh, sbin/build.sh
=> Undo OpenJ9/OpenSSL support on AIX

build-farm/platform-specific-configurations/windows.sh
=> add freetype parameter for JDK10/J9

.gitignore, .travis.yml, shellcheck.sh
Moved Travis check to shellcheck.sh script allow to run the same version of shellcheck before commits. The same script will be used by Travis.
=> shellcheck script

build-farm/platform-specific-configurations/mac.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/524
=> Add support for building JDK8+OpenJ9 on macos

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
Also adds macos changes for JDK8/OpenJ9 to match JDK11
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/686
=> Add support for OpenJ9 Large Heap builds on macos

build-farm/platform-specific-configurations/mac.sh
Changes as per https://github.com/eclipse/openj9/issues/3323#issuecomment-436116237
=> Update macos.sh with new OpenJ9 parameters

build-farm/platform-specific-configurations/aix.sh, build-farm/platform-specific-configurations/linux.sh, build-farm/platform-specific-configurations/mac.sh
This fixes a build break while rebuilding an old level by temporarily reverting the last change
=> Macos j9 011 rebuild

sbin/prepareWorkspace.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/750 (hopefully!)
Note to reviewers - this seemed like the best place to do it - just before creating the workspace dir, but am open to other suggestions ...
=> Force umask to 022 to avoid any group writable files

build-farm/platform-specific-configurations/linux.sh, configureBuild.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/754
=> Do not skip freetype on ppc64le and aarch64

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
Enable System test on x64Windows
Signed-off-by: Mesbah Alam <Mesbah_Alam@ca.ibm.com>
=> Enable System test on x64Windows at Adopt

sbin/prepareWorkspace.sh
Missed one reference when doing the last update
=> Add openssl retrieval for JDK11/J9 to sbin/prepareWorkspace.sh

build-farm/platform-specific-configurations/solaris.sh, pipelines/build/openjdk8_pipeline.groovy, sbin/common/config_init.sh, sbin/prepareWorkspace.sh
test build passing here https://ci.adoptopenjdk.net/job/jdk8u-solaris-sparcv9-hotspot-test/
=> initial solaris solaris suppport

build-farm/platform-specific-configurations/mac.sh
=> Stop trying to use openssl parameters on JDK11/HotSpot

build-farm/make-adopt-build-farm.sh
rather than adding another if statement for solaris I figured that this would be simpler
=> simplify setting extension

pipelines/build/openjdk_build_pipeline.groovy
=> Add test build name with largeHeap logic

build-farm/platform-specific-configurations/linux.sh
=> Upgrade OpenJ9/s390x builds from GCC 7.3 to 7.4

pipelines/build/openjdk12_pipeline.groovy, pipelines/jobs/configurations/jdk12u.groovy
This will not work until https://github.com/AdoptOpenJDK/openjdk-jdk12u has something in it
=> add 12 build

build-farm/platform-specific-configurations/aix.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/929
=> Fix wget of jdk boot dir

build-farm/platform-specific-configurations/mac.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/924
=> Fix JDK_BOOT_DIR setting for macos

pipelines/jobs/configurations/jdk8u.groovy
=> Add platform x64MacXL in jdk8u

build-farm/platform-specific-configurations/mac.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/958
=> Remove /Home from JDK_BOOT_DIR_dir setting

build-farm/platform-specific-configurations/mac.sh
=> Fix last update which ignored top level . directory

pipelines/build.gradle, pipelines/build/common/build_base_file.groovy, pipelines/build/common/create_job_from_template.groovy, pipelines/build/common/import_lib.groovy, pipelines/build/common/kick_off_build.groovy, pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/build/openjdk10_pipeline.groovy, pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk12_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy, pipelines/build/openjdk9_pipeline.groovy, pipelines/build/openjdk_pipeline.groovy, pipelines/build/prTester/pr_test_pipeline.groovy, pipelines/library/src/ParseVersion.groovy, pipelines/library/src/common/IndividualBuildConfig.groovy, pipelines/library/src/common/MetaData.groovy, pipelines/library/src/common/VersionInfo.groovy, pipelines/src/main/groovy/testDoubles/ContextStub.groovy, pipelines/src/test/groovy/JenkinsTypeCheckHelperExtension.groovy, pipelines/src/test/groovy/TestCompilation.groovy, sbin/build.sh
Take some of the classes used in jenkins and extract them to a shared lib so that they can be reused.
Rename dir inside archive to be semver based on the parsed version.
Apply a bunch of the fixes also in #968
=> Extract Jenkins into shared library

git-hg/jdk8u/merge.sh
when rebuilding a 8 repo, merge in correct tag/head
=> Fix init of a new java 8 repo

pipelines/build/openjdk8_pipeline.groovy
=> Remove --skip-freetype from j9 builds

sbin/build.sh
Dont merge me until PR tests have completed to confirm installers are working
=> Revert directory naming update pending #1016

configureBuild.sh, pipelines/jobs/pipeline_job_template.groovy
Set cron to build on 31st of Feb to inhibit builds pre-release
=>  Pre release build inhibitor

build-farm/platform-specific-configurations/solaris.sh, pipelines/build/openjdk8_pipeline.groovy, pipelines/build/openjdk_pipeline.groovy
test x64 build: https://ci.adoptopenjdk.net/job/jdk8u-solaris-x64-hotspot/12/
test sparc build: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk8u-solaris-sparcv9-hotspot-gdams/1/
=> add support for solaris intel

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk12_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
Test will be triggered weekly automatically
=> Turn off external extended test

sbin/build.sh
=> Get jdk tag for openj9 from openjdk-tag.gmk file

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk12_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy, pipelines/build/openjdk_pipeline.groovy, pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk12u.groovy, pipelines/jobs/configurations/jdk8u.groovy
- OpenJ9 only
- JDK8,11,12,HEAD
Fixes #1099
=> Add WinXL spec to Jenkins pipelines

pipelines/build/openjdk8_pipeline.groovy
Can't build client on jdk8 for x64
=> revert_client_build_for_windows_x64

pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk12_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy, pipelines/build/openjdk_pipeline.groovy
- Also add jobName addition for WinXL builds
Follow up to #1111
Related #1099
=> Add additionalFileNameTag for WinXL builds

git-hg/mercurialToGit.sh
=> Update merge script to use new "merge" based method

git-hg/mercurialToGit.sh
=> When release branch new, branch at latest build

pipelines/jobs/configurations/jdk10.groovy
=> add 10u config file

git-hg/README.md
=> Update git-hg README.md

build-farm/platform-specific-configurations/linux.sh, build-farm/platform-specific-configurations/windows.sh
Add appropriate configure arguments if CUDA is detected on build system.
See AdoptOpenJDK/TSC#88.
=> Enable CUDA for OpenJ9

sbin/prepareWorkspace.sh
=> Back off to using curl if wget fails on freemarker checksum (macos)

pipelines/build/common/openjdk_build_pipeline.groovy
we now need to build installers on mojave.
=> switch label on mac installer job

docker/README.md, docker/buildDocker.sh
To fix : https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/917 
Updated `README.md` to contain a table with the different options of the script, and to explain what it does.
=> Moved Docker script to build repo, and updated README

build-farm/platform-specific-configurations/aix.sh
=> Reduce AIX memory usage due to fork failures

build-farm/set-platform-specific-configurations.sh, configureBuild.sh, pipelines/jobs/configurations/jdk8u.groovy, sbin/common/common.sh, sbin/common/constants.sh
Treats hotspot-jfr as a variant - we'll refactor provider vs variant out properly later
=> Allow for JFR variant

docker/jdk10/x86_64/ubuntu/Dockerfile, docker/jdk8/x86_64/ubuntu/Dockerfile, docker/jdk9/x86_64/ubuntu/Dockerfile, sbin/build.sh
Needed for `--enable-dtrace` as described in https://github.com/AdoptOpenJDK/openjdk-build/issues/1242
=> Add systemtap-sdt to Dockerfiles

sbin/build.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1269
Introduced under https://github.com/AdoptOpenJDK/openjdk-build/commit/9e9a5e05b6e7635057a7a88a1358dbb031d1fac7
=> Remove --enable-dtrace on JDK8

pipelines/build/common/create_job_from_template.groovy, pipelines/jobs/pipeline_job_template.groovy
This reverts commit d0d5e4124d4df8fbb5b0b55952aee7bb4c386d47.
=> Revert "Release build inhibitor (#1282)"

sign.sh
=> Reeanble notarize

sign.sh
=> Disable notarize again..

pipelines/build/common/build_base_file.groovy
=> Handle null additional configureArgs

git-hg/mercurialToGit.sh
=> Add excluded list of tags that will not get merged into the release branch

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9, docker/jdk13/x86_64/ubuntu/Dockerfile-openj9, docker/jdk8/x86_64/ubuntu/Dockerfile-openj9
Follow up to the prior PR (#1353)
Forgot to do the same for the Openj9 files. Made the changes and tested like the last ones :-)
=> Dockerfile: Changed container UID to host UID for j9 files

sbin/prepareWorkspace.sh
=> Skip download of Alsa on macOS.

docker/jdk11/x86_64/ubuntu/Dockerfile-openj9, docker/jdk13/x86_64/ubuntu/Dockerfile-openj9
=> Dockerfile-J9: Extract GCC-7 in a more usual way

docker/buildDocker.sh
The main thing done here was to more appropriately split up the various versions that `buildDocker.sh` can run. As it currently stands, a person couldn't run 2 docker builds in parallel from the same `openjdk-build` repo.
I've also fixed a bug in which if the first time `buildDocker.sh` is ran is using the `-use-eclipse-docker-files` option, the script won't work as the `$WORKSPACE/DockerBuildFolder/` directory hasn't been made yet.
=> Dockerfiles: Refactor buildDocker script

pipelines/jobs/configurations/jdk13u.groovy, pipelines/jobs/pipeline_job_template.groovy
Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/1397
=> Re-enable jdk13/j9/aix

build-farm/make-adopt-build-farm.sh, build-farm/platform-specific-configurations/aix.sh
I'm going to push this one through since the OpenJ9 team want it and it won't affect anyone else ;-)
=> Enable openj9 ddr

pipelines/jobs/configurations/jdk11u.groovy
=> Temporarily disable aarch64 openj9 builds

build-farm/make-adopt-build-farm.sh, configureBuild.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1257
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-aarch32-jdk8/5
=> Fix aarch32 jdk8 - use correct repo and JVM variant to enable JIT

RELEASING.md
An initial document to describe the process of doign quartlery and point releases for both HotSpot and OpenJ9 at AdoptOpenJDK
=> First draft of release process documentation

RELEASING.md
=> Fix formatting issues in RELEASING.md

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk13_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
=> Switch off testing of nightly builds during release cycle

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
=> Add --enable-jitserver for openj9 xLinux/XL

sbin/build.sh
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>
=> Use --with-vendor-name rather than --with-company-name on jdk8

README.md, build-farm/make-adopt-build-farm.sh, pipelines/build/openjdk14_pipeline.groovy, pipelines/jobs/configurations/jdk14.groovy, sbin/common/constants.sh
HotSpot only for now. Not sure how to test this
and how to get a job to show up on the build farm.
=> Add jdk 14 build pipeline

build-farm/platform-specific-configurations/windows.sh
fixes: line 45: C:\Program: command not found
=> fix windows bootjdk script

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk13_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
This reverts commit ab9c903a4608a1208ba7d7f235c4a22c23a3ad0c.
=> Revert "Switch off testing of nightly builds during release cycle"

pipelines/jobs/configurations/jdk14.groovy
=> Fix configuration file

sbin/build.sh
fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1502
=> fix codesign parsing error

pipelines/build/common/openjdk_build_pipeline.groovy
Closes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1511
FYI @jerboaa 
=> Fix Java version output

pipelines/jobs/configurations/jdk14.groovy
=> pipelines: Add AIX JDK14 builds

git-hg/skaraMirror.sh
Used to setup https://github.com/AdoptOpenJDK/openjdk-jdk14
=> add script to mirror skara repos into github

build-farm/platform-specific-configurations/aix.sh
=> Add missing fi in aix.sh

git-hg/jdk8u/merge.sh
=> addRemotes called too early for newly setup machine

build-farm/platform-specific-configurations/mac.sh
Fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1525
=> remove JDK8 J9 codesign options

pipelines/jobs/configurations/jdk8u.groovy
Boxes are offline for the time being
=> Skip solaris sparcv9

pipelines/build/openjdk14_pipeline.groovy
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>
=> Enable testing in jdk14 pipeline

pipelines/build/openjdk14_pipeline.groovy
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>
=> Enable testing of nightly builds on jdk14

pipelines/build/openjdk14_pipeline.groovy, pipelines/build/openjdk15_pipeline.groovy, pipelines/jobs/configurations/jdk14.groovy, pipelines/jobs/configurations/jdk15.groovy
=> Add AIX to JDK14/15 pipelines

configureBuild.sh, pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk8u.groovy, sbin/build.sh, sbin/common/config_init.sh
=> Enable Corretto builds jdk8 & jdk11, xLinux only to start with

pipelines/build/openjdk15_pipeline.groovy
=> Disable Testing on JDK15 Aix

configureBuild.sh
Signed-off-by: Simon Rushton <rushton@uk.ibm.com>
=> Add jre to build for jdk14

RELEASING.md
No significant changes in content, just tidy-up of typos and readability based on a read through the first part.
=> [Trivial] Some tidy up

sbin/build.sh
Fixing issue https://github.com/AdoptOpenJDK/openjdk-build/issues/980
=> Removing demo folder under JAVA_HOME

build-farm/platform-specific-configurations/windows.sh
=> add missing fi

build-farm/platform-specific-configurations/windows.sh
=> build: Fix missing space from Windows specific config

pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
Closes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1614
~~Please wait until https://github.com/eclipse/openj9/pull/8832 is merged before merging this.~~
=> Enable JIT on plinux OpenJ9 JDK8 and 11

pipelines/build/common/config_regeneration.groovy
=> Continue statement not kept in the for loop

pipelines/jobs/configurations/jdk8_pipeline_config.groovy
FYI @sxa555 this will allow us to destroy the 2008 machines and provision more 2012 build machines
=> bump jdk8u hotspot builds to win2012

build-farm/platform-specific-configurations/windows.sh, pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/src/main/groovy/testDoubles/ContextStub.groovy
test build: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/38/
=> remove unnecessary workspace relocation script and use jenkins workspace

sbin/build.sh
=> Don't disable native debug symbols for OpenJ9

pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/src/main/groovy/testDoubles/EnvStub.groovy
=> add custom workspace env var

sbin/build.sh
fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/1670
broken in https://github.com/AdoptOpenJDK/openjdk-build/pull/1637
=> remove map and pdb files from JRE

pipelines/build/common/openjdk_build_pipeline.groovy
this means that the builds will now fail if the installers fail to build
=> add propagate: true to all installer jobs

pipelines/build/common/openjdk_build_pipeline.groovy
Reverts AdoptOpenJDK/openjdk-build#1668
=> Revert "Fix checksums on platforms without sha256sum"

pipelines/build/common/openjdk_build_pipeline.groovy
This reverts commit e5cfc16830dcf3845e6f3511028f4ef04fc205ef.
=> Revert "add propagate: true to all installer jobs (#1675)"

RELEASING.md, pipelines/build/regeneration/README.md
=> Updating Concurrent Pipeline Scripts

sbin/build.sh
=> Remove debug files from JDK and JRE

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fix checksums on platforms without sha256sum

RELEASING.md
Follow up to https://github.com/AdoptOpenJDK/openjdk-build/pull/1702
=> Move new releases to bottom of RELEASING.md

pipelines/build/common/openjdk_build_pipeline.groovy
=> Provide notification that signing or installer failed

pipelines/build/common/openjdk_build_pipeline.groovy
=> Ensure testType isn't false

pipelines/jobs/configurations/jdk14_pipeline_config.groovy, pipelines/jobs/configurations/jdk15_pipeline_config.groovy
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1661
=> Enable JITserver for J9 builds on JDK14 and later

pipelines/build/common/openjdk_build_pipeline.groovy
=> Fire installer failure on all failed results

pipelines/jobs/configurations/jdk15_pipeline_config.groovy
=> Remove auto from --enable-dtrace

pipelines/library/src/common/VersionInfo.groovy
Follow up of https://github.com/AdoptOpenJDK/openjdk-build/pull/1704
=> Account for empty ADOPT_BUILD_NUMBER string

pipelines/jobs/configurations/jdk11_pipeline_config.groovy, pipelines/jobs/configurations/jdk14_pipeline_config.groovy, pipelines/jobs/configurations/jdk15_pipeline_config.groovy, pipelines/jobs/configurations/jdk8_pipeline_config.groovy
Required for fixing https://github.com/AdoptOpenJDK/openjdk-build/issues/1733
=> Move AIX OpenJ9 builds to AIX 7.1.5 machines

build-farm/platform-specific-configurations/aix.sh
It's causing issues with tonight's AIX builds
=> I need to revert the previous LIBPATH change 

build-farm/platform-specific-configurations/aix.sh
Need this in before tonight's builds so forcing through
=> Add /usr/lib back into AIX LIBPATH

RELEASING.md
This is about all I know about. It's not great, but it should partially cover #1581.
=> Update RELEASING.md for new JDK head releases.

pipelines/build/common/openjdk_build_pipeline.groovy
* Removes non functional getResult() blocks
* Encompasses installer functions in try-catch instead
=> Amend "Fire installer failure on all failed"

pipelines/build/common/openjdk_build_pipeline.groovy
* Introduces missing timestamps to the builds
* Introduces an initial, test 18hr timeout for all pipelines.
Closes #1101 , Closes #1102 
=> Introduce timestamps and timeouts

pipelines/build/common/openjdk_build_pipeline.groovy
Should fix https://github.com/AdoptOpenJDK/openjdk-build/issues/1769
This reverts commit 5aa149aefe096724be75f93bce0c2894cc311ff2.
=> Revert "Introduce timestamps and timeouts (#1760)"

pipelines/build/common/openjdk_build_pipeline.groovy
As per https://github.com/AdoptOpenJDK/openjdk-build/pull/1754#issuecomment-633714627
I'm going to directly merge this without official approval as it's a fix to a break as diagnosed by @douph1
Problem introduced by https://github.com/AdoptOpenJDK/openjdk-build/pull/1754/files
=> Reverse "Improve filter parsing" as it causes a build break

sbin/prepareWorkspace.sh
Forcing this through in order to stabilise nightlies as no-one else is currently responding to my messages about it in slack :-)
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1780
=> Emergency fix to pull freetype from local repo

sbin/prepareWorkspace.sh
Pushing this through due to it being a build break resolution
=> Freetype typofix

sbin/prepareWorkspace.sh
Again, pushing this through due to build break
=> Freetype typofix2

pipelines/build/common/openjdk_build_pipeline.groovy
=> Set build result to fail on installer failure

pipelines/build/common/openjdk_build_pipeline.groovy
* Seems to cause a lot of false positives or just doesnt work overall. Better to just remove for now
=> Revert 'Fire installer failure on all failed results'

pipelines/build/common/openjdk_build_pipeline.groovy
=> Only try and archive Mac & Win buildInstaller artifacts

pipelines/build/common/config_regeneration.groovy, pipelines/build/regeneration/jdk10_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk11_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk12_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk13_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk14_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk15_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk8_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk9_regeneration_pipeline.groovy
=> Remove use of named args

pipelines/build/common/openjdk_build_pipeline.groovy
* Builds an installer for the JDK and for JRE if it exists
Closes: #1751 
=> Build one installer unless we have JRE

pipelines/build/common/openjdk_build_pipeline.groovy
Follow up to https://github.com/AdoptOpenJDK/openjdk-build/pull/1790
=> Remove broken break statement

pipelines/build/common/build_base_file.groovy, pipelines/build/common/openjdk_build_pipeline.groovy
* most_recent_feature_release has reverted back to 14 since #1822 (it was at 15)
Follow up to: #1822 
Signed-off-by: Morgan Davies morgan.davies@ibm.com
=> Use most_recent_feature_version

pipelines/build/common/build_base_file.groovy, pipelines/build/common/openjdk_build_pipeline.groovy
* Also fixes a variable declared Python style. Groovy don't like that
=> Declare Helper as an import

pipelines/build/common/build_base_file.groovy, pipelines/build/common/openjdk_build_pipeline.groovy
* Partial revert of https://github.com/AdoptOpenJDK/openjdk-build/pull/1835 (keeps the syntax change, removes the lib ones)
=> Revert Import changes from previous commit

pipelines/gradlew, sbin/build.sh
=> Add gradlew retry to avert network failures

pipelines/build/common/build_base_file.groovy, pipelines/build/common/openjdk_build_pipeline.groovy
=> equalsIgnoreCase can't be used with null

pipelines/build/common/openjdk_build_pipeline.groovy
=> Remove wix from installer filter

sbin/prepareWorkspace.sh
Fixes issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/1867
=> Change freemarker.tar.gz download to apache site

README.md, RELEASING.md, build-farm/make-adopt-build-farm.sh, pipelines/build/common/build_base_file.groovy, pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/build/openjdk16_pipeline.groovy, pipelines/build/regeneration/jdk16_regeneration_pipeline.groovy, pipelines/jobs/configurations/jdk16.groovy, pipelines/jobs/configurations/jdk16_pipeline_config.groovy, sbin/common/constants.sh
* Also includes documentation updates
Closes: #1866 
=> Migrate head to jdk16

pipelines/build/common/config_regeneration.groovy
=> Remove public from regenerate()

build-farm/make-adopt-build-farm.sh, sbin/common/common.sh
Issue: #1873 (doesn't close, the original error is not fixed by this)
=> Dump info on failed api request

pipelines/build/common/config_regeneration.groovy
=> Add timestamps to regeneration log

pipelines/jobs/configurations/jdk16_pipeline_config.groovy
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1882
Ref: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1591970418052400?thread_ts=1591953258.043300&cid=C09NW3L2J
=> Update xLinxu JDK16 builds to run on RHEL7

pipelines/build.gradle
=> Update groovy to 3.0.4 for all platforms

pipelines/build/common/openjdk_build_pipeline.groovy
=> print full stacktrace instead just getMessage

pipelines/jobs/configurations/jdk14u_pipeline_config.groovy, pipelines/jobs/configurations/jdk15.groovy, pipelines/jobs/configurations/jdk15_pipeline_config.groovy
* Also deletes the duplicate arm32 config in jdk14
Closes: #1900 
=> Add arm32 builds to JDK15

pipelines/build/common/build_base_file.groovy, pipelines/build/common/config_regeneration.groovy, pipelines/build/common/openjdk_build_pipeline.groovy
* See https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/pull/36
Issue: #1873 
=> Add context to getAvailableReleases

pipelines/build/common/openjdk_build_pipeline.groovy
This reverts #1913 
Closes: #1914
=> Revert "Print out file perms on build fail (#1913)"

pipelines/build/common/openjdk_build_pipeline.groovy
to help debug/understand #1834
=> try re-throw exception to see full stacktrace

docker-build.sh, docker/dockerfile-generator.sh
Ref: https://ci.adoptopenjdk.net/job/DockerfileCheck/121/
Signed-off-by: William Parker william.parker1@ibm.com
=> docker: Fixes to get `dockerfile-generator.sh` working with `makejdk-any-platform.sh --docker`

docker/dockerfile-generator.sh
Missed out from my previous PR: #1912 
Signed off by: William Parker <william.parker1@ibm.com>
=> docker: Declare `PRINT` var in dockerfile-generator.sh

pipelines/build/prTester/pr_test_pipeline.groovy
=> Set PR_Tester build result to failure

pipelines/build/common/config_regeneration.groovy
There is no need to check if we're going to overwrite a release in the pr-tester as we won't ever release inside of it
=> Don't check if pr-tester is running

pipelines/build/common/openjdk_build_pipeline.groovy
=> Print the error and stacktrace together

pipelines/build/prTester/pr_test_pipeline.groovy
=> Print out name of failed pipeline in pr_tester

pipelines/build/common/openjdk_build_pipeline.groovy
=> Use jenkins utility function to print stack trace : printThrowable(e)

build-farm/make-adopt-build-farm.sh, sbin/common/common.sh
=> Switch timeout value to seconds

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk14u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
Codebuild machines are currently only 2CPU which is causing occasional crashes during builds, switching to Azure
=> switch from codebuild to azure devops

pipelines/jobs/pipeline_job_template.groovy
Reverts AdoptOpenJDK/openjdk-build#1970
=> Revert "Block nightly builds"

RELEASING.md, pipelines/build/regeneration/jdk10_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk11_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk12_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk13_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk14_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk15_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk16_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk8_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk9_regeneration_pipeline.groovy
Also updates RELEASING doc with info about update repos and what needs to be done should the switch to an update repo be necessary
Closes: #1613 
=> Account for jdkxxu in job regenerators

pipelines/build/common/build_base_file.groovy, pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy
=> Refactor scripts to only use node when needed

pipelines/build/common/openjdk_build_pipeline.groovy
=> Pass in build jdk repo and branch to test pipeline builds

pipelines/build/common/build_base_file.groovy
=> Always pre-clean workspace on mac

pipelines/build/regeneration/jdk10_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk11_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk12_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk13_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk14_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk15_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk16_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk8_regeneration_pipeline.groovy, pipelines/build/regeneration/jdk9_regeneration_pipeline.groovy
=> Parameterise the job regenerators

build-farm/make-adopt-build-farm.sh
=> Terminate build if we dont have valid JDK_BOOT_DIR

pipelines/build/regeneration/README.md
=> Add note on where to find the test job regenerator

sbin/build.sh
OpenJ9 builds capture debug symbols in the debug image; this avoids the duplication while retaining them when present in other (e.g. hotspot) builds.
Fixes: #1972.
=> Only remove debug symbols from JDK for OpenJ9 builds

build-farm/platform-specific-configurations/linux.sh, configureBuild.sh
switches to use the aarch32 port repo
=> re-enable JIT on arm32

build-farm/platform-specific-configurations/linux.sh
=> Add -latomic to ARM32 builds for 8

RELEASING.md
Documentation tweak. See modified doc for details.
=> Ensure we use the correct tag while composing a milestone Publish Name

sbin/prepareWorkspace.sh
Fixes: #1966
General thoughts are referenced in https://github.com/AdoptOpenJDK/openjdk-build/issues/1966#issuecomment-674939773.
Signed-off-by: Austin Bailey <Austin.Bailey@ibm.com>
=> Populate "SOURCE" tag for jdk8u builds

RELEASING.md
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>
=> Add early access configureArgs options to RELEASING.md

sbin/build.sh
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>
=> Use chronological tag sorting to get latest version tag

build-farm/make-adopt-build-farm.sh, pipelines/build/common/config_regeneration.groovy, sbin/build.sh, sbin/common/common.sh, sbin/prepareWorkspace.sh, sign.sh
This is an alternative to allowing the jobs to queue up behind one another. At the least the pr-tester jobs will run now.
Closes: #2053 
Signed-off-by: Morgan Davies morgandavies2020@gmail.com
=> Re-enable concurrency for the pr-tester

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk15u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Enable sanity.openjdk set on arm32

pipelines/build/common/config_regeneration.groovy
* Because bash advanced sleep doesn't work here
Follow up to https://github.com/AdoptOpenJDK/openjdk-build/pull/2102
=> Use Groovy's Advanced Sleep

.azure-devops/openjdk-pipelines.yml, .azure-devops/test/jobs/steps/parallel.yml, .azure-devops/test/jobs/steps/test.yml, .azure-devops/test/jobs/template.yml, .azure-devops/test/sanity.yml
Signed-off-by: lanxia <lan_xia@ca.ibm.com>
=> Add support for Azure Devops testing

pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk12u_pipeline_config.groovy, pipelines/jobs/configurations/jdk13u_pipeline_config.groovy, pipelines/jobs/configurations/jdk14u_pipeline_config.groovy, pipelines/jobs/configurations/jdk15u_pipeline_config.groovy, pipelines/jobs/configurations/jdk16.groovy, pipelines/jobs/configurations/jdk16_pipeline_config.groovy
=> Add arm32 to build&test jdk16

pipelines/build/common/openjdk_build_pipeline.groovy
fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1616
=> sign: force windows to use 2012 machines

pipelines/jobs/configurations/jdk15u_pipeline_config.groovy, pipelines/jobs/configurations/jdk16_pipeline_config.groovy
Ref: https://github.com/AdoptOpenJDK/openjdk-build/pull/2154#issuecomment-712908452
=> Switch JDK15/J9 back to centos7 build image

tools/nightly_build_and_test_stats.groovy
=> Nightly build and test stats job

pipelines/library/src/common/VersionInfo.groovy, pipelines/src/test/groovy/VersionInfoTest.groovy, pipelines/src/test/groovy/VersionParsingTest.groovy
=> Add support for jdk8 'ea' version info

.github/workflows/build.yml
=> actions: disable macOS PR tester

RELEASING.md, sbin/build.sh
=> Use milestone=fcs only on JDK8 release

pipelines/build/common/openjdk_build_pipeline.groovy
=> Remove waitForANodeToBecomeActive from Docker

pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/library/src/common/VersionInfo.groovy, pipelines/src/test/groovy/VersionInfoTest.groovy
=> Compute semver build from openjdk patch and build

pipelines/build/common/openjdk_build_pipeline.groovy
=> Load jenkins helper before building

build-farm/platform-specific-configurations/windows.sh
=> Temporarily change jdk8 openj9 back to using vs2010

tools/stage_time_analysis.groovy
=> Jenkins longest job stage analysis script

sbin/build.sh
=> Ensure createOpenJDKTarArchive is in the working directory

RELEASING.md
Add information about disabling nightly testing during release cycles.
Morgan, you mentioned this might need to be changed in the base files too but I wasn't clear on where that would be so is this enough?
=> doc: add explicit info on disabling nightly testing

sbin/prepareWorkspace.sh
Because of the slowness issues with java on the SPARC Solaris 10 machine, the [changes to run keytool multiple times during the build](https://github.com/AdoptOpenJDK/openjdk-build/pull/2113) have pushed it over the 8 hour timeout.
As a mitigation, this PR will stop the builds from generating cacerts on Solaris/SPARC and instaead download and use the cacerts file from the Solaris/x64 build. This is not intended to be a permanent solution, but it will allow us to get the JDK8/HotSpot/Solaris-sparc builds running clean again with valid output on this platform.
~(NOTE: This WIP PR currently includes a change to [exclude gradle](https://github.com/AdoptOpenJDK/openjdk-build/pull/2228) as it helps speed up testing, but that will NOT be part of this PR - only the change to prepareWorkspace.sh)~ …
=> Do not build mozilla cacerts bundle natively on Solaris/SPARC (too slow on our systems)

build-farm/platform-specific-configurations/alpine-linux.sh
fixes: https://github.com/AdoptOpenJDK/openjdk-build/issues/2303
=> alpine: attempt to download EA build JDK if a GA doesn't exist

tools/nightly_build_and_test_stats.groovy
Rate the success of the nightly Jenkins Build & Tests Execution
=> Add nightly build and test quantatative success rating

.github/workflows/build.yml, README.md, pipelines/build/common/build_base_file.groovy, pipelines/build/common/config_regeneration.groovy, pipelines/build/common/create_job_from_template.groovy, pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk15u_pipeline_config.groovy, pipelines/jobs/configurations/jdk16_pipeline_config.groovy, pipelines/jobs/configurations/jdk17_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy, pipelines/library/src/common/IndividualBuildConfig.groovy, pipelines/src/test/groovy/IndividualBuildConfigTest.groovy, sbin/build.sh, sbin/common/config_init.sh
converts the cross_compile env var to be a build arguement
=> fix issue from introducing CROSS_COMPILE env var

pipelines/build/common/openjdk_build_pipeline.groovy
=> Temporarily clean s390x build workspace after build to save space

build-farm/platform-specific-configurations/mac.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2309
=> Add openssl compile and bundle for jdk8 openj9

pipelines/build/common/cross_compiled_version_out.groovy, pipelines/build/common/openjdk_build_pipeline.groovy
=> Revert to the old linux cross compile filter

pipelines/build/common/cross_compiled_version_out.groovy
Reverts AdoptOpenJDK/openjdk-build#2326 as Morgan fixed the root cause
=> Revert "Add Debug statements to try and resolve #2325"

pipelines/jobs/configurations/jdk16_pipeline_config.groovy
=> jdk16 x32Windows test pipeline config not valid

pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
=> Ensure dragonwell jdk8 windows64 builds using dragonwell label

sbin/prepareWorkspace.sh
=> Ensure dragonwell build validates git repo correctly

tools/stage_time_analysis.groovy
It is more useful if this tool can analyze jobs run over the last x days, as some jobs are not run anymore or regularly and are not of interest.
=> Add period_days to analyze stage_time_analysis for jobs over the last so many days

pipelines/build/common/build_base_file.groovy, pipelines/build/common/weekly_release_pipeline.groovy, pipelines/build/regeneration/build_pipeline_generator.groovy, pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk15u.groovy, pipelines/jobs/configurations/jdk16.groovy, pipelines/jobs/configurations/jdk17.groovy, pipelines/jobs/configurations/jdk8u.groovy, pipelines/jobs/weekly_release_pipeline_job_template.groovy
=> New midweek nightly build schedule and weekend weekly-release

git-hg/mercurialToGit.sh
The git-hg script needed the jdk tag sorting updating to allow for the jdk-11.0.9.1 (patch) scenario. As it was it thought jdk-11.0.9.1+1 was the latest tag, as opposed to jdk-11.0.10+8.
Sorting logic copied from: https://github.com/AdoptOpenJDK/openjdk-build/blob/4b03e4c4c37a5c02ba60caacb4bd2d3bd9f6fead/sbin/build.sh#L802
=> Fix git-hg mirror tag sorting so jdk11u _adopt tags get created

pipelines/build/common/config_regeneration.groovy
=> Make downstream regenerator less inclusive

tools/nightly_build_and_test_stats.groovy
The Success Rating will now include the scheduled weekend release build&test
=> Include weekend weekly builds in Success Rating stats

tools/nightly_build_and_test_stats.groovy
Ensure:
- job startBy is not null
- job status is Done
- allow for no tests or builds being done, preventing divide by 0
=> Nightly stats, allow for null startBy in pipeline object

pipelines/jobs/configurations/jdk8u_pipeline_config.groovy, sbin/build.sh, sbin/prepareWorkspace.sh
Related: 
https://github.com/AdoptOpenJDK/openjdk-build/issues/2385
https://github.com/AdoptOpenJDK/openjdk-build/issues/2316
=> Polish Dragonwell

RELEASING.md
=> Document re-enabling Nightly Testing after a Release

sbin/build.sh
Controversial? Maybe, but we [disabled it for Solaris/SPARC](https://github.com/AdoptOpenJDK/openjdk-build/pull/2228) for performance reasons a while back and it did not appear to cause any obvious problems ([reinstated](https://github.com/AdoptOpenJDK/openjdk-build/pull/2399) once a particular issue with the build system was fixed) and [based on the Slack threads](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1605110513432600) which I've tried to start on this topic no-one was able to tell me why it was strictly required, and since the gradle code here has been the cause of various build failures in the last year or so I'm proposing stripping it out to resolve https://github.com/AdoptOpenJDK/openjdk-build/issues/2139 unless someone can come up with a good reason to retain it (it may …
=> build: Disable buildSharedLibs as it does not seem to be needed

.github/workflows/build.yml, pipelines/build/prTester/README.md
=> Collect built JDKs in PR tester

pipelines/jobs/configurations/jdk16.groovy, pipelines/jobs/configurations/jdk17.groovy
New machine needed: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1884
=> Remove arch64Windows from nightly until new machine available

build-farm/platform-specific-configurations/linux.sh, pipelines/build/dockerFiles/dragonwell_aarch64.dockerfile, pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, pipelines/jobs/configurations/jdk8u.groovy, pipelines/jobs/configurations/jdk8u_pipeline_config.groovy
This requires https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1706
Related issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2367
=> Add dragonwell on aarch64

pipelines/build/common/openjdk_build_pipeline.groovy
=> Remove pointless getResult() from sign()

pipelines/build/common/kick_off_build.groovy
See https://github.com/AdoptOpenJDK/openjdk-build/pull/2132/commits/8d762f9b787ec45a25696c5f55bcb89b4867823b#diff-a385c8842d53dff1a13532ec0e118480d4ebce5fbca4b3b3ad469e5d57f0f1ea
Fixes: #2447 
=> Reverts functionising of kick_off_build.groovy

pipelines/build/openjdk10_pipeline.groovy, pipelines/build/openjdk11_pipeline.groovy, pipelines/build/openjdk12_pipeline.groovy, pipelines/build/openjdk13_pipeline.groovy, pipelines/build/openjdk14_pipeline.groovy, pipelines/build/openjdk15_pipeline.groovy, pipelines/build/openjdk16_pipeline.groovy, pipelines/build/openjdk17_pipeline.groovy, pipelines/build/openjdk8_pipeline.groovy, pipelines/build/openjdk9_pipeline.groovy
* If we are, retrieve head number and pull in correct config file
Fixes: #2451 
=> Check we are not on JDK head in the pipelines

pipelines/build/prTester/pr_test_pipeline.groovy
=> Missing CHECKOUT_CREDENTIALS for pr tester

pipelines/jobs/configurations/jdk16.groovy
Signed-off-by: Simon Rushton <srushton@redhat.com>
=> Add s390x_linux_xl for jdk16

pipelines/jobs/configurations/jdk17.groovy
Signed-off-by: Simon Rushton <srushton@redhat.com>
=> Add s390x_linux_xl to jdk17 build pipeline

pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/src/main/groovy/testDoubles/ContextStub.groovy, pipelines/src/main/groovy/testDoubles/EnvStub.groovy
Adds status checks for each downstream job to help see the build failures
=> Set GitHub commit status for downstream PR tester jobs

sbin/build.sh
Create an archive of openjdk make failure logs and dumps if any.
=> Archive failed openjdk make failure logs

.github/workflows/build.yml, README.md, build-farm/platform-specific-configurations/linux.sh, configureBuild.sh, pipelines/build/common/openjdk_build_pipeline.groovy, pipelines/jobs/configurations/jdk11u.groovy, pipelines/jobs/configurations/jdk11u_pipeline_config.groovy, sbin/build.sh, sbin/common/config_init.sh, sbin/common/constants.sh, sbin/prepareWorkspace.sh
Add Bisheng JDK RISC-V support for openjdk-build. Closes: #2420
=> Add Bisheng JDK RISC-V support

build-farm/platform-specific-configurations/linux.sh
Fed up of this now :-) Forcing this through to prevent build break again
=> Refix last change again

.github/workflows/build.yml, sbin/common/constants.sh
=> Change JDK16_VERSION to jdk16u

.gitignore, build-farm/make-adopt-build-farm.sh, build-farm/platform-specific-configurations/mac.sh, configureBuild.sh, sbin/common/constants.sh
=> Terminate build on unknown variant type

configureBuild.sh, sbin/build.sh
Change bisheng source code repo to the official [OpenEuler mirror](https://github.com/openeuler-mirror/bishengjdk-11) and update tag search rules.
=> update bisheng source repo and tag search rules

RELEASING.md
=> Update RELEASING.md update repo section

RELEASING.md
* Twin PR -> https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/102
=> Update doc to account for ci changes

build-farm/platform-specific-configurations/windows.sh, sbin/prepareWorkspace.sh
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2549
Draft until https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2085 (Deploy on all windows machines) is complete
=> Update OpenJ9's OpenSSL to 1.1.1k

test/functional/buildAndPackage/src/net/adoptopenjdk/test/FeatureTests.java
=> Disable JFR smoke test  on AIX

test/functional/buildAndPackage/playlist.xml
=> Add Java version to smoke test

sbin/build.sh
=> Enable Shenandoah for Corretto jdk 11

.github/labeler.yml, .github/regex_labeler.yml, .github/workflows/comment-bot.yml, .github/workflows/labeler.yml
=> Add comment bot, labeller and project manager

configureBuild.sh
fixes: https://github.com/adoptium/adoptium/issues/10
=> stop building jdk8 aarch64 from separate repo

.github/workflows/labeler.yml
=> Specify column name for project manager

sign.sh
This is required as part of the EF codesign work
=> add deep signing for macOS

sbin/NOTICE.template, sbin/build.sh
closes: https://github.com/adoptium/adoptium/issues/20
=> initial attempt at adding NOTICE file

sbin/common/constants.sh, sbin/prepareWorkspace.sh
Update Temurin marker file to be the required notice file. This will ensure that the required notice is in place as part of each build process.
After merging the Temurin.md will be removed from the source repos
=> Update marker file name

.github/workflows/build.yml
Add's some windows GitHub actions CI builds back to allow us to catch errors in script changes
=> actions: add windows builds

build-farm/make-adopt-build-farm.sh
=> Enable debug images for all platforms including AIX

.github/workflows/build.yml, build-farm/make-adopt-build-farm.sh, sbin/common/constants.sh
changes also made in `ci-jenkins-pipelines` https://github.com/adoptium/ci-jenkins-pipelines/pull/168
=> bump JDK tip version to JDK18

.github/workflows/build.yml
=> Add smoke test to PR workflow

.github/workflows/ca-cert-updater.yml, security/README.md
Adds a bot that checks for cacerts updates each night.
=> add automatic cacert updater bot

.github/workflows/ca-cert-updater.yml
This will create the pull request as the correct user and pass the ECA checks
=> Switch cert updater to use Temurin bot

sbin/common/config_init.sh
=> Change default TARGET_FILE_NAME to include -jdk

sign.sh
This PR fixes the issues that we observed with Eclipse IDE
fixes: https://github.com/adoptium/temurin-build/issues/2687
=> remove entitlements from deep sign

.github/linters/.jscpd.json, .github/workflows/build.yml, sbin/common/constants.sh
JDK17u repo has now been mirrored
=> bump JDK17 to JDK17u

RELEASING.md
=> Update releasing doc about re-enabling nightly tests

RELEASING.md, sbin/prepareWorkspace.sh
In draft until https://github.com/adoptium/temurin-build/issues/2798 is complete
=> Switch JDK8u to use Skara mirror and update RELEASING.md

SECURITY.md
Note that the security reporting email address is eclipse.org
=> Update security report location

.github/workflows/linter.yml
fixes: https://github.com/adoptium/temurin-build/issues/2820
=> linter: bump superlinter to v4

build-farm/platform-specific-configurations/windows.sh, sbin/prepareWorkspace.sh
https://github.com/eclipse-openj9/openj9/issues/14208
=> Update OpenJ9 builds to use OpenSSL 1.1.1m

RELEASING.md
Fixes https://github.com/adoptium/temurin-build/issues/2848
[Link to new version in my branch](https://github.com/sxa/openjdk-build/blob/release_updates_feb22/RELEASING.md)
=> doc: Update RELEASING.md based on Jan2022 experiences

sbin/build.sh
=> Show different bug-url for corresponding jdk version

sbin/build.sh
when enable --create-sbom flag in build.sh script, it exposed an error:
https://github.com/adoptium/temurin-build/runs/6404611567?check_suite_focus=true
=> fix: env WORKSPACE is not set for non-Jenkins env.

sbin/common/config_init.sh
Ref: https://github.com/adoptium/temurin-build/issues/2900
=> feat: enable SBOM as default behavior

.github/workflows/build.yml
Adds a Github action for building JDK8 and JDK11 on Alpine Linux
=> add alpine JDK8 and JDK11 to build action

sbin/build.sh
Ref: https://github.com/adoptium/temurin-build/issues/2900
=> feat: add archive sbom.json in Jenkins build.

CHANGELOG.md, README.md, RELEASING.md, build-farm/make-adopt-build-farm.sh, build-farm/platform-specific-configurations/aix.sh, build-farm/platform-specific-configurations/linux.sh, build-farm/platform-specific-configurations/mac.sh, build-farm/platform-specific-configurations/windows.sh, build-farm/set-platform-specific-configurations.sh, configureBuild.sh, docker-build.sh, makejdk-any-platform.1, makejdk-any-platform.sh, native-build.sh, sbin/common/common.sh, sbin/common/config_init.sh, sbin/prepareWorkspace.sh
=> docs: Update reference from "Adopt" to "Adoptium"

test/functional/buildAndPackage/src/net/adoptium/test/BundledFreetypeTest.java, test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java
- fix Adopt_J9_FeatureTests_0
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14952 ibm_git/runtimes/backlog/issues/796
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>
=> Fix Adopt_J9_FeatureTests_0

build-farm/make-adopt-build-farm.sh, build-farm/platform-specific-configurations/linux.sh, sbin/build.sh
- get return value for multiple caller in sbom related block
was originally done in https://github.com/adoptium/temurin-build/pull/2956 
Due to part of the changes aint needed that PR was closed, but this part is still good to have
=> chore: move set JAVA_HOME into a function

build-farm/set-platform-specific-configurations.sh
Ref: https://github.com/adoptium/temurin-build/issues/2973
=> feat: disable CCache for jdk19+ as part of reproducible builds

build-farm/set-platform-specific-configurations.sh
Fixes: https://github.com/adoptium/temurin-build/issues/2977
=> feat: enable reproducible build for jdk17

build-farm/platform-specific-configurations/linux.sh, build-farm/set-platform-specific-configurations.sh, sbin/build.sh
Ref: https://github.com/adoptium/temurin-build/issues/2973
Ref: https://github.com/adoptium/temurin-build/pull/3026#issuecomment-1176103066
=> update: move function from build-farm to build.sh (reproducible build)

security/mk-cacerts.sh
Some tidy up comments from previous PR: https://github.com/adoptium/temurin-build/pull/3033
=> mk-cacerts.sh tidy up

sbin/common/config_init.sh
=> Amend OS/Kernel version reporting to include pretty o/s and kernel version.

README.md, makejdk-any-platform.1
=> Add --create-sbom to README.md

sbin/build.sh
Fix: https://github.com/adoptium/temurin-build/issues/3066
Detail:
https://github.com/adoptium/temurin-build/issues/3060#issuecomment-1213059414
=> fix: correct path for case sensitive Mac drive

FAQ.md
I haven't updated the macos ones as I'm not entirely sure of the best way to reference them, but I believe the rest of this information is now correct. We should endeavour to keep this table accurate when we make changes to the build scripts.
=> doc: Update FAQ with correct compiler levels

.github/workflows/ca-cert-updater.yml
Include PR body text that has a link to the Mozilla wiki containing links to release notes for the new version.
=> Add link to CACerts change details

RELEASING.md
Hi @zdtsw I fixed the error in #3124. Please review. 
Thank you
=> fixed typo from Termurin to Temurin

.github/workflows/build.yml
Fixes the currently failing macOS build jobs
=> actions: fix failing macOS builds

RELEASING.md
- remove OPENJ9 related content
- remove links and content invalid
- update mostly for "steps for every version"
For review: https://github.com/zdtsw/temurin-build/blob/issue/3132/RELEASING.md 
Fixes: https://github.com/adoptium/temurin-build/issues/3132
=> docs: update RELEASE.md

.github/workflows/build.yml, .github/workflows/ca-cert-updater.yml, .github/workflows/comment-bot.yml, .github/workflows/labeler.yml, .github/workflows/linter.yml
Part of https://github.com/adoptium/adoptium/issues/187
Note this includes some dependency action version updates in addition to fixing to hash numbers.
=> Pin GitHub action dependencies to hashes

.github/workflows/ossf-scorecard.yml
Adds a secure dev scan and uploads reports to security tab.
=> OSSF scorecard scan action

FAQ.md
Signed-off-by: julian55455 <julianatuhwera55@gmail.com>
cc @andrew-m-leonard @zdtsw
=> Confirm how to build from a tag with make-adopt-build-farm.sh

.github/workflows/build.yml
- no need run it if it is .md files :moneybag:
=> github: only run GH action check "build" if it is scripts changes

RELEASING.md
Fixes: https://github.com/adoptium/temurin-build/issues/3157 
For review result: https://github.com/zdtsw/temurin-build/blob/issue/3157/RELEASING.md
update:
- how to generate release pipeline
- how to set expected GA tag
- how new way of auto trigger release pipeline by GA is
- jdk8 aarch32linux still need manual trigger
Do not merge till below issues/PRs are all closed:
- https://github.com/adoptium/ci-jenkins-pipelines/issues/526
- https://github.com/adoptium/ci-jenkins-pipelines/pull/525
- https://github.com/adoptium/temurin-build/issues/3167
- https://github.com/adoptium/ci-jenkins-pipelines/issues/514
=> docs: add build tags for release step and auto trigger release pipeline etc

RELEASING.md
Add instructions for before release trigger test.
=> Update RELEASING.md with auto release tag trigger instuctions

RELEASING.md
=> Update RELEASING.md auto-trigger release details

sbin/build.sh, sbin/prepareWorkspace.sh
get env variable BUILDIMAGESHA (set by docker conatiner or not set by VM build)
write value into docker.txt
=> fix: inaccurate value "using docker" in sbom

.github/code-freeze.yml
This has been tested in other repos and seems stable so should be carried over now
=> Add code freeze bot

.github/workflows/build.yml
in order to test out https://github.com/adoptium/temurin-build/pull/3210
=> GH: add test on changes under cyclonedx-lib folder

cyclonedx-lib/build.xml
Update cyclonedx-lib/build.xml to clone openkeystore and build as part of the build ant target
Ref: https://github.com/adoptium/temurin-build/issues/3158
=> Update cyclonedx-lib/build.xml to clone openkeystore and build as part of the build ant target

cyclonedx-lib/build.xml
=> Fix cyclonedx build.xml error

.github/workflows/build.yml, .github/workflows/testsbom.yml, cyclonedx-lib/build.xml
Fixes: https://github.com/adoptium/temurin-build/issues/3238
Adds a new github action to build TemurinGenSBOM.java and run its unit test
Also enables --create-sbom for the test build actions.
=> Add a github action for building and running TemurinGenSBOM unit test

sbin/prepareWorkspace.sh
See also https://github.com/eclipse-openj9/openj9/pull/16675.
=> Update openssl to version 1.1.1t

CONTRIBUTING.md, README.md, RELEASING.md, build-farm/platform-specific-configurations/linux.sh
Linked to https://github.com/adoptium/infrastructure/issues/2932
=> Change references of ci.adoptopenjdk.net to ci.adoptium.net

.github/workflows/linter.yml
Fixes: https://github.com/adoptium/temurin-build/issues/3259
=> Disable google-java-format linter

sbin/NOTICE.template
Update NOTICE template repository list.
=> Update NOTICE template file to add jdk20

.github/ISSUE_TEMPLATE/weekly-build-triage.md
Title says it all. Thoughts welcome. :)
=> Weekly build triage summary issue template creation

sbin/prepareWorkspace.sh
See also https://github.com/eclipse-openj9/openj9/pull/17468.
=> Update openssl to version 1.1.1u

.github/ISSUE_TEMPLATE/weekly-build-triage.md
This way it's easier to update throughout the week.
=> Simplify build triage template

tooling/linux_repro_compare.sh
=> Source shell script

tooling/repro_common.sh
Update mkdir with -p
Update some unzip command to turn off the verbose output
relate https://github.com/adoptium/temurin-build/issues/3245
=> Using jimage, jmod of compared jdks

cyclonedx-lib/build.xml, cyclonedx-lib/sign_src/TemurinSignSBOM.java
Build temurin-sign-sbom.jar and openkeystore in same directory build/jar as temurin-gen-sbom.jar and all other dependent jars
Exit(1) if Openration failed so ant build will exitonerror
=> Sign SBOM build update

tooling/linux_repro_compare.sh
=> Enable detailed reproducible percent information if compared builds are different

RELEASING.md
Some additions and tidy up moving detail from the Release checklist..
=> Tidy up of detail from Release Checklist

sbin/build.sh, sbin/prepareWorkspace.sh
Fixes [#3314](https://github.com/adoptium/temurin-build/issues/3314)
- GCC version
- GLIBC version
- BootJDK version
=> Populate sbom with minimal properties | reproducible builds

tooling/repro_common.sh
Create self-signed certificate for windows
Update windows tools' windows paths calling from cygwin
Turn on echo and verbose information only if command fails
=> Windows reproducible comparison update

sign.sh
Fixes #3433 
Successful test run of this change here:
https://ci.adoptium.net/job/build-scripts/job/release/job/sign_build/25728/console
=> Fix Issue With MacOS Codesigning Find Command

RELEASING.md
Plus a syntax fix in the last one.
=> More releasing guide updates

sbin/prepareWorkspace.sh
See also https://github.com/eclipse-openj9/openj9/pull/17895.
=> Update openssl to version 1.1.1v

sbin/build.sh
Related #3459 eclipse-openj9/openj9#18127
=> Don't bundle zlib for OpenJ9 builds

sbin/prepareWorkspace.sh
See also https://github.com/eclipse-openj9/openj9/pull/18161.
=> Update to openssl 3.0.11

.azure-devops/test/jobs/steps/parallel.yml, .azure-devops/test/jobs/steps/test.yml
depends on https://github.com/adoptium/aqa-tests/pull/4837
=> Rename openjdkbinary folder to jdkbinary

sbin/prepareWorkspace.sh
See also https://github.com/eclipse-openj9/openj9/pull/18338.
=> Update to openssl 3.0.12

cyclonedx-lib/getDependencies
User error by me ...
Adding same reviewers as https://github.com/adoptium/temurin-build/pull/3558
=> Fixup comment characters in getDependencies

configureBuild.sh
The support for riscv64 was merged into jdk17u mainline
=> Fix jdk17u source repo on riscv64

.github/labeler.yml
WARN: Because of https://github.com/actions/labeler?tab=readme-ov-file#notes-regarding-pull_request_target-event this PR will appear to have failed the GH Action check.  We won't know its worked until a subsequent PR is created.  This is why we can't have nice things :-)
=> fix labeler

sbin/build.sh
Cherry pick: [ec7fb8d](https://github.com/adoptium/temurin-build/commit/ec7fb8d4a2883b0ddb325e749894ffe8c6e86daf)
into release branch
=> Add Windows & Mac Compiler Fields To SBOM

test/functional/reproducibleCompare/playlist.xml
Fix #3587 
related https://github.com/adoptium/ci-jenkins-pipelines/pull/908
=> Move reproducable comparing test target to dev.system

.github/workflows/code-freeze.yml, .github/workflows/comment-bot.yml, .github/workflows/labeler.yml
Now that GH has changed the default permissions to read we need to explicitly define the permissions
=> Fix GH action permissions

.github/workflows/build-autotriage.yml, .github/workflows/ca-cert-updater.yml, .github/workflows/dependabot-auto-merge.yml, .github/workflows/testsbom.yml
Now that GH token defaults is read we need to add explicit definitions
=> fixup GH token permissions

tooling/reproducible/windows_repro_build_compare.sh
Fix WGET Output Switches And Typos in windows reproducible compare script.
=> Fix WGET Output Switches And Typos in windows reproducible compare script.

.github/workflows/code-freeze.yml
Correct code-freeze of release branch
=> Remove master from code-freeze and fix release branch regex (#3715)

test/functional/buildAndPackage/build.xml
- Add lib jcommander for smoke test
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/19122
=> Add lib jcommander for smoke test

tooling/reproducible/ReproducibleBuilds.md
Update the "Reproducible Build Tools" section of
tooling/reproducible/ReproducibleBuilds.md to reflect the reorganization of repro_compare.sh.
=> ReproducibleBuilds.md: Update "Reproducible Build Tools" section (#3729)

.azure-devops/build/steps/windows/before.yml, .github/workflows/build.yml, build-farm/platform-specific-configurations/linux.sh, docker/buildDocker.sh, tooling/reproducible/linux_repro_build_compare.sh
Ref: Trail Of Bits Security Audit
Fixes #3780 
Include checksum validation for 3rd party downloads.
=> Improve security by adding checksum validation to downloads.

.github/workflows/code-freeze.yml, .github/workflows/semgrep_diff.yml, .licenserc.yaml, RELEASING.md
Fixes https://github.com/adoptium/.github/issues/121
Update code-freeze action to use the new regex branch check workflow
=> Fix codefreeze to check PR target branch correctly

.github/workflows/code-freeze.yml
Simplify the code-freeze pull-request-target yml, remove unnecessary filter
=> Simplify the code-freeze yml

.github/workflows/semgrep_diff.yml
gha : Add permissions scheme to semgrep action
=> gha : Add permissions scheme to semgrep action

sbin/build.sh, tooling/strace_analysis.sh
Fix to various strace_analysis issues:
- Correct syntax errors
- Make work with set -eu
- Detect and log DevKit Adoptium version
- Correctly filter openjdk cloned source and openjdk build output that should not be analysed
Fixes https://github.com/adoptium/temurin-build/issues/3746
Fixes https://github.com/adoptium/temurin-build/issues/3745
Fixes https://github.com/adoptium/temurin-build/issues/3689
=> Strace fixes

sbin/prepareWorkspace.sh
See also https://github.com/eclipse-openj9/openj9/pull/19620.
=> Update to openssl 3.0.14

build-farm/platform-specific-configurations/aix.sh, sbin/build.sh
[Made](url) changes in configuration files to build JDK succesfully for AIX using OpenXLC compiler 17.1.1
=> AIX: Changes in configuration files to support OpenXL17

sbin/build.sh
Fixes: https://github.com/adoptium/temurin-build/issues/3865
Previous PR: https://github.com/adoptium/temurin-build/pull/3830 changed the ARCHITECTURE check to use the target OS arch rather than the build-farm build arch, at the time it wasn't obvious it was using the fact of the "build arch" being x64 to reason the Freetype was 2.8.1...
The patchFreetypeWindows() should be checking for actual freetype version 2.8.1 rather than assuming the version from the build ARCHITECTURE being built
jdk8u x86-32 uses Freetype 2.5.3
jdk8u x64 uses Freetype 2.8.1
Test builds:
- jdk8u win32 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-temurin/479/consoleFull
- jdk8u win64 : https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-temuri …
=> Update Windows jdk8u freetype version check to correctly update freetype.vcxproj for version 2.8.1

sbin/build.sh, tooling/strace_analysis.sh
- Add Ubuntu and dpkg check for strace analysis
- Also update build.sh to not check for rpm, as that is deffered to strace_analysis.sh
- Correct strace_analysis.sh processing to handle differing OS package query output...
Test builds:
- https://ci.adoptium.net/job/build-scripts/job/openjdk21-pipeline/313/
- https://ci.adoptium.net/job/build-scripts/job/openjdk8-pipeline/2913/
=> Update strace build to check for Ubuntu dpkg

tooling/reproducible/macos_repro_build_compare.sh
Part of: https://github.com/adoptium/ci-jenkins-pipelines/issues/1072
See also: https://github.com/adoptium/ci-jenkins-pipelines/pull/1073
=> Fix comment in macos comparison script

RELEASING.md
- Add details relevant to new jdk(HEAD) version branches
- Correct some detail that is out of date
=> RELEASING.md updates for version branch and various updates

sbin/prepareWorkspace.sh
See https://github.com/eclipse-openj9/openj9/pull/20098.
=> Update to openssl 3.0.15

sbin/common/downloaders.sh
=> Update Signature URL, so no longer case sensitive.

test/system/reproducibleCompare/playlist.xml
Depends https://github.com/adoptium/ci-jenkins-pipelines/pull/1135
Close #4025
=> Move reproducible tests to one level

sign.sh
Fixes https://github.com/adoptium/temurin-build/issues/4111
Update jdk8u signing script sign.sh to skip Microsoft Redist DLLs
Test build: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-temurin/545/ - SUCCESS
=> Update jdk8u sign.sh Eclipse signing to not sign apims Microsoft files

sbin/prepareWorkspace.sh
See https://github.com/eclipse-openj9/openj9/pull/21275
=> Update to OpenSSL 3.0.16

test/functional/buildAndPackage/src/net/adoptium/test/VendorPropertiesTest.java
resolves: https://github.com/eclipse-openj9/openj9/issues/21710
=> Update SemeruPropertiesChecks.javaVendorUrlBug test

.github/workflows/build-autotriage.yml, tooling/build_autotriage/autotriage_regexes.sh
Tested in adamfarley repo and proven to work
=> Updating JDK versions and regexes for autotriage

cyclonedx-lib/README.md
I added a placeholder section with an outline for the addition of future CycloneDX formulation support.
=> added section with plan for CycloneDX formulation support
